calc_com Module Reference
Data Types
type com_coord_type
type coord_type
type mass_ave_type
Public Member Functions
subroutine com_initialize
subroutine com_finalize (i)
integer function com_add (desc)
subroutine com_calc (i)
subroutine com_put_mass (i)
subroutine com_heading (i)
Public Attributes
integer, parameter max_masks = 10
Private Attributes
type(mask_type), dimension(max_masks),
*
target, private masks
integer, private nmasks = 0
type(com_coord_type),
*
dimension(max_masks), private coords_mass
type(coord_type), dimension(max_masks),
*
private coords
type(mass_ave_type), dimension(max_masks),
*
private mass_ave
real, dimension(max_masks), private tot_mass
Detailed Description
Definition at line 6 of file calc_com.f90.
Member Function/Subroutine Documentation
integer function calc_com::com_add (character(*) desc)
Definition at line 45 of file calc_com.f90.
References com_put_mass(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), and maskmanip::maskmanip_make().
Referenced by add_a_calc().
subroutine calc_com::com_calc (integer, intent(in) i)
Definition at line 87 of file calc_com.f90.
References atom_mask::mask_get().
Referenced by calc_all().
subroutine calc_com::com_finalize (integer i)
Definition at line 39 of file calc_com.f90.
References atom_mask::mask_finalize().
Referenced by finalize().
subroutine calc_com::com_heading (integer i)
Definition at line 139 of file calc_com.f90.
Referenced by print_headings().
subroutine calc_com::com_initialize ()
Definition at line 36 of file calc_com.f90.
Referenced by initialize().
subroutine calc_com::com_put_mass (integer i)
Definition at line 116 of file calc_com.f90.
Referenced by com_add().
Member Data Documentation
type(coord_type), dimension(max_masks), private calc_com::coords [private]
Definition at line 24 of file calc_com.f90.
type(com_coord_type), dimension(max_masks), private calc_com::coords_mass [private]
Definition at line 19 of file calc_com.f90.
type(mask_type), dimension(max_masks), target, private calc_com::masks [private]
Definition at line 14 of file calc_com.f90.
type(mass_ave_type), dimension(max_masks), private calc_com::mass_ave [private]
Definition at line 30 of file calc_com.f90.
integer, parameter calc_com::max_masks = 10
Definition at line 12 of file calc_com.f90.
integer, private calc_com::nmasks = 0 [private]
Definition at line 15 of file calc_com.f90.
real, dimension(max_masks), private calc_com::tot_mass [private]
Definition at line 32 of file calc_com.f90.
The documentation for this module was generated from the following file:
calc_com.f90