trj Module Reference
Data Types
type rec1
Public Member Functions
subroutine trj_startup
subroutine trj_shutdown
subroutine trj_initialize (frames, steps_before, interval, steps, degf, topfile)
integer function trj_add (line)
logical function trj_store_mask (line)
integer function trj_commit_mask ()
integer function trj_count ()
logical function trj_create (filename, append)
logical function trj_write (x)
logical function trj_read (x)
logical function trj_read_masked (x)
logical function trj_seek (frame)
subroutine trj_close
logical function trj_open (filename)
integer function trj_intersection (m)
subroutine trj_clone_mask (m)
integer function trj_get_ncoords ()
Public Attributes
integer, parameter max_mask_rows = 20
character(len=80), dimension(max_mask_rows) mask_row
Private Attributes
character(*), parameter, private module_version = '5.7'
character(*), parameter, private module_date = '2015-02-22'
type(rec1), private r1
character(len=80), private topology
integer, private mask_rows
integer, private lun = 0
integer, private current_frame = 0
integer, private ncoords
real(4), dimension(:),
*
allocatable, private xmasked
type(mask_type), private mask
Detailed Description
Definition at line 18 of file trj.f90.
Member Function/Subroutine Documentation
integer function trj::trj_add (character(*) line)
Definition at line 97 of file trj.f90.
References atom_mask::mask_add().
subroutine trj::trj_clone_mask (type(mask_type) m)
Definition at line 427 of file trj.f90.
Referenced by prep::trajectory().
subroutine trj::trj_close ()
Definition at line 324 of file trj.f90.
References atom_mask::mask_finalize().
Referenced by process_data(), prep::readnext(), and trj_shutdown().
integer function trj::trj_commit_mask ()
Definition at line 133 of file trj.f90.
References atom_mask::mask_add().
Referenced by md::init_trj().
integer function trj::trj_count ()
Definition at line 150 of file trj.f90.
Referenced by prep::trajectory().
logical function trj::trj_create (character(*) filename, logical, optional append)
Definition at line 154 of file trj.f90.
References misc::freefile().
Referenced by md::init_trj().
integer function trj::trj_get_ncoords ()
Definition at line 435 of file trj.f90.
Referenced by avetr::avetr_calc().
subroutine trj::trj_initialize (integer, intent(in) frames, integer, intent(in) steps_before, integer, intent(in) interval, integer, intent(in) steps, integer, intent(in) degf, character(*), intent(in) topfile)
Definition at line 67 of file trj.f90.
References atom_mask::mask_initialize().
Referenced by md::init_trj().
integer function trj::trj_intersection (type(mask_type) m)
Definition at line 420 of file trj.f90.
Referenced by prep::trajectory().
logical function trj::trj_open (character(*) filename)
Definition at line 338 of file trj.f90.
References misc::freefile(), atom_mask::mask_add(), and atom_mask::mask_initialize().
Referenced by get_coordfile(), and prep::trajectory().
logical function trj::trj_read (real(8), dimension(:) x)
Definition at line 231 of file trj.f90.
References atom_mask::mask_put().
Referenced by process_data(), and prep::readnext().
logical function trj::trj_read_masked (real(4), dimension(:) x)
Definition at line 259 of file trj.f90.
Referenced by avetr::avetr_calc().
logical function trj::trj_seek (integer frame)
Definition at line 281 of file trj.f90.
Referenced by prep::readframe().
subroutine trj::trj_shutdown ()
Definition at line 61 of file trj.f90.
References atom_mask::mask_shutdown(), and trj_close().
Referenced by prep::prep_shutdown().
subroutine trj::trj_startup ()
Definition at line 55 of file trj.f90.
References atom_mask::mask_startup().
Referenced by md::md_startup().
logical function trj::trj_store_mask (character(*) line)
Definition at line 117 of file trj.f90.
Referenced by md::initialize().
logical function trj::trj_write (real(8), dimension(:) x)
Definition at line 206 of file trj.f90.
References atom_mask::mask_get().
Referenced by md::write_trj().
Member Data Documentation
integer, private trj::current_frame = 0 [private]
Definition at line 45 of file trj.f90.
integer, private trj::lun = 0 [private]
Definition at line 44 of file trj.f90.
type(mask_type), private trj::mask [private]
Definition at line 50 of file trj.f90.
character(len=80), dimension(max_mask_rows) trj::mask_row
Definition at line 42 of file trj.f90.
integer, private trj::mask_rows [private]
Definition at line 40 of file trj.f90.
integer, parameter trj::max_mask_rows = 20
Definition at line 41 of file trj.f90.
character(*), parameter, private trj::module_date = '2015-02-22' [private]
Definition at line 25 of file trj.f90.
character(*), parameter, private trj::module_version = '5.7' [private]
Definition at line 24 of file trj.f90.
integer, private trj::ncoords [private]
Definition at line 48 of file trj.f90.
type(rec1), private trj::r1 [private]
Definition at line 37 of file trj.f90.
character(len=80), private trj::topology [private]
Definition at line 39 of file trj.f90.
real(4), dimension(:), allocatable, private trj::xmasked [private]
Definition at line 49 of file trj.f90.
The documentation for this module was generated from the following file:
trj.f90