calc_pmf Module Reference
Data Types
type atom_type_conversion
type bond_pointer
type donor
type q_atom
type q_bond
type tabsdetail
type tpmfatom
type tpmfbond
type tpmfedge
type tpmfinput
type tpmfmolecule
type tpmfnames
type tpmfring
type tpmfrule
type tpmfscore
type tpmfvertex
Public Member Functions
subroutine pmfreadatomtypeconversions (filename, chType)
subroutine pmfread_input
subroutine pmfread_inputqatom
subroutine pmf_extract_rules (filename)
subroutine pmf_show_rule (rule)
subroutine pmfread_data (filename)
subroutine pmfread_names (filename)
subroutine pmf_precalc
subroutine pmfscoring_stats (mol, iAtom)
subroutine pmfshow_abs (mol)
real function pmf_score (lig, prot, inp)
integer function pmfgetindex (atom)
real function pmf_distance (a, b)
subroutine pmfprotein_translate (protein, nAtoms, coordinates, bond, num_bond, transfer_waters)
subroutine pmfligand_translate (ligand, nAtoms, nBonds, aQ, aB, offset)
subroutine pmffixatomtypes (mol)
subroutine pmfvalue_molecule (mol, rule, count, prot, literun)
subroutine pmfassign_planar (mol)
integer function pmfeval_rule (atom, mol, r)
integer function pmfeval_bonds (atom, mol, r)
integer function pmfbonds_single (atom, mol)
integer function pmfbonds_double (atom, mol)
pure integer function pmfbonds_triple (atom, mol)
pure integer function pmfbonds_aromatic (atom, mol)
integer function pmfbonds_metal (atom, mol)
subroutine pmfassign_hybr (mol)
subroutine pmfassign_polarity (mol)
subroutine pmfassign_rings (mol, l)
recursive subroutine pmfatom_walk (start, mol, path, c, limit)
subroutine pmfreport_ring (mol, path, c)
subroutine pmfint_pushback (array, int)
integer function pmfmolecule_look_for_a_ring (molecule, bond_id, atom_path, bond_path, required_size)
subroutine pmfmolecule_clean_choices (molecule, tried_choice, choice)
integer function pmfmolecule_get_choices (molecule, choice, wrong_end, current_path_length, current_path)
subroutine pmfmolecule_reset_choices (molecule, bond_id, choice)
integer function pmfmolecule_two_bonds_connection_check (bond1, bond2)
subroutine pmfassign_aromatic (mol, req_ring)
subroutine pmfassign_charge (mol)
subroutine pmfassign_hbchar (mol)
subroutine pmfshow_molecule (mol)
subroutine pmfsort_bonds
subroutine pmf_calc (iCalc, iFrame)
subroutine pmflog_frame (iFrame, ligand)
integer function pmf_add (desc)
subroutine pmf_initialize
subroutine pmf_finalize
subroutine pmf_heading (i)
subroutine pmfscore_mean
subroutine pmfdetect_connections (molecule)
real function pmfangle_of_two_vectors (v1, v2)
real function pmfangle (a, b, c)
Public Attributes
type(tpmfrule), dimension(:),
*
pointer protrule
integer prot_num_rule
type(tpmfrule), dimension(:),
*
pointer ligrule
integer lig_num_rule
integer, public single = 1
integer, public double = 2
integer, public aromatic = 3
integer, public amide = 4
character *80 top_file
character *80 fep_file
character *80 atom_data_file
character *80 coord_file
integer, dimension(:), allocatable iqatom
integer nhq
integer nhb
integer(ai), dimension(:),
*
allocatable lph_r
integer(ai), dimension(:),
*
allocatable lph_l
type(donor), dimension(:),
*
allocatable hbd_r
type(donor), dimension(:),
*
allocatable hbd_l
integer(ai), dimension(:),
*
allocatable hba_r
integer(ai), dimension(:),
*
allocatable hba_l
integer(ai), dimension(:),
*
allocatable met_r
integer nlph_r
integer nlph_l
integer nhbd_r
integer nhbd_l
integer nhba_r
integer nhba_l
integer nmet_r
integer nwaters
integer nqbonds
integer nhbd_prot
integer nhba_prot
integer nrings
integer, dimension(:), allocatable pol_con
integer, parameter max_masks = 10
integer bdotopcalc
integer bsecondpass
type(tpmfmolecule), public protein
type(tpmfmolecule), public ligand
type(tpmfmolecule), dimension(:),
*
allocatable, public cofactor
integer, dimension(:), pointer top2prot
type(tpmfinput), public input
character(len=256) chinput
type(tpmfnames), dimension(:),
*
pointer pmf_names
type(atom_type_conversion),
*
dimension(:), allocatable atomtypetable
integer num_atomtype
real, dimension(34, 16, 60) pmfdata
character(len=2), dimension(2, 34) pmftype
integer, parameter nprot = 16
integer, parameter nlig = 34
type(tpmfscore), dimension(:),
*
pointer pmfscores
integer npmfscores
integer maxpmfscores
integer max_bond_neib = 10
integer max_atom_neib = 6
integer, public err
integer, public warn
integer, public waterwarn
Private Attributes
type(q_atom), dimension(:),
*
allocatable, target, private q_atoms
type(q_bond), dimension(:),
*
allocatable, target, private q_bonds
type(q_atom), dimension(:),
*
allocatable, target, private ahq
type(q_bond), dimension(:),
*
allocatable, target, private ahb
type(mask_type), dimension(max_masks),
*
target, private masks
integer, private nmasks = 0
Detailed Description
Definition at line 7 of file calc_pmfscore.f90.
Member Function/Subroutine Documentation
integer function calc_pmf::pmf_add (character(*), intent(out) desc)
Definition at line 2611 of file calc_pmfscore.f90.
References misc::getlin(), misc::locase(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), and maskmanip::maskmanip_make().
Referenced by add_a_calc().
subroutine calc_pmf::pmf_calc (integer, intent(in) iCalc, integer, intent(in) iFrame)
Definition at line 2557 of file calc_pmfscore.f90.
References pmf_score(), pmflog_frame(), and pmfscoring_stats().
Referenced by calc_all().
real function calc_pmf::pmf_distance (real(8), dimension(0:2) a, real(8), dimension(0:2) b)
Definition at line 1021 of file calc_pmfscore.f90.
Referenced by pmf_score().
subroutine calc_pmf::pmf_extract_rules (character(len=256) filename)
Definition at line 570 of file calc_pmfscore.f90.
References misc::freefile().
Referenced by pmf_precalc().
subroutine calc_pmf::pmf_finalize ()
Definition at line 2667 of file calc_pmfscore.f90.
Referenced by finalize().
subroutine calc_pmf::pmf_heading (integer, intent(in) i)
Definition at line 2689 of file calc_pmfscore.f90.
Referenced by print_headings().
subroutine calc_pmf::pmf_initialize ()
Definition at line 2659 of file calc_pmfscore.f90.
Referenced by initialize().
subroutine calc_pmf::pmf_precalc ()
Definition at line 799 of file calc_pmfscore.f90.
References pmf_extract_rules(), pmf_score(), pmfligand_translate(), pmfprotein_translate(), pmfread_data(), pmfread_input(), pmfread_inputqatom(), pmfread_names(), pmfreadatomtypeconversions(), pmfscoring_stats(), pmfshow_molecule(), pmfsort_bonds(), pmfvalue_molecule(), and qatom::qatom_load_atoms().
Referenced by do_pre_calcs().
real function calc_pmf::pmf_score (type(tpmfmolecule) lig, type(tpmfmolecule) prot, type(tpmfinput) inp)
Definition at line 934 of file calc_pmfscore.f90.
References pmf_distance(), pmfgetindex(), and calc_rdf::r().
Referenced by pmf_calc(), and pmf_precalc().
subroutine calc_pmf::pmf_show_rule (type(tpmfrule) rule)
Definition at line 676 of file calc_pmfscore.f90.
real function calc_pmf::pmfangle (real, dimension(0:2) a, real, dimension(0:2) b, real, dimension(0:2) c)
Definition at line 2931 of file calc_pmfscore.f90.
References pmfangle_of_two_vectors().
real function calc_pmf::pmfangle_of_two_vectors (real, dimension(0:2) v1, real, dimension(0:2) v2)
Definition at line 2909 of file calc_pmfscore.f90.
References calc_chemscore::angle().
Referenced by pmfangle().
subroutine calc_pmf::pmfassign_aromatic (type(tpmfmolecule) mol, integer, optional req_ring)
Definition at line 2322 of file calc_pmfscore.f90.
Referenced by pmfvalue_molecule().
subroutine calc_pmf::pmfassign_charge (type(tpmfmolecule) mol)
Definition at line 2339 of file calc_pmfscore.f90.
Referenced by pmfvalue_molecule().
subroutine calc_pmf::pmfassign_hbchar (type(tpmfmolecule) mol)
Definition at line 2353 of file calc_pmfscore.f90.
Referenced by pmfvalue_molecule().
subroutine calc_pmf::pmfassign_hybr (type(tpmfmolecule) mol)
Definition at line 1675 of file calc_pmfscore.f90.
Referenced by pmfvalue_molecule().
subroutine calc_pmf::pmfassign_planar (type(tpmfmolecule) mol)
Definition at line 1410 of file calc_pmfscore.f90.
Referenced by pmfvalue_molecule().
subroutine calc_pmf::pmfassign_polarity (type(tpmfmolecule) mol)
Definition at line 1925 of file calc_pmfscore.f90.
Referenced by pmfvalue_molecule().
subroutine calc_pmf::pmfassign_rings (type(tpmfmolecule) mol, integer l)
Definition at line 1942 of file calc_pmfscore.f90.
References pmfatom_walk().
Referenced by pmfvalue_molecule().
recursive subroutine calc_pmf::pmfatom_walk (integer start, type(tpmfmolecule) mol, integer, dimension(:), pointer path, integer c, integer limit)
Definition at line 1986 of file calc_pmfscore.f90.
References pmfreport_ring(), and calc_chemscore::start().
Referenced by pmfassign_rings().
pure integer function calc_pmf::pmfbonds_aromatic (type(tpmfatom), intent(in) atom, type(tpmfmolecule), intent(in) mol)
Definition at line 1642 of file calc_pmfscore.f90.
integer function calc_pmf::pmfbonds_double (type(tpmfatom), intent(in) atom, type(tpmfmolecule), intent(in) mol)
Definition at line 1620 of file calc_pmfscore.f90.
integer function calc_pmf::pmfbonds_metal (type(tpmfatom), intent(in) atom, type(tpmfmolecule), intent(in) mol)
Definition at line 1653 of file calc_pmfscore.f90.
References pmfeval_rule().
integer function calc_pmf::pmfbonds_single (type(tpmfatom), intent(in) atom, type(tpmfmolecule), intent(in) mol)
Definition at line 1609 of file calc_pmfscore.f90.
pure integer function calc_pmf::pmfbonds_triple (type(tpmfatom), intent(in) atom, type(tpmfmolecule), intent(in) mol)
Definition at line 1631 of file calc_pmfscore.f90.
subroutine calc_pmf::pmfdetect_connections (type(tpmfmolecule), intent(inout) molecule)
Definition at line 2714 of file calc_pmfscore.f90.
References pmfmolecule_two_bonds_connection_check().
Referenced by pmfvalue_molecule().
integer function calc_pmf::pmfeval_bonds (type(tpmfatom), intent(inout) atom, type(tpmfmolecule), intent(in) mol, character(len=37), intent(in) r)
Definition at line 1509 of file calc_pmfscore.f90.
References calc_rdf::r().
Referenced by pmfeval_rule().
integer function calc_pmf::pmfeval_rule (type(tpmfatom) atom, type(tpmfmolecule) mol, character, intent(in) r)
Definition at line 1437 of file calc_pmfscore.f90.
References pmfeval_bonds(), and calc_rdf::r().
Referenced by pmfbonds_metal(), and pmfvalue_molecule().
subroutine calc_pmf::pmffixatomtypes (type(tpmfmolecule) mol)
Definition at line 1262 of file calc_pmfscore.f90.
Referenced by pmfvalue_molecule().
integer function calc_pmf::pmfgetindex (type(tpmfatom) atom)
Definition at line 1005 of file calc_pmfscore.f90.
Referenced by pmf_score().
subroutine calc_pmf::pmfint_pushback (integer, dimension(:), pointer array, integer int)
Definition at line 2090 of file calc_pmfscore.f90.
subroutine calc_pmf::pmfligand_translate (type(tpmfmolecule), intent(out) ligand, integer, intent(in) nAtoms, integer, intent(in) nBonds, type(q_atom), dimension(:), intent(in) aQ, type(q_bond), dimension(:), intent(in) aB, integer offset)
Definition at line 1156 of file calc_pmfscore.f90.
Referenced by pmf_precalc().
subroutine calc_pmf::pmflog_frame (integer, intent(in) iFrame, type(tpmfmolecule) ligand)
Definition at line 2591 of file calc_pmfscore.f90.
Referenced by pmf_calc().
subroutine calc_pmf::pmfmolecule_clean_choices (type(tpmfmolecule) molecule, integer tried_choice, integer, dimension(0:max_bond_neib-1) choice)
Definition at line 2205 of file calc_pmfscore.f90.
Referenced by pmfmolecule_look_for_a_ring().
integer function calc_pmf::pmfmolecule_get_choices (type(tpmfmolecule) molecule, integer, dimension(0:max_bond_neib -1) choice, integer wrong_end, integer current_path_length, integer, dimension(:), pointer current_path)
Definition at line 2223 of file calc_pmfscore.f90.
Referenced by pmfmolecule_look_for_a_ring().
integer function calc_pmf::pmfmolecule_look_for_a_ring (type(tpmfmolecule), intent(inout) molecule, integer bond_id, integer, dimension(:), pointer atom_path, integer, dimension(:), pointer bond_path, integer required_size)
Definition at line 2113 of file calc_pmfscore.f90.
References pmfmolecule_clean_choices(), pmfmolecule_get_choices(), pmfmolecule_reset_choices(), and pmfmolecule_two_bonds_connection_check().
subroutine calc_pmf::pmfmolecule_reset_choices (type(tpmfmolecule) molecule, integer bond_id, integer, dimension(0:max_bond_neib -1) choice)
Definition at line 2270 of file calc_pmfscore.f90.
Referenced by pmfmolecule_look_for_a_ring().
integer function calc_pmf::pmfmolecule_two_bonds_connection_check (type(tpmfbond) bond1, type(tpmfbond) bond2)
Definition at line 2294 of file calc_pmfscore.f90.
Referenced by pmfdetect_connections(), and pmfmolecule_look_for_a_ring().
subroutine calc_pmf::pmfprotein_translate (type(tpmfmolecule) protein, integer nAtoms, real(8), dimension(:) coordinates, type(bond_type), dimension(:) bond, integer num_bond, integer, optional transfer_waters)
Definition at line 1034 of file calc_pmfscore.f90.
References md::bond().
Referenced by pmf_precalc().
subroutine calc_pmf::pmfread_data (character(len=256) filename)
Definition at line 686 of file calc_pmfscore.f90.
References misc::freefile().
Referenced by pmf_precalc().
subroutine calc_pmf::pmfread_input ()
Definition at line 425 of file calc_pmfscore.f90.
References misc::freefile(), and misc::upcase().
Referenced by pmf_precalc().
subroutine calc_pmf::pmfread_inputqatom ()
Definition at line 533 of file calc_pmfscore.f90.
Referenced by pmf_precalc().
subroutine calc_pmf::pmfread_names (character(len=256) filename)
Definition at line 738 of file calc_pmfscore.f90.
References misc::freefile().
Referenced by pmf_precalc().
subroutine calc_pmf::pmfreadatomtypeconversions (character(len=256) filename, character(len=20) chType)
Definition at line 281 of file calc_pmfscore.f90.
References misc::freefile(), and misc::locase().
Referenced by pmf_precalc().
subroutine calc_pmf::pmfreport_ring (type(tpmfmolecule) mol, integer, dimension(:), pointer path, integer c)
Definition at line 2030 of file calc_pmfscore.f90.
Referenced by pmfatom_walk().
subroutine calc_pmf::pmfscore_mean ()
Definition at line 2694 of file calc_pmfscore.f90.
Referenced by make_mean_all().
subroutine calc_pmf::pmfscoring_stats (type(tpmfmolecule) mol, integer, optional iAtom)
Definition at line 889 of file calc_pmfscore.f90.
Referenced by pmf_calc(), and pmf_precalc().
subroutine calc_pmf::pmfshow_abs (type(tpmfmolecule) mol)
Definition at line 924 of file calc_pmfscore.f90.
subroutine calc_pmf::pmfshow_molecule (type(tpmfmolecule) mol)
Definition at line 2411 of file calc_pmfscore.f90.
Referenced by pmf_precalc().
subroutine calc_pmf::pmfsort_bonds ()
Definition at line 2515 of file calc_pmfscore.f90.
Referenced by pmf_precalc().
subroutine calc_pmf::pmfvalue_molecule (type(tpmfmolecule), intent(inout) mol, type(tpmfrule), dimension(:), pointer rule, integer count, integer, optional prot, integer, optional literun)
Definition at line 1301 of file calc_pmfscore.f90.
References pmfassign_aromatic(), pmfassign_charge(), pmfassign_hbchar(), pmfassign_hybr(), pmfassign_planar(), pmfassign_polarity(), pmfassign_rings(), pmfdetect_connections(), pmfeval_rule(), and pmffixatomtypes().
Referenced by pmf_precalc().
Member Data Documentation
type(q_bond), dimension(:), allocatable, target, private calc_pmf::ahb [private]
Definition at line 207 of file calc_pmfscore.f90.
type(q_atom), dimension(:), allocatable, target, private calc_pmf::ahq [private]
Definition at line 206 of file calc_pmfscore.f90.
integer, public calc_pmf::amide = 4
Definition at line 196 of file calc_pmfscore.f90.
integer, public calc_pmf::aromatic = 3
Definition at line 195 of file calc_pmfscore.f90.
character*80 calc_pmf::atom_data_file
Definition at line 199 of file calc_pmfscore.f90.
type(atom_type_conversion), dimension(:), allocatable calc_pmf::atomtypetable
Definition at line 250 of file calc_pmfscore.f90.
integer calc_pmf::bdotopcalc
Definition at line 234 of file calc_pmfscore.f90.
integer calc_pmf::bsecondpass
Definition at line 235 of file calc_pmfscore.f90.
character(len=256) calc_pmf::chinput
Definition at line 245 of file calc_pmfscore.f90.
type(tpmfmolecule), dimension(:), allocatable, public calc_pmf::cofactor
Definition at line 240 of file calc_pmfscore.f90.
character*80 calc_pmf::coord_file
Definition at line 200 of file calc_pmfscore.f90.
integer, public calc_pmf::double = 2
Definition at line 194 of file calc_pmfscore.f90.
integer, public calc_pmf::err
Definition at line 276 of file calc_pmfscore.f90.
character*80 calc_pmf::fep_file
Definition at line 198 of file calc_pmfscore.f90.
integer(ai), dimension(:), allocatable calc_pmf::hba_l
Definition at line 217 of file calc_pmfscore.f90.
integer(ai), dimension(:), allocatable calc_pmf::hba_r
Definition at line 216 of file calc_pmfscore.f90.
type(donor), dimension(:), allocatable calc_pmf::hbd_l
Definition at line 215 of file calc_pmfscore.f90.
type(donor), dimension(:), allocatable calc_pmf::hbd_r
Definition at line 214 of file calc_pmfscore.f90.
type(tpmfinput), public calc_pmf::input
Definition at line 244 of file calc_pmfscore.f90.
integer, dimension(:), allocatable calc_pmf::iqatom
Definition at line 204 of file calc_pmfscore.f90.
integer calc_pmf::lig_num_rule
Definition at line 187 of file calc_pmfscore.f90.
type(tpmfmolecule), public calc_pmf::ligand
Definition at line 239 of file calc_pmfscore.f90.
type(tpmfrule), dimension(:), pointer calc_pmf::ligrule
Definition at line 186 of file calc_pmfscore.f90.
integer(ai), dimension(:), allocatable calc_pmf::lph_l
Definition at line 213 of file calc_pmfscore.f90.
integer(ai), dimension(:), allocatable calc_pmf::lph_r
Definition at line 212 of file calc_pmfscore.f90.
type(mask_type), dimension(max_masks), target, private calc_pmf::masks [private]
Definition at line 230 of file calc_pmfscore.f90.
integer calc_pmf::max_atom_neib = 6
Definition at line 275 of file calc_pmfscore.f90.
integer calc_pmf::max_bond_neib = 10
Definition at line 274 of file calc_pmfscore.f90.
integer, parameter calc_pmf::max_masks = 10
Definition at line 229 of file calc_pmfscore.f90.
integer calc_pmf::maxpmfscores
Definition at line 271 of file calc_pmfscore.f90.
integer(ai), dimension(:), allocatable calc_pmf::met_r
Definition at line 218 of file calc_pmfscore.f90.
integer calc_pmf::nhb
Definition at line 210 of file calc_pmfscore.f90.
integer calc_pmf::nhba_l
Definition at line 223 of file calc_pmfscore.f90.
integer calc_pmf::nhba_prot
Definition at line 224 of file calc_pmfscore.f90.
integer calc_pmf::nhba_r
Definition at line 223 of file calc_pmfscore.f90.
integer calc_pmf::nhbd_l
Definition at line 222 of file calc_pmfscore.f90.
integer calc_pmf::nhbd_prot
Definition at line 224 of file calc_pmfscore.f90.
integer calc_pmf::nhbd_r
Definition at line 222 of file calc_pmfscore.f90.
integer calc_pmf::nhq
Definition at line 209 of file calc_pmfscore.f90.
integer, parameter calc_pmf::nlig = 34
Definition at line 257 of file calc_pmfscore.f90.
integer calc_pmf::nlph_l
Definition at line 222 of file calc_pmfscore.f90.
integer calc_pmf::nlph_r
Definition at line 222 of file calc_pmfscore.f90.
integer, private calc_pmf::nmasks = 0 [private]
Definition at line 231 of file calc_pmfscore.f90.
integer calc_pmf::nmet_r
Definition at line 223 of file calc_pmfscore.f90.
integer calc_pmf::npmfscores
Definition at line 271 of file calc_pmfscore.f90.
integer, parameter calc_pmf::nprot = 16
Definition at line 257 of file calc_pmfscore.f90.
integer calc_pmf::nqbonds
Definition at line 223 of file calc_pmfscore.f90.
integer calc_pmf::nrings
Definition at line 225 of file calc_pmfscore.f90.
integer calc_pmf::num_atomtype
Definition at line 251 of file calc_pmfscore.f90.
integer calc_pmf::nwaters
Definition at line 223 of file calc_pmfscore.f90.
type(tpmfnames), dimension(:), pointer calc_pmf::pmf_names
Definition at line 249 of file calc_pmfscore.f90.
real, dimension(34,16,60) calc_pmf::pmfdata
Definition at line 254 of file calc_pmfscore.f90.
type(tpmfscore), dimension(:), pointer calc_pmf::pmfscores
Definition at line 270 of file calc_pmfscore.f90.
character(len=2), dimension(2,34) calc_pmf::pmftype
Definition at line 255 of file calc_pmfscore.f90.
integer, dimension(:), allocatable calc_pmf::pol_con
Definition at line 227 of file calc_pmfscore.f90.
integer calc_pmf::prot_num_rule
Definition at line 185 of file calc_pmfscore.f90.
type(tpmfmolecule), public calc_pmf::protein
Definition at line 238 of file calc_pmfscore.f90.
type(tpmfrule), dimension(:), pointer calc_pmf::protrule
Definition at line 184 of file calc_pmfscore.f90.
type(q_atom), dimension(:), allocatable, target, private calc_pmf::q_atoms [private]
Definition at line 202 of file calc_pmfscore.f90.
type(q_bond), dimension(:), allocatable, target, private calc_pmf::q_bonds [private]
Definition at line 203 of file calc_pmfscore.f90.
integer, public calc_pmf::single = 1
Definition at line 193 of file calc_pmfscore.f90.
integer, dimension(:), pointer calc_pmf::top2prot
Definition at line 241 of file calc_pmfscore.f90.
character*80 calc_pmf::top_file
Definition at line 198 of file calc_pmfscore.f90.
integer, public calc_pmf::warn
Definition at line 277 of file calc_pmfscore.f90.
integer, public calc_pmf::waterwarn
Definition at line 277 of file calc_pmfscore.f90.
The documentation for this module was generated from the following file:
calc_pmfscore.f90