calc_rdf Module Reference
Data Types
type rdf_calc_type
type rdf_list_type
Public Member Functions
subroutine rdf_initialize
subroutine rdf_finalize (i)
integer function rdf_add (desc)
subroutine rdf_calc (i)
subroutine rdf_heading (i)
real function r (a, b)
integer function rdf_make_list (mask1, mask2, rdf_list)
Public Attributes
integer, parameter max_masks = 10
real(8) pi
Private Attributes
type(mask_type), dimension(2),
*
target, private temp_masks
integer, private ats1
integer, private ats2
integer, private nmasks = 0
type(rdf_calc_type), dimension(max_masks),
*
private rdf_calcs
type(rdf_list_type), dimension(:),
*
allocatable, private rdf_listan
Detailed Description
Definition at line 8 of file calc_rdf.f90.
Member Function/Subroutine Documentation
real function calc_rdf::r (integer a, integer b)
Definition at line 198 of file calc_rdf.f90.
Referenced by calc_geom::dist_calc(), calc_com_ke::eigen(), eigen(), calc_xscore::forcefield_get_surface_dot(), calc_xscore::forcefield_get_surface_dot_rxyz(), prep::makehyds(), calc_xscore::molecule_add_ring(), calc_nb::nb_calc_lists(), md::nonbon2_pw(), md::nonbon2_pw_box(), md::nonbon2_qp(), md::nonbon2_qp_box(), md::nonbon2_qq(), md::nonbon2_qq_lib_charges(), md::nonbon2_ww(), md::nonbon2_ww_box(), md::nonbond_monitor(), md::nonbond_pw(), md::nonbond_pw_box(), md::nonbond_qp(), md::nonbond_qp_box(), md::nonbond_qp_qvdw(), md::nonbond_qp_qvdw_box(), md::nonbond_qq(), md::nonbond_qq_lib_charges(), md::offdiag(), calc_pmf::pmf_score(), calc_pmf::pmfeval_bonds(), calc_pmf::pmfeval_rule(), calc_xscore::protein_add_ring(), prep::randm(), md::randm(), rdf_calc(), calc_xscore::ring_copy(), calc_rms::rms_calc(), calc_rmsf::rmsf_calc(), nrgy::sum_bonded(), nrgy::sum_non_bonded(), and tqli().
integer function calc_rdf::rdf_add (character(*) desc)
Definition at line 85 of file calc_rdf.f90.
References parse::get_int_arg(), parse::get_real_arg(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), maskmanip::maskmanip_make(), and rdf_make_list().
Referenced by add_a_calc().
subroutine calc_rdf::rdf_calc (integer, intent(in) i)
Definition at line 149 of file calc_rdf.f90.
References calc_chemscore::dist(), and r().
Referenced by calc_all().
subroutine calc_rdf::rdf_finalize (integer i)
Definition at line 45 of file calc_rdf.f90.
Referenced by finalize().
subroutine calc_rdf::rdf_heading (integer i)
Definition at line 189 of file calc_rdf.f90.
Referenced by print_headings().
subroutine calc_rdf::rdf_initialize ()
Definition at line 41 of file calc_rdf.f90.
Referenced by initialize().
integer function calc_rdf::rdf_make_list (type(mask_type), intent(in) mask1, type(mask_type), intent(in) mask2, type(rdf_list_type) rdf_list)
Definition at line 224 of file calc_rdf.f90.
Referenced by rdf_add().
Member Data Documentation
integer, private calc_rdf::ats1 [private]
Definition at line 20 of file calc_rdf.f90.
integer, private calc_rdf::ats2 [private]
Definition at line 20 of file calc_rdf.f90.
integer, parameter calc_rdf::max_masks = 10
Definition at line 15 of file calc_rdf.f90.
integer, private calc_rdf::nmasks = 0 [private]
Definition at line 20 of file calc_rdf.f90.
real(8) calc_rdf::pi
Definition at line 31 of file calc_rdf.f90.
type(rdf_calc_type), dimension(max_masks), private calc_rdf::rdf_calcs [private]
Definition at line 30 of file calc_rdf.f90.
type(rdf_list_type), dimension(:), allocatable, private calc_rdf::rdf_listan [private]
Definition at line 37 of file calc_rdf.f90.
type(mask_type), dimension(2), target, private calc_rdf::temp_masks [private]
Definition at line 18 of file calc_rdf.f90.
The documentation for this module was generated from the following file:
calc_rdf.f90