calc_geom Module Reference
Data Types
type geom_type
Public Member Functions
subroutine geom_initialize
subroutine geom_finalize
integer function dist_add (desc)
integer function angle_add (desc)
integer function torsion_add (desc)
subroutine dist_calc (i)
subroutine angle_calc (i)
subroutine torsion_calc (i)
subroutine dist_heading (i)
subroutine angle_heading (i)
subroutine torsion_heading (i)
Public Attributes
integer, parameter max_measurements = 99
real(8) pi
Private Attributes
integer, private nmeas = 0
type(geom_type), dimension(max_measurements),
*
private geom
Detailed Description
Definition at line 6 of file calc_geom.f90.
Member Function/Subroutine Documentation
integer function calc_geom::angle_add (character(*) desc)
Definition at line 79 of file calc_geom.f90.
Referenced by add_a_calc().
subroutine calc_geom::angle_calc (integer, intent(in) i)
Definition at line 219 of file calc_geom.f90.
Referenced by calc_all().
subroutine calc_geom::angle_heading (integer i)
Definition at line 304 of file calc_geom.f90.
Referenced by print_headings().
integer function calc_geom::dist_add (character(*) desc)
Definition at line 30 of file calc_geom.f90.
Referenced by add_a_calc().
subroutine calc_geom::dist_calc (integer, intent(in) i)
Definition at line 195 of file calc_geom.f90.
References calc_rdf::r().
Referenced by calc_all().
subroutine calc_geom::dist_heading (integer i)
Definition at line 293 of file calc_geom.f90.
Referenced by print_headings().
subroutine calc_geom::geom_finalize ()
Definition at line 27 of file calc_geom.f90.
subroutine calc_geom::geom_initialize ()
Definition at line 23 of file calc_geom.f90.
Referenced by initialize().
integer function calc_geom::torsion_add (character(*) desc)
Definition at line 135 of file calc_geom.f90.
Referenced by add_a_calc().
subroutine calc_geom::torsion_calc (integer, intent(in) i)
Definition at line 249 of file calc_geom.f90.
Referenced by calc_all().
subroutine calc_geom::torsion_heading (integer i)
Definition at line 315 of file calc_geom.f90.
Referenced by print_headings().
Member Data Documentation
type(geom_type), dimension(max_measurements), private calc_geom::geom [private]
Definition at line 20 of file calc_geom.f90.
integer, parameter calc_geom::max_measurements = 99
Definition at line 11 of file calc_geom.f90.
integer, private calc_geom::nmeas = 0 [private]
Definition at line 15 of file calc_geom.f90.
real(8) calc_geom::pi
Definition at line 14 of file calc_geom.f90.
The documentation for this module was generated from the following file:
calc_geom.f90