nrgy Module Reference
Data Types
type bonded_energies
type energies
type nb_energies
type offdiag_aux
type offdiag_save
interface operator(*)
interface operator(+)
type q_energies
type restraint_energies
Public Member Functions
subroutine nrgy_startup
subroutine put_ene (unit, e2, OFFD)
integer function get_ene (unit, e2, OFFD, nstates, noffd)
type(q_energies) function,
*
dimension(size(e1)) add_ene (e1, e2)
type(q_energies) function,
*
dimension(size(e1)) scale_ene (e1, k)
real(8) function sum_bonded (r, eb)
real(8) function sum_non_bonded (r, enb)
Public Attributes
character(*), parameter nrgy_version = '5.01'
character(*), parameter nrgy_date = '2003-06-02'
Detailed Description
Definition at line 6 of file nrgy.f90.
Member Function/Subroutine Documentation
type(q_energies) function, dimension (size (e1)) nrgy::add_ene (type(q_energies), dimension (:), intent(in) e1, type(q_energies), dimension (size (e1)), intent(in) e2)
Definition at line 151 of file nrgy.f90.
References nrgy::operator(+)::add_ene().
integer function nrgy::get_ene (integer unit, type(q_energies), dimension(:), intent(out) e2, type(offdiag_save), dimension(:), intent(out) OFFD, integer, optional nstates, integer, optional noffd)
Definition at line 104 of file nrgy.f90.
Referenced by qfep().
subroutine nrgy::nrgy_startup ()
Definition at line 69 of file nrgy.f90.
Referenced by qatom::qatom_startup().
subroutine nrgy::put_ene (integer unit, type(q_energies), dimension(:), intent(in) e2, type(offdiag_save), dimension(:), intent(in) OFFD)
Definition at line 74 of file nrgy.f90.
Referenced by md::md_run().
type(q_energies) function, dimension (size (e1)) nrgy::scale_ene (type(q_energies), dimension (:), intent(in) e1, real, intent(in) k)
Definition at line 174 of file nrgy.f90.
References nrgy::operator(*)::scale_ene().
real(8) function nrgy::sum_bonded (real(8), intent(in) r, type(bonded_energies), intent(in) eb)
Definition at line 198 of file nrgy.f90.
References calc_rdf::r().
real(8) function nrgy::sum_non_bonded (real(8), intent(in) r, type(nb_energies), intent(in) enb)
Definition at line 207 of file nrgy.f90.
References calc_rdf::r().
Member Data Documentation
character(*), parameter nrgy::nrgy_date = '2003-06-02'
Definition at line 12 of file nrgy.f90.
character(*), parameter nrgy::nrgy_version = '5.01'
Definition at line 11 of file nrgy.f90.
The documentation for this module was generated from the following file:
nrgy.f90