prep Module Reference
Data Types
type angle_type_type
type bond_prm_type
type bond_type_type
type imp_prm_type
type lib_bond_type
type lib_entry_type
type lib_imp_type
type lib_rule_type
type tor_codes
type torsion_type_type
Public Member Functions
subroutine prep_startup
subroutine allocate_for_pdb (atoms, residues, molecules)
subroutine prep_shutdown
subroutine clearlib
subroutine addbond
subroutine clearbond
subroutine angle_ene (emax, nlarge, av_ene)
integer function anglecode (taci, tacj, tack)
subroutine bond_ene (emax, nlarge, av_ene)
character(KEYLENGTH) function wildcard_tac (taci)
integer function bondcode (taci, tacj)
subroutine changeimp
subroutine checkangs
subroutine checkbonds
subroutine checkimps
subroutine checktors
real(8) function, dimension(3) cross_product (a, b)
subroutine xlink
integer function impcode (taci, tacj, tack, tacl)
subroutine impr_ene (emax, nlarge, av_ene, mode)
subroutine listres
subroutine listseq
subroutine make14list
subroutine makeangles
subroutine make_solute_bonds
subroutine makebonds
integer function makeextrabonds ()
subroutine set_bondcodes
integer function makesomebonds (startres, endres)
subroutine makeexlist
subroutine makehyds
integer function genh (j, residue)
subroutine makeimps
subroutine imp_params
integer function find_atom (ires, atom)
subroutine makeimps_explicit
subroutine maketop
subroutine set_default_mask
subroutine makeconn
subroutine maketors
subroutine prompt (outtxt)
real function randm (seed, seed_only)
subroutine oldreadlib (filnam)
subroutine readlib (file)
subroutine check_overload (resnam)
subroutine oldreadparm (flag)
subroutine readff
subroutine readparm (filnam)
subroutine clearpdb
subroutine cleartop
logical function countpdb (pdb_fileno, atoms, residues, molecules)
subroutine readpdb ()
subroutine readtop
subroutine readx
subroutine readnext
subroutine readframe
subroutine trajectory
subroutine modify_mask
subroutine set_cgp
subroutine set_crg
subroutine set_iac
logical function set_irc_solvent ()
subroutine set_solvent_type
integer function get_atom_from_descriptor (aid)
subroutine define_boundary_condition
logical function set_boundary_condition ()
logical function set_simulation_sphere ()
logical function set_solvent_box ()
subroutine solvate
subroutine solvate_box
subroutine solvate_box_grid
subroutine solvate_box_file
subroutine solvate_sphere
logical function set_solvent_sphere ()
subroutine solvate_sphere_grid
subroutine solvate_sphere_file (shift)
subroutine solvate_restart
subroutine add_solvent_to_topology (waters_in_sphere, max_waters, make_hydrogens, pack)
subroutine grow_arrays_for_solvent (nmore, atoms_per_molecule)
real function rwat_eff ()
type(TOR_CODES) function torcode (taci, tacj, tack, tacl)
subroutine tors_ene (emax, nlarge, av_ene)
logical function check_residues ()
subroutine writepdb
subroutine writemol2
subroutine writetop
subroutine listprefs
subroutine set
subroutine make_shell2
logical function get_centre_by_mass (centre)
Public Attributes
integer, parameter max_entry = 1000
integer, parameter max_atlib = 500
integer, parameter max_cgplib = 100
integer, parameter max_atcgplib = 100
integer, parameter max_old_atyps = 100
integer, parameter max_extrabnd = 100
integer, parameter max_lib = 1000
integer, parameter max_long = 10000
integer, parameter max_conn = 10
real, target solvent_pack = 2.4
real, target rho_solute = 0.05794
real, target max_xlink = 2.1
character(len=200), target solvent_names = ''
integer, target random_seed_solute = 179857
integer, target random_seed_solvent = 758971
integer, parameter build_rule_torsion = 1
integer nlibres
type(lib_entry_type),
*
dimension(max_entry), target lib
logical have_prm_file_name = .false.
logical have_solute_sphere = .false.
logical have_title = .false.
logical have_solvent_boundary = .false.
logical boundary_set = .false.
integer nbnd_prm
integer nbnd_types
type(bond_type_type),
*
dimension(:), allocatable bnd_types
type(bond_prm_type), dimension(:),
*
allocatable bnd_prm
type(angle_type_type),
*
dimension(:), allocatable ang_types
type(anglib_type), dimension(:),
*
allocatable ang_prm
integer nang_types
integer nang_prm
type(torsion_type_type),
*
dimension(:), allocatable tor_types
type(torlib_type), dimension(:),
*
allocatable tor_prm
integer ntor_types
integer ntor_prm
type(imp_prm_type), dimension(:),
*
allocatable imp_prm
integer nimp_prm
logical imp_explicit
integer natom
integer nat_wat
integer nwat
character(len=100) coord_source = ''
character(len=80) auto_name = ''
integer, parameter trj_unit = 17
integer trj_frame = 0
character(len=180) trj_filnam
type(mask_type) mask
integer nextrabnd
type(bond_type), dimension(max_extrabnd) extrabnd
logical, dimension(:), allocatable makeh
integer, dimension(:), allocatable nconn
integer, dimension(:,:),
*
allocatable iconn
real(8) pi
real(8) deg2rad
real(8), dimension(:,:,:),
*
allocatable xw
logical, dimension(:), allocatable keep
integer irc_solvent
character(len=4) solvent_name
logical topo_ok = .false.
logical ff_ok = .false.
Private Member Functions
subroutine, private check_alloc (message)
Private Attributes
character(*), parameter, private module_version = '5.04'
character(*), parameter, private module_date = '2005-04-14'
integer, private alloc_status
Detailed Description
Definition at line 6 of file prep.f90.
Member Function/Subroutine Documentation
subroutine prep::add_solvent_to_topology (integer waters_in_sphere, integer max_waters, logical make_hydrogens, real pack)
Definition at line 5488 of file prep.f90.
References grow_arrays_for_solvent().
Referenced by solvate_box_file(), solvate_box_grid(), solvate_restart(), solvate_sphere_file(), and solvate_sphere_grid().
subroutine prep::addbond ()
Definition at line 268 of file prep.f90.
References get_atom_from_descriptor(), parse::get_string_arg(), and misc::upcase().
Referenced by parse_command().
subroutine prep::allocate_for_pdb (integer, intent(in) atoms, integer, intent(in) residues, integer, intent(in) molecules)
Definition at line 222 of file prep.f90.
Referenced by prep_startup(), and readpdb().
subroutine prep::angle_ene (real emax, integer nlarge, real av_ene)
Definition at line 348 of file prep.f90.
References calc_chemscore::angle().
Referenced by checkangs().
integer function prep::anglecode (character(*), intent(in) taci, character(*), intent(in) tacj, character(*), intent(in) tack)
Definition at line 406 of file prep.f90.
References wildcard_tac().
Referenced by makeangles().
subroutine prep::bond_ene (real emax, integer nlarge, real av_ene)
Definition at line 437 of file prep.f90.
Referenced by checkbonds().
integer function prep::bondcode (character(*), intent(in) taci, character(*), intent(in) tacj)
Definition at line 499 of file prep.f90.
References wildcard_tac().
Referenced by makeextrabonds(), and set_bondcodes().
subroutine prep::changeimp ()
Definition at line 531 of file prep.f90.
References impr_ene(), and prompt().
Referenced by parse_command().
subroutine, private prep::check_alloc (character(*) message) [private]
Definition at line 255 of file prep.f90.
subroutine prep::check_overload (character(len=80) resnam)
Definition at line 2952 of file prep.f90.
Referenced by readlib().
logical function prep::check_residues ()
Definition at line 5928 of file prep.f90.
Referenced by listres(), maketop(), writemol2(), writepdb(), and xlink().
subroutine prep::checkangs ()
Definition at line 579 of file prep.f90.
References angle_ene(), and parse::get_real_arg().
Referenced by parse_command().
subroutine prep::checkbonds ()
Definition at line 602 of file prep.f90.
References bond_ene(), and parse::get_real_arg().
Referenced by parse_command().
subroutine prep::checkimps ()
Definition at line 625 of file prep.f90.
References parse::get_real_arg(), and impr_ene().
Referenced by parse_command().
subroutine prep::checktors ()
Definition at line 651 of file prep.f90.
References parse::get_real_arg(), and tors_ene().
Referenced by parse_command().
subroutine prep::clearbond ()
Definition at line 341 of file prep.f90.
Referenced by parse_command().
subroutine prep::clearlib ()
Definition at line 248 of file prep.f90.
Referenced by parse_command(), and qprep().
subroutine prep::clearpdb ()
Definition at line 3665 of file prep.f90.
Referenced by prep_startup(), and readpdb().
subroutine prep::cleartop ()
Definition at line 3683 of file prep.f90.
Referenced by parse_command(), and prep_startup().
logical function prep::countpdb (integer pdb_fileno, integer atoms, integer residues, integer molecules)
Definition at line 3693 of file prep.f90.
Referenced by readpdb().
real(8) function, dimension(3) prep::cross_product (real(8), dimension(3) a, real(8), dimension(3) b)
Definition at line 676 of file prep.f90.
Referenced by genh().
subroutine prep::define_boundary_condition ()
Definition at line 4518 of file prep.f90.
References parse::parse_reset(), and set_boundary_condition().
Referenced by parse_command().
integer function prep::find_atom (integer ires, character(len=5) atom)
Definition at line 2039 of file prep.f90.
Referenced by get_atom_from_descriptor(), and makeimps_explicit().
integer function prep::genh (integer, intent(in) j, integer, intent(in) residue)
Definition at line 1712 of file prep.f90.
References calc_chemscore::angle(), cross_product(), and md::randm().
Referenced by makehyds().
integer function prep::get_atom_from_descriptor (character(*), intent(in) aid)
Definition at line 4492 of file prep.f90.
References find_atom().
Referenced by addbond(), set_simulation_sphere(), set_solvent_box(), and set_solvent_sphere().
logical function prep::get_centre_by_mass (real(8), dimension(3), intent(out) centre)
Definition at line 6313 of file prep.f90.
References atom_mask::mask_initialize(), maskmanip::maskmanip_make_pretop(), and set_iac().
Referenced by set_simulation_sphere(), set_solvent_box(), and set_solvent_sphere().
subroutine prep::grow_arrays_for_solvent (integer, intent(in) nmore, integer, intent(in) atoms_per_molecule)
Definition at line 5619 of file prep.f90.
References md::check_alloc().
Referenced by add_solvent_to_topology(), and solvate_restart().
subroutine prep::imp_params ()
Definition at line 1990 of file prep.f90.
References impcode().
Referenced by maketop().
integer function prep::impcode (character(keylength) taci, character(keylength) tacj, character(keylength) tack, character(keylength) tacl)
Definition at line 767 of file prep.f90.
References wildcard_tac().
Referenced by imp_params().
subroutine prep::impr_ene (real emax, integer nlarge, real av_ene, integer mode)
Definition at line 1103 of file prep.f90.
Referenced by changeimp(), and checkimps().
subroutine prep::listprefs ()
Definition at line 6247 of file prep.f90.
References prefs::pref_list().
Referenced by parse_command().
subroutine prep::listres ()
Definition at line 1192 of file prep.f90.
References check_residues(), and parse::get_int_arg().
Referenced by parse_command().
subroutine prep::listseq ()
Definition at line 1220 of file prep.f90.
Referenced by parse_command().
subroutine prep::make14list ()
Definition at line 1235 of file prep.f90.
Referenced by maketop().
subroutine prep::make_shell2 ()
Definition at line 6269 of file prep.f90.
References parse::get_real_arg().
subroutine prep::make_solute_bonds ()
Definition at line 1410 of file prep.f90.
References makesomebonds(), and topo::topo_set_max().
Referenced by xlink().
subroutine prep::makeangles ()
Definition at line 1301 of file prep.f90.
References anglecode().
Referenced by maketop().
subroutine prep::makebonds ()
Definition at line 1435 of file prep.f90.
References makeextrabonds(), and makesomebonds().
Referenced by maketop().
subroutine prep::makeconn ()
Definition at line 2287 of file prep.f90.
Referenced by maketop().
subroutine prep::makeexlist ()
Definition at line 1591 of file prep.f90.
Referenced by maketop().
integer function prep::makeextrabonds ()
Definition at line 1463 of file prep.f90.
References bondcode().
Referenced by makebonds().
subroutine prep::makehyds ()
Definition at line 1669 of file prep.f90.
References genh(), calc_rdf::r(), and md::randm().
Referenced by maketop().
subroutine prep::makeimps ()
Definition at line 1966 of file prep.f90.
Referenced by maketop().
subroutine prep::makeimps_explicit ()
Definition at line 2099 of file prep.f90.
References find_atom().
Referenced by maketop().
integer function prep::makesomebonds (integer startres, integer endres)
Definition at line 1539 of file prep.f90.
Referenced by make_solute_bonds(), and makebonds().
subroutine prep::maketop ()
Definition at line 2129 of file prep.f90.
References check_residues(), parse::get_line_arg(), imp_params(), make14list(), makeangles(), makebonds(), makeconn(), makeexlist(), makehyds(), makeimps(), makeimps_explicit(), maketors(), set_bondcodes(), set_cgp(), set_crg(), set_default_mask(), set_iac(), set_solvent_type(), and topo::topo_set_max().
Referenced by parse_command().
subroutine prep::maketors ()
Definition at line 2310 of file prep.f90.
References torcode().
Referenced by maketop().
subroutine prep::modify_mask ()
Definition at line 4229 of file prep.f90.
References parse::get_line_arg(), atom_mask::mask_add(), atom_mask::mask_clear(), and misc::upcase().
Referenced by parse_command().
subroutine prep::oldreadlib (character(*) filnam)
Definition at line 2460 of file prep.f90.
References parse::openit(), and misc::skip_comments().
Referenced by readlib().
subroutine prep::oldreadparm (logical flag)
Definition at line 2970 of file prep.f90.
References md::check_alloc(), indexer::index_add(), indexer::index_create(), and misc::skip_comments().
Referenced by readff(), and readparm().
subroutine prep::prep_shutdown ()
Definition at line 238 of file prep.f90.
References indexer::index_shutdown(), atom_mask::mask_finalize(), topo::topo_deallocate(), and trj::trj_shutdown().
Referenced by shutdown().
subroutine prep::prep_startup ()
Definition at line 194 of file prep.f90.
References allocate_for_pdb(), clearpdb(), cleartop(), indexer::index_startup(), parse::parse_startup(), prefs::pref_add(), prefs::pref_initialize(), prmfile::prmfile_startup(), and topo::topo_startup().
Referenced by startup().
subroutine prep::prompt (character(*) outtxt)
Definition at line 2408 of file prep.f90.
real function prep::randm (integer, intent(in), optional seed, logical, intent(in), optional seed_only)
Definition at line 2422 of file prep.f90.
References calc_rdf::r(), and md::randm().
subroutine prep::readff ()
Definition at line 3150 of file prep.f90.
References parse::get_string_arg(), oldreadparm(), parse::openit(), prmfile::prm_close(), prmfile::prm_open(), and readparm().
Referenced by parse_command().
subroutine prep::readframe ()
Definition at line 4186 of file prep.f90.
References parse::get_int_arg(), readnext(), and trj::trj_seek().
Referenced by parse_command().
subroutine prep::readlib (character(*), optional file)
Definition at line 2607 of file prep.f90.
References check_overload(), parse::get_string_arg(), indexer::index_add(), indexer::index_create(), indexer::index_get(), misc::locase(), oldreadlib(), prmfile::prm_close(), prmfile::prm_count(), prmfile::prm_get_field(), prmfile::prm_get_line(), prmfile::prm_get_logical_by_key(), prmfile::prm_get_next_title(), prmfile::prm_get_real_by_key(), prmfile::prm_get_string_by_key(), prmfile::prm_open(), prmfile::prm_open_section(), and misc::upcase().
Referenced by parse_command(), and readtop().
subroutine prep::readnext ()
Definition at line 4161 of file prep.f90.
References trj::trj_close(), and trj::trj_read().
Referenced by parse_command(), and readframe().
subroutine prep::readparm (character(*) filnam)
Definition at line 3176 of file prep.f90.
References md::check_alloc(), indexer::index_add(), indexer::index_alias(), indexer::index_create(), indexer::index_get(), indexer::index_resize(), oldreadparm(), parse::openit(), prmfile::prm_close(), prmfile::prm_count(), prmfile::prm_get_line(), prmfile::prm_get_logical_by_key(), prmfile::prm_get_real_by_key(), prmfile::prm_get_string_by_key(), prmfile::prm_get_string_string(), prmfile::prm_open_section(), and misc::upcase().
Referenced by readff().
subroutine prep::readpdb ()
Definition at line 3803 of file prep.f90.
References allocate_for_pdb(), clearpdb(), countpdb(), parse::get_string_arg(), parse::openit(), and topo::topo_deallocate().
Referenced by parse_command().
subroutine prep::readtop ()
Definition at line 4051 of file prep.f90.
References parse::get_string_arg(), parse::openit(), readlib(), set_default_mask(), misc::string_part(), and topo::topo_read().
Referenced by parse_command().
subroutine prep::readx ()
Definition at line 4127 of file prep.f90.
References misc::freefile(), parse::get_string_arg(), and parse::openit().
Referenced by parse_command().
real function prep::rwat_eff ()
Definition at line 5702 of file prep.f90.
References md::check_alloc().
Referenced by set_cgp(), and set_solvent_sphere().
subroutine prep::set ()
Definition at line 6253 of file prep.f90.
References parse::get_string_arg(), and prefs::pref_set().
Referenced by md::nbqqlist(), and parse_command().
subroutine prep::set_bondcodes ()
Definition at line 1497 of file prep.f90.
References bondcode().
Referenced by maketop().
logical function prep::set_boundary_condition ()
Definition at line 4528 of file prep.f90.
References parse::get_string_arg(), parse::parse_reset(), set_simulation_sphere(), set_solvent_box(), and misc::upcase().
Referenced by define_boundary_condition().
subroutine prep::set_cgp ()
Definition at line 4257 of file prep.f90.
References rwat_eff().
Referenced by maketop().
subroutine prep::set_crg ()
Definition at line 4359 of file prep.f90.
Referenced by maketop().
subroutine prep::set_default_mask ()
Definition at line 2275 of file prep.f90.
References atom_mask::mask_all(), atom_mask::mask_finalize(), and atom_mask::mask_initialize().
Referenced by maketop(), and readtop().
subroutine prep::set_iac ()
Definition at line 4385 of file prep.f90.
References indexer::index_get().
Referenced by get_centre_by_mass(), and maketop().
logical function prep::set_irc_solvent ()
Definition at line 4428 of file prep.f90.
Referenced by solvate_box_file(), solvate_box_grid(), solvate_restart(), solvate_sphere_file(), and solvate_sphere_grid().
logical function prep::set_simulation_sphere ()
Definition at line 4571 of file prep.f90.
References get_atom_from_descriptor(), get_centre_by_mass(), parse::get_real_arg(), and parse::get_string_arg().
Referenced by set_boundary_condition().
logical function prep::set_solvent_box ()
Definition at line 4630 of file prep.f90.
References get_atom_from_descriptor(), get_centre_by_mass(), parse::get_real_arg(), parse::get_string_arg(), and misc::upcase().
Referenced by set_boundary_condition().
logical function prep::set_solvent_sphere ()
Definition at line 5079 of file prep.f90.
References get_atom_from_descriptor(), get_centre_by_mass(), parse::get_real_arg(), parse::get_string_arg(), rwat_eff(), and misc::upcase().
Referenced by solvate_sphere().
subroutine prep::set_solvent_type ()
Definition at line 4450 of file prep.f90.
References indexer::index_get().
Referenced by maketop().
subroutine prep::solvate ()
Definition at line 4699 of file prep.f90.
References solvate_box(), and solvate_sphere().
Referenced by parse_command().
subroutine prep::solvate_box ()
Definition at line 4717 of file prep.f90.
References parse::get_string_arg(), parse::parse_reset(), solvate_box_file(), solvate_box_grid(), solvate_restart(), and misc::upcase().
Referenced by solvate().
subroutine prep::solvate_box_file ()
Definition at line 4834 of file prep.f90.
References add_solvent_to_topology(), md::check_alloc(), parse::get_string_arg(), parse::parse_reset(), set_irc_solvent(), and misc::upcase().
Referenced by solvate_box().
subroutine prep::solvate_box_grid ()
Definition at line 4751 of file prep.f90.
References add_solvent_to_topology(), md::check_alloc(), parse::get_string_arg(), and set_irc_solvent().
Referenced by solvate_box().
subroutine prep::solvate_restart ()
Definition at line 5428 of file prep.f90.
References add_solvent_to_topology(), misc::freefile(), parse::get_string_arg(), grow_arrays_for_solvent(), parse::parse_reset(), and set_irc_solvent().
Referenced by solvate_box(), and solvate_sphere().
subroutine prep::solvate_sphere ()
Definition at line 5042 of file prep.f90.
References parse::get_string_arg(), parse::parse_reset(), set_solvent_sphere(), solvate_restart(), solvate_sphere_file(), solvate_sphere_grid(), and misc::upcase().
Referenced by solvate().
subroutine prep::solvate_sphere_file (logical, intent(in), optional shift)
Definition at line 5224 of file prep.f90.
References add_solvent_to_topology(), md::check_alloc(), parse::get_string_arg(), parse::parse_reset(), set_irc_solvent(), and misc::upcase().
Referenced by solvate_sphere().
subroutine prep::solvate_sphere_grid ()
Definition at line 5144 of file prep.f90.
References add_solvent_to_topology(), md::check_alloc(), parse::get_string_arg(), and set_irc_solvent().
Referenced by solvate_sphere().
type(TOR_CODES) function prep::torcode (character(keylength) taci, character(keylength) tacj, character(keylength) tack, character(keylength) tacl)
Definition at line 5755 of file prep.f90.
References wildcard_tac().
Referenced by maketors().
subroutine prep::tors_ene (real emax, integer nlarge, real av_ene)
Definition at line 5852 of file prep.f90.
Referenced by checktors().
subroutine prep::trajectory ()
Definition at line 4201 of file prep.f90.
References parse::get_string_arg(), trj::trj_clone_mask(), trj::trj_count(), trj::trj_intersection(), and trj::trj_open().
Referenced by avetr::avetr_calc(), and parse_command().
character(KEYLENGTH) function prep::wildcard_tac (character(*), intent(in) taci)
Definition at line 485 of file prep.f90.
Referenced by anglecode(), bondcode(), impcode(), and torcode().
subroutine prep::writemol2 ()
Definition at line 6067 of file prep.f90.
References check_residues(), misc::freefile(), parse::get_string_arg(), parse::openit(), and parse::parse_reset().
Referenced by parse_command().
subroutine prep::writepdb ()
Definition at line 5957 of file prep.f90.
References check_residues(), parse::get_string_arg(), parse::openit(), and parse::parse_reset().
Referenced by parse_command(), and avetr::write_average().
subroutine prep::writetop ()
Definition at line 6219 of file prep.f90.
References parse::get_string_arg(), parse::parse_reset(), and topo::topo_save().
Referenced by parse_command().
subroutine prep::xlink ()
Definition at line 687 of file prep.f90.
References check_residues(), and make_solute_bonds().
Referenced by parse_command().
Member Data Documentation
integer, private prep::alloc_status [private]
Definition at line 186 of file prep.f90.
type(anglib_type), dimension(:), allocatable prep::ang_prm
Definition at line 123 of file prep.f90.
type(angle_type_type), dimension(:), allocatable prep::ang_types
Definition at line 122 of file prep.f90.
character(len=80) prep::auto_name = ''
Definition at line 153 of file prep.f90.
type(bond_prm_type), dimension(:), allocatable prep::bnd_prm
Definition at line 116 of file prep.f90.
type(bond_type_type), dimension(:), allocatable prep::bnd_types
Definition at line 115 of file prep.f90.
logical prep::boundary_set = .false.
Definition at line 101 of file prep.f90.
integer, parameter prep::build_rule_torsion = 1
Definition at line 72 of file prep.f90.
character(len=100) prep::coord_source = ''
Definition at line 152 of file prep.f90.
real(8) prep::deg2rad
Definition at line 170 of file prep.f90.
type(bond_type), dimension(max_extrabnd) prep::extrabnd
Definition at line 161 of file prep.f90.
logical prep::ff_ok = .false.
Definition at line 183 of file prep.f90.
logical prep::have_prm_file_name = .false.
Definition at line 97 of file prep.f90.
logical prep::have_solute_sphere = .false.
Definition at line 98 of file prep.f90.
logical prep::have_solvent_boundary = .false.
Definition at line 100 of file prep.f90.
logical prep::have_title = .false.
Definition at line 99 of file prep.f90.
integer, dimension(:,:), allocatable prep::iconn
Definition at line 168 of file prep.f90.
logical prep::imp_explicit
Definition at line 148 of file prep.f90.
type(imp_prm_type), dimension(:), allocatable prep::imp_prm
Definition at line 146 of file prep.f90.
integer prep::irc_solvent
Definition at line 176 of file prep.f90.
logical, dimension(:), allocatable prep::keep
Definition at line 174 of file prep.f90.
type(lib_entry_type), dimension(max_entry), target prep::lib
Definition at line 93 of file prep.f90.
logical, dimension(:), allocatable prep::makeh
Definition at line 165 of file prep.f90.
type(mask_type) prep::mask
Definition at line 157 of file prep.f90.
integer, parameter prep::max_atcgplib = 100
Definition at line 27 of file prep.f90.
integer, parameter prep::max_atlib = 500
Definition at line 25 of file prep.f90.
integer, parameter prep::max_cgplib = 100
Definition at line 26 of file prep.f90.
integer, parameter prep::max_conn = 10
Definition at line 39 of file prep.f90.
integer, parameter prep::max_entry = 1000
Definition at line 23 of file prep.f90.
integer, parameter prep::max_extrabnd = 100
Definition at line 33 of file prep.f90.
integer, parameter prep::max_lib = 1000
Definition at line 36 of file prep.f90.
integer, parameter prep::max_long = 10000
Definition at line 37 of file prep.f90.
integer, parameter prep::max_old_atyps = 100
Definition at line 31 of file prep.f90.
real, target prep::max_xlink = 2.1
Definition at line 47 of file prep.f90.
character(*), parameter, private prep::module_date = '2005-04-14' [private]
Definition at line 19 of file prep.f90.
character(*), parameter, private prep::module_version = '5.04' [private]
Definition at line 18 of file prep.f90.
integer prep::nang_prm
Definition at line 125 of file prep.f90.
integer prep::nang_types
Definition at line 124 of file prep.f90.
integer prep::nat_wat
Definition at line 151 of file prep.f90.
integer prep::natom
Definition at line 151 of file prep.f90.
integer prep::nbnd_prm
Definition at line 105 of file prep.f90.
integer prep::nbnd_types
Definition at line 106 of file prep.f90.
integer, dimension(:), allocatable prep::nconn
Definition at line 166 of file prep.f90.
integer prep::nextrabnd
Definition at line 160 of file prep.f90.
integer prep::nimp_prm
Definition at line 147 of file prep.f90.
integer prep::nlibres
Definition at line 92 of file prep.f90.
integer prep::ntor_prm
Definition at line 135 of file prep.f90.
integer prep::ntor_types
Definition at line 134 of file prep.f90.
integer prep::nwat
Definition at line 151 of file prep.f90.
real(8) prep::pi
Definition at line 170 of file prep.f90.
integer, target prep::random_seed_solute = 179857
Definition at line 50 of file prep.f90.
integer, target prep::random_seed_solvent = 758971
Definition at line 51 of file prep.f90.
real, target prep::rho_solute = 0.05794
Definition at line 45 of file prep.f90.
character(len=4) prep::solvent_name
Definition at line 178 of file prep.f90.
character(len=200), target prep::solvent_names = ''
Definition at line 48 of file prep.f90.
real, target prep::solvent_pack = 2.4
Definition at line 43 of file prep.f90.
logical prep::topo_ok = .false.
Definition at line 182 of file prep.f90.
type(torlib_type), dimension(:), allocatable prep::tor_prm
Definition at line 133 of file prep.f90.
type(torsion_type_type), dimension(:), allocatable prep::tor_types
Definition at line 132 of file prep.f90.
character(len=180) prep::trj_filnam
Definition at line 156 of file prep.f90.
integer prep::trj_frame = 0
Definition at line 155 of file prep.f90.
integer, parameter prep::trj_unit = 17
Definition at line 154 of file prep.f90.
real(8), dimension(:,:,:), allocatable prep::xw
Definition at line 172 of file prep.f90.
The documentation for this module was generated from the following file:
prep.f90