calc_xscore Module Reference
Data Types
type atom_data_type
type atom_type_conversion
type bond_pointer
type donor
type heavybond
type patom_name_conversion
type q_atom
type q_bond
type residue_name_conversion
type tabs
type tatom_def
type tatomstruct
type tbond_def
type tbondstruct
type thb_def
type tlogpfactor
type tpmf_def
type tresidue_def
type ttors_def
type twpmf_def
type txatom
type txatom_def
type txbond
type txchain
type txdot
type txdotset
type txff
type txgroup
type txhbond
type txinput
type txligand
type txmolecule
type txprotein
type txresidue
type txring
type txscore
type txtorsion
type txwater
type wat
Public Member Functions
subroutine xscore_initialize
subroutine xscore_finalize
integer function xscore_add (desc)
subroutine xsort_bonds
subroutine xreadatomtypeconversions (filename, chType)
subroutine xreadresidueconversions (filename, chType)
subroutine xpatomnameconversions (filename, chType)
character(len=12) function xtranslateatomtype (othertype)
subroutine xreadlib (filename)
character(len=10) function xtranslatepatomname (atom_res_id, res)
character(len=10) function xtranslateresidue (res)
subroutine xreadinput ()
subroutine xreadinputqatom
subroutine xscore_precalc
subroutine xflag_cofactors
subroutine xextract_cofactor (cf, cf_def, conumber, nAtoms, nBonds, coordinates, bonds)
subroutine xscore_calc (iCalc, iFrame)
subroutine xlog_frame (iFrame, ligand)
subroutine xscore_mean
subroutine xscore_heading (i)
integer function molecule_get_num_heavy_atom (molecule)
subroutine molecule_surdot_clear (molecule)
subroutine molecule_generate_surface_dots (molecule, probe_r)
subroutine molecule_assign_apparent_charge (molecule)
subroutine molecule_show_contents (mol)
subroutine molecule_show_atoms (mol)
subroutine molecule_show_bonds (mol)
subroutine molecule_show_rings (mol)
subroutine molecule_detectconnections (molecule)
integer function molecule_two_bonds_connection_check (bond1, bond2)
integer function molecule_valueatom (molecule, lite_run)
integer function molecule_get_xtool_type (molecule, atom_id, xtype)
type(tXGroup) function molecule_find_a_group (molecule, atom_id)
subroutine molecule_detect_aromatic_rings (molecule)
subroutine molecule_add_ring (m, r)
integer function molecule_aromatic_ring_check_6 (molecule, atom_path, bond_path)
integer function molecule_aromatic_ring_check_5 (molecule, atom_path, bond_path)
subroutine molecule_detect_rings (molecule)
integer function molecule_look_for_a_ring (molecule, bond_id, atom_path, bond_path, required_size)
subroutine molecule_reset_choices (molecule, bond_id, choice)
integer function molecule_get_choices (molecule, choice, wrong_end, current_path_length, current_path)
subroutine molecule_clean_choices (molecule, tried_choice, choice)
integer function molecule_get_num_hb_atom (molecule)
real function molecule_count_rotor (molecule)
integer function molecule_judge_terminal_atom (molecule, atm, partner)
integer function molecule_get_atom_hybridizing_type (molecule, ttype)
real function molecule_calculate_logp (molecule)
real function molecule_count_sulfonic_acid (molecule, flag)
real function molecule_count_salicylic_acid (molecule, flag)
real function molecule_count_amino_acid (molecule, flag)
real function molecule_count_acceptor_1_5_pair (molecule, flag)
real function molecule_count_o3_1_4_pair (molecule, flag)
integer function molecule_adjacent_aromatic_check (molecule, id_in)
real function molecule_count_nar_1_4_pair (molecule, flag)
real function molecule_count_halogen_1_3_pair (molecule, flag)
integer function molecule_adjacent_ring_check (molecule, id_in)
real function molecule_count_internal_hbond (molecule, flag)
real function molecule_count_hydrophobic_carbon (molecule, flag)
integer function molecule_hydrophobic_neighbor_check (molecule, id_in)
integer function molecule_connection_1_2_check (molecule, id1_in, id2_in)
integer function molecule_connection_1_3_check (molecule, id1_in, id2_in)
integer function molecule_connection_1_4_check (molecule, id1_in, id2_in)
integer function molecule_connection_1_5_check (molecule, id1_in, id2_in)
integer function molecule_connection_1_6_check (molecule, id1_in, id2_in)
type(tXGroup) function molecule_find_x_group (molecule, atom_id)
subroutine molecule_get_xlogp_type (molecule, atom_id, ttype)
subroutine ligand_scoring_stats (ligand, iAtom)
real function ligand_calculate_binding_score (ligand, input, protein)
subroutine ligand_sum_hbonds (ligand, protein, num_candidate, candidate)
real function ligand_calculate_rt (ligand, protein)
real function ligand_calculate_hp (ligand, protein)
real function ligand_calculate_hm (ligand, protein)
real function ligand_calculate_hs (ligand, protein)
real function ligand_calculate_vdw (ligand, protein)
real function ligand_calculate_hb (ligand, protein)
integer function ligand_get_hbond_pair_pl (ligand, protein, candidate)
subroutine ligand_value_atom (ligand, lite_run)
subroutine ligand_calculate_hb_root (lig)
subroutine xligand_translate (ligand, nAtoms, nBonds, aQ, aB)
real function ligand_atom_buried_surface (ligand, protein, id_in, total, buried)
subroutine forcefield_read_surface_def (filename)
type(tXDotSet) function forcefield_get_surface_dot (atom, r)
type(tXDotSet) function forcefield_get_surface_dot_rxyz (bigR, x, y, z)
subroutine forcefield_read_residue_def (filename)
subroutine forcefield_read_atom_def (filename)
subroutine forcefield_read_xatom_def (filename)
real function ff_get_atom_logp (ttype)
integer function forcefield_assign_atom_parameters (atm)
subroutine forcefield_translate
integer function forcefield_assign_patom_parameters (atm, suppress_warnings)
integer function forcefield_patom_connection_test (atm1, atm2)
subroutine ring_copy (ring, r)
subroutine bond_swap (b1, b2)
subroutine bond_copy (b1, b2)
real function angle (a, b, c)
integer function hbond_value_hbond_2 (hbond)
subroutine hbond_determine_da_type (hbond)
integer function atom_get_donor_type (atom)
integer function atom_get_acceptor_type (atom)
real function angle_of_two_vectors (v1, v2)
subroutine hbond_clear (hbond)
subroutine dot_pushback (dots, numdot, newdot)
subroutine int_pushback (array, int)
subroutine ring_pushback (ring, atom_id)
subroutine dotset_pushback (dotset, dot)
subroutine dotset_operator_copy (s1, s2)
subroutine hbond_operator_copy (b1, b2)
subroutine atom_operator_copy (a1, a2)
subroutine group_operator_copy (g1, g2)
subroutine dotset_show_contents (dotset)
subroutine taclear (this)
subroutine ring_clear (ring, size)
real function distance (a, b)
subroutine protein_merge_cofactor (protein, cf)
subroutine xprotein_translate (protein, nAtoms, coordinates, num_bond, bond)
subroutine protein_show_contents (protein)
subroutine protein_show_atoms (protein)
subroutine protein_show_rings (mol)
subroutine protein_show_bonds (protein)
subroutine protein_define_pocket (protein, ff, ligand, cutoff)
subroutine protein_add_ring (m, r)
subroutine protein_value_atom (protein, flag, lite_run)
subroutine protein_calculate_hb_root (protein)
subroutine protein_detect_connections (protein, lite_run)
Public Attributes
type(atom_data_type),
*
dimension(:), allocatable atom_data
character *80 top_file
character *80 fep_file
character *80 atom_data_file
character *80 coord_file
integer, dimension(:), allocatable iqatom
integer nhq
integer nhb
integer(ai), dimension(:),
*
allocatable lph_r
integer(ai), dimension(:),
*
allocatable lph_l
type(donor), dimension(:),
*
allocatable hbd_r
type(donor), dimension(:),
*
allocatable hbd_l
integer(ai), dimension(:),
*
allocatable hba_r
integer(ai), dimension(:),
*
allocatable hba_l
integer(ai), dimension(:),
*
allocatable met_r
type(wat), dimension(:),
*
allocatable waters
integer, dimension(:), allocatable pol_con
integer nlph_r
integer nlph_l
integer nhbd_r
integer nhbd_l
integer nhba_r
integer nhba_l
integer nmet_r
integer nwaters
integer nqbonds
integer nhbd_prot
integer nhba_prot
integer nrings
type(txprotein), public protein
type(txligand), public ligand
type(txligand), dimension(:),
*
allocatable, public cofactor
type(txff), public ff
integer, dimension(:), pointer top2prot
integer, parameter, public max_masks = 10
type(mask_type), dimension(max_masks),
*
target, public masks
integer, public nmasks = 0
type(txscore), dimension(:),
*
pointer xscores
integer nxscores
integer maxxscores
integer bdotopcalc
type(txinput) input
character(len=20) chtranslationkey
character(len=80) chinput
character(len=80), dimension(:),
*
allocatable cofactor_def
integer num_cofactor
type(atom_type_conversion),
*
dimension(:), allocatable atomtypetable
integer num_atomtype
type(patom_name_conversion),
*
dimension(:), pointer patomnametable
integer num_patomrestype
type(residue_name_conversion),
*
dimension(:), pointer residuetable
integer num_residue
integer max_bond_neib = 10
integer max_atom_neib = 6
real logp_hydrophobic_carbon = 0.211
real logp_internal_hbond = 0.429
real logp_halogen_pair = 0.137
real logp_nar_pair = 0.485
real logp_o3_pair = -0.268
real logp_acceptor_pair = 0.580
real logp_amino_acid = -2.166
real logp_salicylic_acid = 0.554
real logp_sulfonic_acid = -0.501
type(tlogpfactor), dimension(0:9),
*
public logp_factor
real large = 1.0e+6
real dist_cutoff = 8.00
real water_r = 1.40
real pocket_depth = 4.00
real layer_depth = 3.00
integer, parameter max_atlib = 500
real pi = 3.1416
integer, public err
Private Attributes
type(q_atom), dimension(:),
*
allocatable, target, private q_atoms
type(q_bond), dimension(:),
*
allocatable, target, private q_bonds
type(q_atom), dimension(:),
*
allocatable, target, private ahq
type(q_bond), dimension(:),
*
allocatable, target, private ahb
integer, private warn
Detailed Description
Definition at line 6 of file calc_xscore.f90.
Member Function/Subroutine Documentation
real function calc_xscore::angle (real, dimension(0:2) a, real, dimension(0:2) b, real, dimension(0:2) c)
Definition at line 6689 of file calc_xscore.f90.
References calc_chemscore::angle(), and angle_of_two_vectors().
real function calc_xscore::angle_of_two_vectors (real, dimension(0:2) v1, real, dimension(0:2) v2)
Definition at line 7083 of file calc_xscore.f90.
References calc_chemscore::angle().
Referenced by angle(), and ligand_sum_hbonds().
integer function calc_xscore::atom_get_acceptor_type (type(txatom) atom)
Definition at line 7047 of file calc_xscore.f90.
Referenced by hbond_determine_da_type().
integer function calc_xscore::atom_get_donor_type (type(txatom) atom)
Definition at line 6991 of file calc_xscore.f90.
Referenced by hbond_determine_da_type().
subroutine calc_xscore::atom_operator_copy (type(txatom) a1, type(txatom) a2)
Definition at line 7275 of file calc_xscore.f90.
Referenced by hbond_operator_copy(), and protein_merge_cofactor().
subroutine calc_xscore::bond_copy (type(txbond) b1, type(txbond) b2)
Definition at line 6674 of file calc_xscore.f90.
Referenced by bond_swap().
subroutine calc_xscore::bond_swap (type(txbond) b1, type(txbond) b2)
Definition at line 6665 of file calc_xscore.f90.
References bond_copy().
Referenced by xextract_cofactor().
real function calc_xscore::distance (real, dimension(0:2) a, real, dimension(0:2) b)
Definition at line 7411 of file calc_xscore.f90.
Referenced by hbond_value_hbond_2(), ligand_atom_buried_surface(), ligand_calculate_hm(), ligand_calculate_hp(), ligand_calculate_vdw(), ligand_get_hbond_pair_pl(), molecule_generate_surface_dots(), protein_define_pocket(), protein_detect_connections(), and calc_chemscore::q_contacts().
subroutine calc_xscore::dot_pushback (type(txdot), dimension(:), pointer dots, integer numdot, type(txdot) newdot)
Definition at line 7125 of file calc_xscore.f90.
Referenced by molecule_generate_surface_dots().
subroutine calc_xscore::dotset_operator_copy (type(txdotset) s1, type(txdotset) s2)
Definition at line 7228 of file calc_xscore.f90.
Referenced by forcefield_get_surface_dot_rxyz().
subroutine calc_xscore::dotset_pushback (type(txdotset) dotset, type(txdot) dot)
Definition at line 7202 of file calc_xscore.f90.
Referenced by forcefield_get_surface_dot_rxyz().
subroutine calc_xscore::dotset_show_contents (type(txdotset) dotset)
Definition at line 7332 of file calc_xscore.f90.
real function calc_xscore::ff_get_atom_logp (character(len=20) ttype)
Definition at line 6432 of file calc_xscore.f90.
Referenced by molecule_calculate_logp().
integer function calc_xscore::forcefield_assign_atom_parameters (type(txatom) atm)
Definition at line 6456 of file calc_xscore.f90.
Referenced by molecule_valueatom().
integer function calc_xscore::forcefield_assign_patom_parameters (type(txatom) atm, integer, optional suppress_warnings)
Definition at line 6488 of file calc_xscore.f90.
Referenced by protein_value_atom().
type(tXDotSet) function calc_xscore::forcefield_get_surface_dot (type(txatom) atom, real r)
Definition at line 6111 of file calc_xscore.f90.
References forcefield_get_surface_dot_rxyz(), and calc_rdf::r().
Referenced by molecule_generate_surface_dots().
type(tXDotSet) function calc_xscore::forcefield_get_surface_dot_rxyz (real bigR, real x, real y, real z)
Definition at line 6129 of file calc_xscore.f90.
References dotset_operator_copy(), dotset_pushback(), and calc_rdf::r().
Referenced by forcefield_get_surface_dot().
integer function calc_xscore::forcefield_patom_connection_test (type(txatom) atm1, type(txatom) atm2)
Definition at line 6575 of file calc_xscore.f90.
Referenced by protein_detect_connections().
subroutine calc_xscore::forcefield_read_atom_def (character(len=256) filename)
Definition at line 6312 of file calc_xscore.f90.
References misc::freefile().
Referenced by xscore_precalc().
subroutine calc_xscore::forcefield_read_residue_def (character(len=256) filename)
Definition at line 6217 of file calc_xscore.f90.
References misc::freefile().
Referenced by xscore_precalc().
subroutine calc_xscore::forcefield_read_surface_def (character(len=80) filename)
Definition at line 6037 of file calc_xscore.f90.
References misc::freefile().
Referenced by xscore_precalc().
subroutine calc_xscore::forcefield_read_xatom_def (character(len=256) filename)
Definition at line 6373 of file calc_xscore.f90.
References misc::freefile().
Referenced by xscore_precalc().
subroutine calc_xscore::forcefield_translate ()
Definition at line 6484 of file calc_xscore.f90.
subroutine calc_xscore::group_operator_copy (type(txgroup) g1, type(txgroup) g2)
Definition at line 7312 of file calc_xscore.f90.
subroutine calc_xscore::hbond_clear (type(txhbond) hbond)
Definition at line 7105 of file calc_xscore.f90.
References taclear().
Referenced by ligand_get_hbond_pair_pl().
subroutine calc_xscore::hbond_determine_da_type (type(txhbond) hbond)
Definition at line 6984 of file calc_xscore.f90.
References atom_get_acceptor_type(), and atom_get_donor_type().
Referenced by hbond_value_hbond_2().
subroutine calc_xscore::hbond_operator_copy (type(txhbond) b1, type(txhbond) b2)
Definition at line 7252 of file calc_xscore.f90.
References atom_operator_copy().
Referenced by ligand_sum_hbonds().
integer function calc_xscore::hbond_value_hbond_2 (type(txhbond) hbond)
Definition at line 6861 of file calc_xscore.f90.
References calc_chemscore::angle(), distance(), and hbond_determine_da_type().
Referenced by ligand_get_hbond_pair_pl().
subroutine calc_xscore::int_pushback (integer, dimension(:), pointer array, integer int)
Definition at line 7152 of file calc_xscore.f90.
Referenced by molecule_detect_aromatic_rings(), protein_define_pocket(), and xextract_cofactor().
real function calc_xscore::ligand_atom_buried_surface (type(txligand) ligand, type(txprotein) protein, integer id_in, real total, real buried)
Definition at line 5952 of file calc_xscore.f90.
References distance().
Referenced by ligand_calculate_hs().
real function calc_xscore::ligand_calculate_binding_score (type(txligand) ligand, type(txinput) input, type(txprotein) protein)
Definition at line 5010 of file calc_xscore.f90.
References ligand_calculate_hb(), ligand_calculate_hm(), ligand_calculate_hp(), ligand_calculate_hs(), ligand_calculate_rt(), ligand_calculate_vdw(), molecule_assign_apparent_charge(), molecule_generate_surface_dots(), and molecule_get_num_heavy_atom().
Referenced by xscore_calc(), and xscore_precalc().
real function calc_xscore::ligand_calculate_hb (type(txligand) ligand, type(txprotein) protein)
Definition at line 5619 of file calc_xscore.f90.
References ligand_get_hbond_pair_pl(), and ligand_sum_hbonds().
Referenced by ligand_calculate_binding_score().
subroutine calc_xscore::ligand_calculate_hb_root (type(txligand) lig)
Definition at line 5800 of file calc_xscore.f90.
Referenced by ligand_value_atom().
real function calc_xscore::ligand_calculate_hm (type(txligand) ligand, type(txprotein) protein)
Definition at line 5476 of file calc_xscore.f90.
References distance().
Referenced by ligand_calculate_binding_score().
real function calc_xscore::ligand_calculate_hp (type(txligand) ligand, type(txprotein) protein)
Definition at line 5423 of file calc_xscore.f90.
References distance().
Referenced by ligand_calculate_binding_score().
real function calc_xscore::ligand_calculate_hs (type(txligand) ligand, type(txprotein) protein)
Definition at line 5533 of file calc_xscore.f90.
References ligand_atom_buried_surface().
Referenced by ligand_calculate_binding_score().
real function calc_xscore::ligand_calculate_rt (type(txligand) ligand, type(txprotein) protein)
Definition at line 5298 of file calc_xscore.f90.
References molecule_get_atom_hybridizing_type(), and molecule_judge_terminal_atom().
Referenced by ligand_calculate_binding_score().
real function calc_xscore::ligand_calculate_vdw (type(txligand) ligand, type(txprotein) protein)
Definition at line 5567 of file calc_xscore.f90.
References distance().
Referenced by ligand_calculate_binding_score().
integer function calc_xscore::ligand_get_hbond_pair_pl (type(txligand) ligand, type(txprotein) protein, type(txhbond), dimension(0:999) candidate)
Definition at line 5659 of file calc_xscore.f90.
References distance(), hbond_clear(), and hbond_value_hbond_2().
Referenced by ligand_calculate_hb().
subroutine calc_xscore::ligand_scoring_stats (type(txligand) ligand, integer, optional iAtom)
Definition at line 4962 of file calc_xscore.f90.
Referenced by xscore_calc(), and xscore_precalc().
subroutine calc_xscore::ligand_sum_hbonds (type(txligand) ligand, type(txprotein) protein, integer num_candidate, type(txhbond), dimension(0:999) candidate)
Definition at line 5168 of file calc_xscore.f90.
References calc_chemscore::angle(), angle_of_two_vectors(), hbond_operator_copy(), and molecule_find_a_group().
Referenced by ligand_calculate_hb().
subroutine calc_xscore::ligand_value_atom (type(txligand), intent(inout) ligand, integer, optional lite_run)
Definition at line 5781 of file calc_xscore.f90.
References ligand_calculate_hb_root(), molecule_calculate_logp(), molecule_count_rotor(), molecule_get_num_hb_atom(), and molecule_valueatom().
Referenced by xscore_calc(), and xscore_precalc().
subroutine calc_xscore::molecule_add_ring (type(txmolecule) m, type(txring) r)
Definition at line 2989 of file calc_xscore.f90.
References calc_rdf::r(), ring_clear(), and ring_copy().
Referenced by molecule_detect_aromatic_rings().
integer function calc_xscore::molecule_adjacent_aromatic_check (type(txmolecule) molecule, integer id_in)
Definition at line 3990 of file calc_xscore.f90.
Referenced by molecule_count_o3_1_4_pair(), molecule_count_salicylic_acid(), and molecule_count_sulfonic_acid().
integer function calc_xscore::molecule_adjacent_ring_check (type(txmolecule) molecule, integer id_in)
Definition at line 4116 of file calc_xscore.f90.
Referenced by molecule_count_internal_hbond().
integer function calc_xscore::molecule_aromatic_ring_check_5 (type(txmolecule) molecule, integer, dimension(0:6) atom_path, integer, dimension(0:6) bond_path)
Definition at line 3088 of file calc_xscore.f90.
Referenced by molecule_detect_aromatic_rings().
integer function calc_xscore::molecule_aromatic_ring_check_6 (type(txmolecule) molecule, integer, dimension(:), pointer atom_path, integer, dimension(:), pointer bond_path)
Definition at line 3028 of file calc_xscore.f90.
Referenced by molecule_detect_aromatic_rings().
subroutine calc_xscore::molecule_assign_apparent_charge (type(txmolecule) molecule)
Definition at line 2135 of file calc_xscore.f90.
Referenced by ligand_calculate_binding_score().
real function calc_xscore::molecule_calculate_logp (type(txmolecule) molecule)
Definition at line 3681 of file calc_xscore.f90.
References ff_get_atom_logp(), molecule_count_acceptor_1_5_pair(), molecule_count_amino_acid(), molecule_count_halogen_1_3_pair(), molecule_count_hydrophobic_carbon(), molecule_count_internal_hbond(), molecule_count_nar_1_4_pair(), molecule_count_o3_1_4_pair(), molecule_count_salicylic_acid(), molecule_count_sulfonic_acid(), and molecule_get_xlogp_type().
Referenced by ligand_value_atom().
subroutine calc_xscore::molecule_clean_choices (type(txmolecule) molecule, integer tried_choice, integer, dimension(0:max_bond_neib-1) choice)
Definition at line 3445 of file calc_xscore.f90.
Referenced by molecule_look_for_a_ring().
integer function calc_xscore::molecule_connection_1_2_check (type(txmolecule) molecule, integer id1_in, integer id2_in)
Definition at line 4291 of file calc_xscore.f90.
Referenced by molecule_connection_1_3_check(), molecule_connection_1_4_check(), molecule_connection_1_5_check(), molecule_connection_1_6_check(), molecule_count_nar_1_4_pair(), and molecule_hydrophobic_neighbor_check().
integer function calc_xscore::molecule_connection_1_3_check (type(txmolecule) molecule, integer id1_in, integer id2_in)
Definition at line 4313 of file calc_xscore.f90.
References molecule_connection_1_2_check().
Referenced by molecule_connection_1_4_check(), molecule_connection_1_5_check(), molecule_connection_1_6_check(), molecule_count_amino_acid(), molecule_count_halogen_1_3_pair(), molecule_count_salicylic_acid(), and molecule_hydrophobic_neighbor_check().
integer function calc_xscore::molecule_connection_1_4_check (type(txmolecule) molecule, integer id1_in, integer id2_in)
Definition at line 4345 of file calc_xscore.f90.
References molecule_connection_1_2_check(), and molecule_connection_1_3_check().
Referenced by molecule_connection_1_5_check(), molecule_connection_1_6_check(), molecule_count_amino_acid(), molecule_count_internal_hbond(), molecule_count_nar_1_4_pair(), molecule_count_o3_1_4_pair(), molecule_count_sulfonic_acid(), and molecule_hydrophobic_neighbor_check().
integer function calc_xscore::molecule_connection_1_5_check (type(txmolecule) molecule, integer id1_in, integer id2_in)
Definition at line 4381 of file calc_xscore.f90.
References molecule_connection_1_2_check(), molecule_connection_1_3_check(), and molecule_connection_1_4_check().
Referenced by molecule_connection_1_6_check(), molecule_count_acceptor_1_5_pair(), molecule_count_internal_hbond(), and molecule_count_salicylic_acid().
integer function calc_xscore::molecule_connection_1_6_check (type(txmolecule) molecule, integer id1_in, integer id2_in)
Definition at line 4410 of file calc_xscore.f90.
References molecule_connection_1_2_check(), molecule_connection_1_3_check(), molecule_connection_1_4_check(), and molecule_connection_1_5_check().
Referenced by molecule_count_sulfonic_acid().
real function calc_xscore::molecule_count_acceptor_1_5_pair (type(txmolecule) molecule, integer flag)
Definition at line 3896 of file calc_xscore.f90.
References molecule_connection_1_5_check().
Referenced by molecule_calculate_logp().
real function calc_xscore::molecule_count_amino_acid (type(txmolecule) molecule, integer flag)
Definition at line 3832 of file calc_xscore.f90.
References molecule_connection_1_3_check(), and molecule_connection_1_4_check().
Referenced by molecule_calculate_logp().
real function calc_xscore::molecule_count_halogen_1_3_pair (type(txmolecule) molecule, integer flag)
Definition at line 4062 of file calc_xscore.f90.
References molecule_connection_1_3_check().
Referenced by molecule_calculate_logp().
real function calc_xscore::molecule_count_hydrophobic_carbon (type(txmolecule) molecule, integer flag)
Definition at line 4230 of file calc_xscore.f90.
References molecule_hydrophobic_neighbor_check().
Referenced by molecule_calculate_logp().
real function calc_xscore::molecule_count_internal_hbond (type(txmolecule) molecule, integer flag)
Definition at line 4138 of file calc_xscore.f90.
References molecule_adjacent_ring_check(), molecule_connection_1_4_check(), and molecule_connection_1_5_check().
Referenced by molecule_calculate_logp().
real function calc_xscore::molecule_count_nar_1_4_pair (type(txmolecule) molecule, integer flag)
Definition at line 4012 of file calc_xscore.f90.
References molecule_connection_1_2_check(), and molecule_connection_1_4_check().
Referenced by molecule_calculate_logp().
real function calc_xscore::molecule_count_o3_1_4_pair (type(txmolecule) molecule, integer flag)
Definition at line 3941 of file calc_xscore.f90.
References molecule_adjacent_aromatic_check(), and molecule_connection_1_4_check().
Referenced by molecule_calculate_logp().
real function calc_xscore::molecule_count_rotor (type(txmolecule) molecule)
Definition at line 3482 of file calc_xscore.f90.
References molecule_get_atom_hybridizing_type(), and molecule_judge_terminal_atom().
Referenced by ligand_value_atom().
real function calc_xscore::molecule_count_salicylic_acid (type(txmolecule) molecule, integer flag)
Definition at line 3781 of file calc_xscore.f90.
References molecule_adjacent_aromatic_check(), molecule_connection_1_3_check(), and molecule_connection_1_5_check().
Referenced by molecule_calculate_logp().
real function calc_xscore::molecule_count_sulfonic_acid (type(txmolecule) molecule, integer flag)
Definition at line 3745 of file calc_xscore.f90.
References molecule_adjacent_aromatic_check(), molecule_connection_1_4_check(), and molecule_connection_1_6_check().
Referenced by molecule_calculate_logp().
subroutine calc_xscore::molecule_detect_aromatic_rings (type(txmolecule) molecule)
Definition at line 2868 of file calc_xscore.f90.
References int_pushback(), molecule_add_ring(), molecule_aromatic_ring_check_5(), molecule_aromatic_ring_check_6(), molecule_look_for_a_ring(), and ring_clear().
Referenced by molecule_valueatom().
subroutine calc_xscore::molecule_detect_rings (type(txmolecule), intent(inout) molecule)
Definition at line 3178 of file calc_xscore.f90.
References molecule_look_for_a_ring().
Referenced by molecule_valueatom().
subroutine calc_xscore::molecule_detectconnections (type(txmolecule), intent(inout) molecule)
Definition at line 2263 of file calc_xscore.f90.
References molecule_two_bonds_connection_check().
Referenced by molecule_valueatom().
type(tXGroup) function calc_xscore::molecule_find_a_group (type(txmolecule) molecule, integer atom_id)
Definition at line 2708 of file calc_xscore.f90.
Referenced by ligand_sum_hbonds(), and molecule_get_xtool_type().
type(tXGroup) function calc_xscore::molecule_find_x_group (type(txmolecule) molecule, integer atom_id)
Definition at line 4440 of file calc_xscore.f90.
Referenced by molecule_get_xlogp_type().
subroutine calc_xscore::molecule_generate_surface_dots (type(txmolecule) molecule, real probe_r)
Definition at line 2041 of file calc_xscore.f90.
References distance(), dot_pushback(), forcefield_get_surface_dot(), and molecule_surdot_clear().
Referenced by ligand_calculate_binding_score().
integer function calc_xscore::molecule_get_atom_hybridizing_type (type(txmolecule) molecule, character(len=10) ttype)
Definition at line 3615 of file calc_xscore.f90.
Referenced by ligand_calculate_rt(), molecule_count_rotor(), and molecule_judge_terminal_atom().
integer function calc_xscore::molecule_get_choices (type(txmolecule) molecule, integer, dimension(0:max_bond_neib -1) choice, integer wrong_end, integer current_path_length, integer, dimension(:), pointer current_path)
Definition at line 3398 of file calc_xscore.f90.
Referenced by molecule_look_for_a_ring().
integer function calc_xscore::molecule_get_num_hb_atom (type(txmolecule) molecule)
Definition at line 3463 of file calc_xscore.f90.
Referenced by ligand_value_atom().
integer function calc_xscore::molecule_get_num_heavy_atom (type(txmolecule) molecule)
Definition at line 2020 of file calc_xscore.f90.
Referenced by ligand_calculate_binding_score().
subroutine calc_xscore::molecule_get_xlogp_type (type(txmolecule) molecule, integer atom_id, character(len=20) ttype)
Definition at line 4570 of file calc_xscore.f90.
References molecule_find_x_group().
Referenced by molecule_calculate_logp().
integer function calc_xscore::molecule_get_xtool_type (type(txmolecule) molecule, integer atom_id, character(len=20) xtype)
Definition at line 2547 of file calc_xscore.f90.
References molecule_find_a_group().
Referenced by molecule_valueatom().
integer function calc_xscore::molecule_hydrophobic_neighbor_check (type(txmolecule) molecule, integer id_in)
Definition at line 4252 of file calc_xscore.f90.
References molecule_connection_1_2_check(), molecule_connection_1_3_check(), and molecule_connection_1_4_check().
Referenced by molecule_count_hydrophobic_carbon().
integer function calc_xscore::molecule_judge_terminal_atom (type(txmolecule) molecule, type(txatom) atm, integer partner)
Definition at line 3573 of file calc_xscore.f90.
References molecule_get_atom_hybridizing_type().
Referenced by ligand_calculate_rt(), and molecule_count_rotor().
integer function calc_xscore::molecule_look_for_a_ring (type(txmolecule), intent(inout) molecule, integer bond_id, integer, dimension(:), pointer atom_path, integer, dimension(:), pointer bond_path, integer required_size)
Definition at line 3280 of file calc_xscore.f90.
References molecule_clean_choices(), molecule_get_choices(), molecule_reset_choices(), and molecule_two_bonds_connection_check().
Referenced by molecule_detect_aromatic_rings(), and molecule_detect_rings().
subroutine calc_xscore::molecule_reset_choices (type(txmolecule) molecule, integer bond_id, integer, dimension(0:max_bond_neib -1) choice)
Definition at line 3375 of file calc_xscore.f90.
Referenced by molecule_look_for_a_ring().
subroutine calc_xscore::molecule_show_atoms (type(txmolecule) mol)
Definition at line 2175 of file calc_xscore.f90.
Referenced by molecule_show_contents().
subroutine calc_xscore::molecule_show_bonds (type(txmolecule) mol)
Definition at line 2225 of file calc_xscore.f90.
Referenced by molecule_show_contents().
subroutine calc_xscore::molecule_show_contents (type(txmolecule) mol)
Definition at line 2159 of file calc_xscore.f90.
References molecule_show_atoms(), molecule_show_bonds(), and molecule_show_rings().
Referenced by xscore_precalc().
subroutine calc_xscore::molecule_show_rings (type(txmolecule) mol)
Definition at line 2241 of file calc_xscore.f90.
Referenced by molecule_show_contents().
subroutine calc_xscore::molecule_surdot_clear (type(txmolecule) molecule)
Definition at line 2034 of file calc_xscore.f90.
Referenced by molecule_generate_surface_dots().
integer function calc_xscore::molecule_two_bonds_connection_check (type(txbond) bond1, type(txbond) bond2)
Definition at line 2460 of file calc_xscore.f90.
Referenced by molecule_detectconnections(), and molecule_look_for_a_ring().
integer function calc_xscore::molecule_valueatom (type(txmolecule), intent(inout) molecule, integer, optional lite_run)
Definition at line 2488 of file calc_xscore.f90.
References forcefield_assign_atom_parameters(), molecule_detect_aromatic_rings(), molecule_detect_rings(), molecule_detectconnections(), and molecule_get_xtool_type().
Referenced by ligand_value_atom().
subroutine calc_xscore::protein_add_ring (type(txprotein) m, type(txring) r)
Definition at line 7859 of file calc_xscore.f90.
References calc_rdf::r(), ring_clear(), and ring_copy().
Referenced by protein_define_pocket().
subroutine calc_xscore::protein_calculate_hb_root (type(txprotein) protein)
Definition at line 7925 of file calc_xscore.f90.
Referenced by protein_value_atom().
subroutine calc_xscore::protein_define_pocket (type(txprotein) protein, type(txff) ff, type(txligand) ligand, real cutoff)
Definition at line 7692 of file calc_xscore.f90.
References distance(), int_pushback(), protein_add_ring(), and ring_clear().
Referenced by xscore_calc(), and xscore_precalc().
subroutine calc_xscore::protein_detect_connections (type(txprotein) protein, integer, optional lite_run)
Definition at line 7981 of file calc_xscore.f90.
References distance(), and forcefield_patom_connection_test().
Referenced by protein_value_atom().
subroutine calc_xscore::protein_merge_cofactor (type(txprotein) protein, type(txligand) cf)
Definition at line 7432 of file calc_xscore.f90.
References atom_operator_copy().
Referenced by xscore_precalc().
subroutine calc_xscore::protein_show_atoms (type(txprotein) protein)
Definition at line 7585 of file calc_xscore.f90.
Referenced by protein_show_contents().
subroutine calc_xscore::protein_show_bonds (type(txprotein) protein)
Definition at line 7658 of file calc_xscore.f90.
Referenced by protein_show_contents().
subroutine calc_xscore::protein_show_contents (type(txprotein) protein)
Definition at line 7575 of file calc_xscore.f90.
References protein_show_atoms(), protein_show_bonds(), and protein_show_rings().
Referenced by xscore_precalc().
subroutine calc_xscore::protein_show_rings (type(txprotein) mol)
Definition at line 7639 of file calc_xscore.f90.
Referenced by protein_show_contents().
subroutine calc_xscore::protein_value_atom (type(txprotein), intent(inout) protein, integer flag, integer, optional lite_run)
Definition at line 7901 of file calc_xscore.f90.
References forcefield_assign_patom_parameters(), protein_calculate_hb_root(), and protein_detect_connections().
Referenced by xscore_calc(), and xscore_precalc().
subroutine calc_xscore::ring_clear (type(txring) ring, integer, optional size)
Definition at line 7388 of file calc_xscore.f90.
Referenced by molecule_add_ring(), molecule_detect_aromatic_rings(), protein_add_ring(), protein_define_pocket(), and ring_copy().
subroutine calc_xscore::ring_copy (type(txring) ring, type(txring) r)
Definition at line 6631 of file calc_xscore.f90.
References calc_rdf::r(), and ring_clear().
Referenced by molecule_add_ring(), and protein_add_ring().
subroutine calc_xscore::ring_pushback (type(txring) ring, integer atom_id)
Definition at line 7175 of file calc_xscore.f90.
subroutine calc_xscore::taclear (type(txatom), intent(out) this)
Definition at line 7342 of file calc_xscore.f90.
Referenced by hbond_clear().
subroutine calc_xscore::xextract_cofactor (type(txligand) cf, character(len=80) cf_def, integer conumber, integer nAtoms, integer nBonds, real(8), dimension(:) coordinates, type(bond_type), dimension(:) bonds)
Definition at line 1663 of file calc_xscore.f90.
References bond_swap(), and int_pushback().
Referenced by xscore_precalc().
subroutine calc_xscore::xflag_cofactors ()
Definition at line 1646 of file calc_xscore.f90.
Referenced by xscore_precalc().
subroutine calc_xscore::xligand_translate (type(txligand), intent(out) ligand, integer, intent(in) nAtoms, integer, intent(in) nBonds, type(q_atom), dimension(:), intent(in) aQ, type(q_bond), dimension(:), intent(in) aB)
Definition at line 5851 of file calc_xscore.f90.
Referenced by xscore_precalc().
subroutine calc_xscore::xlog_frame (integer, intent(in) iFrame, type(txligand) ligand)
Definition at line 1948 of file calc_xscore.f90.
Referenced by xscore_calc().
subroutine calc_xscore::xpatomnameconversions (character(len=256) filename, character(len=20) chType)
Definition at line 922 of file calc_xscore.f90.
References misc::freefile(), misc::locase(), and misc::upcase().
Referenced by xscore_precalc().
subroutine calc_xscore::xprotein_translate (type(txprotein) protein, integer nAtoms, real(8), dimension(:) coordinates, integer num_bond, type(bond_type), dimension(:) bond)
Definition at line 7448 of file calc_xscore.f90.
References md::bond().
Referenced by xscore_precalc().
subroutine calc_xscore::xreadatomtypeconversions (character(len=256) filename, character(len=20) chType)
Definition at line 707 of file calc_xscore.f90.
References misc::freefile(), and misc::locase().
Referenced by xscore_precalc().
subroutine calc_xscore::xreadinput ()
Definition at line 1223 of file calc_xscore.f90.
References misc::freefile(), and misc::upcase().
Referenced by xscore_precalc().
subroutine calc_xscore::xreadinputqatom ()
Definition at line 1397 of file calc_xscore.f90.
Referenced by xscore_precalc().
subroutine calc_xscore::xreadlib (character(len=256) filename)
Definition at line 1047 of file calc_xscore.f90.
References misc::freefile().
Referenced by xscore_precalc().
subroutine calc_xscore::xreadresidueconversions (character(len=256) filename, character(len=20) chType)
Definition at line 854 of file calc_xscore.f90.
References misc::freefile(), and misc::locase().
Referenced by xscore_precalc().
integer function calc_xscore::xscore_add (character(*), intent(out) desc)
Definition at line 607 of file calc_xscore.f90.
References misc::getlin(), misc::locase(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), and maskmanip::maskmanip_make().
Referenced by add_a_calc().
subroutine calc_xscore::xscore_calc (integer, intent(in) iCalc, integer, intent(in) iFrame)
Definition at line 1909 of file calc_xscore.f90.
References ligand_calculate_binding_score(), ligand_scoring_stats(), ligand_value_atom(), protein_define_pocket(), protein_value_atom(), and xlog_frame().
Referenced by calc_all().
subroutine calc_xscore::xscore_finalize ()
Definition at line 599 of file calc_xscore.f90.
Referenced by finalize().
subroutine calc_xscore::xscore_heading (integer, intent(in) i)
Definition at line 2005 of file calc_xscore.f90.
Referenced by print_headings().
subroutine calc_xscore::xscore_initialize ()
Definition at line 593 of file calc_xscore.f90.
Referenced by initialize().
subroutine calc_xscore::xscore_mean ()
Definition at line 1974 of file calc_xscore.f90.
Referenced by make_mean_all().
subroutine calc_xscore::xscore_precalc ()
Definition at line 1433 of file calc_xscore.f90.
References forcefield_read_atom_def(), forcefield_read_residue_def(), forcefield_read_surface_def(), forcefield_read_xatom_def(), ligand_calculate_binding_score(), ligand_scoring_stats(), ligand_value_atom(), molecule_show_contents(), protein_define_pocket(), protein_merge_cofactor(), protein_show_contents(), protein_value_atom(), qatom::qatom_load_atoms(), xextract_cofactor(), xflag_cofactors(), xligand_translate(), xpatomnameconversions(), xprotein_translate(), xreadatomtypeconversions(), xreadinput(), xreadinputqatom(), xreadlib(), xreadresidueconversions(), xsort_bonds(), xtranslateatomtype(), xtranslatepatomname(), and xtranslateresidue().
Referenced by do_pre_calcs().
subroutine calc_xscore::xsort_bonds ()
Definition at line 665 of file calc_xscore.f90.
Referenced by xscore_precalc().
character(len=12) function calc_xscore::xtranslateatomtype (character othertype)
Definition at line 1031 of file calc_xscore.f90.
Referenced by xscore_precalc().
character(len=10) function calc_xscore::xtranslatepatomname (integer atom_res_id, character(len=10) res)
Definition at line 1190 of file calc_xscore.f90.
Referenced by xscore_precalc().
character(len=10) function calc_xscore::xtranslateresidue (character(len=8) res)
Definition at line 1208 of file calc_xscore.f90.
Referenced by xscore_precalc().
Member Data Documentation
type(q_bond), dimension(:), allocatable, target, private calc_xscore::ahb [private]
Definition at line 510 of file calc_xscore.f90.
type(q_atom), dimension(:), allocatable, target, private calc_xscore::ahq [private]
Definition at line 509 of file calc_xscore.f90.
type(atom_data_type), dimension(:), allocatable calc_xscore::atom_data
Definition at line 481 of file calc_xscore.f90.
character*80 calc_xscore::atom_data_file
Definition at line 502 of file calc_xscore.f90.
type(atom_type_conversion), dimension(:), allocatable calc_xscore::atomtypetable
Definition at line 557 of file calc_xscore.f90.
integer calc_xscore::bdotopcalc
Definition at line 549 of file calc_xscore.f90.
character(len=80) calc_xscore::chinput
Definition at line 552 of file calc_xscore.f90.
character(len=20) calc_xscore::chtranslationkey
Definition at line 551 of file calc_xscore.f90.
type(txligand), dimension(:), allocatable, public calc_xscore::cofactor
Definition at line 535 of file calc_xscore.f90.
character(len=80), dimension(:), allocatable calc_xscore::cofactor_def
Definition at line 553 of file calc_xscore.f90.
character*80 calc_xscore::coord_file
Definition at line 503 of file calc_xscore.f90.
real calc_xscore::dist_cutoff = 8.00
Definition at line 580 of file calc_xscore.f90.
integer, public calc_xscore::err
Definition at line 588 of file calc_xscore.f90.
character*80 calc_xscore::fep_file
Definition at line 501 of file calc_xscore.f90.
type(txff), public calc_xscore::ff
Definition at line 536 of file calc_xscore.f90.
integer(ai), dimension(:), allocatable calc_xscore::hba_l
Definition at line 520 of file calc_xscore.f90.
integer(ai), dimension(:), allocatable calc_xscore::hba_r
Definition at line 519 of file calc_xscore.f90.
type(donor), dimension(:), allocatable calc_xscore::hbd_l
Definition at line 518 of file calc_xscore.f90.
type(donor), dimension(:), allocatable calc_xscore::hbd_r
Definition at line 517 of file calc_xscore.f90.
type(txinput) calc_xscore::input
Definition at line 550 of file calc_xscore.f90.
integer, dimension(:), allocatable calc_xscore::iqatom
Definition at line 507 of file calc_xscore.f90.
real calc_xscore::large = 1.0e+6
Definition at line 579 of file calc_xscore.f90.
real calc_xscore::layer_depth = 3.00
Definition at line 583 of file calc_xscore.f90.
type(txligand), public calc_xscore::ligand
Definition at line 534 of file calc_xscore.f90.
real calc_xscore::logp_acceptor_pair = 0.580
Definition at line 573 of file calc_xscore.f90.
real calc_xscore::logp_amino_acid = -2.166
Definition at line 574 of file calc_xscore.f90.
type(tlogpfactor), dimension(0:9), public calc_xscore::logp_factor
Definition at line 577 of file calc_xscore.f90.
real calc_xscore::logp_halogen_pair = 0.137
Definition at line 570 of file calc_xscore.f90.
real calc_xscore::logp_hydrophobic_carbon = 0.211
Definition at line 568 of file calc_xscore.f90.
real calc_xscore::logp_internal_hbond = 0.429
Definition at line 569 of file calc_xscore.f90.
real calc_xscore::logp_nar_pair = 0.485
Definition at line 571 of file calc_xscore.f90.
real calc_xscore::logp_o3_pair = -0.268
Definition at line 572 of file calc_xscore.f90.
real calc_xscore::logp_salicylic_acid = 0.554
Definition at line 575 of file calc_xscore.f90.
real calc_xscore::logp_sulfonic_acid = -0.501
Definition at line 576 of file calc_xscore.f90.
integer(ai), dimension(:), allocatable calc_xscore::lph_l
Definition at line 516 of file calc_xscore.f90.
integer(ai), dimension(:), allocatable calc_xscore::lph_r
Definition at line 515 of file calc_xscore.f90.
type(mask_type), dimension(max_masks), target, public calc_xscore::masks
Definition at line 541 of file calc_xscore.f90.
integer, parameter calc_xscore::max_atlib = 500
Definition at line 585 of file calc_xscore.f90.
integer calc_xscore::max_atom_neib = 6
Definition at line 566 of file calc_xscore.f90.
integer calc_xscore::max_bond_neib = 10
Definition at line 565 of file calc_xscore.f90.
integer, parameter, public calc_xscore::max_masks = 10
Definition at line 540 of file calc_xscore.f90.
integer calc_xscore::maxxscores
Definition at line 546 of file calc_xscore.f90.
integer(ai), dimension(:), allocatable calc_xscore::met_r
Definition at line 521 of file calc_xscore.f90.
integer calc_xscore::nhb
Definition at line 513 of file calc_xscore.f90.
integer calc_xscore::nhba_l
Definition at line 528 of file calc_xscore.f90.
integer calc_xscore::nhba_prot
Definition at line 529 of file calc_xscore.f90.
integer calc_xscore::nhba_r
Definition at line 528 of file calc_xscore.f90.
integer calc_xscore::nhbd_l
Definition at line 527 of file calc_xscore.f90.
integer calc_xscore::nhbd_prot
Definition at line 529 of file calc_xscore.f90.
integer calc_xscore::nhbd_r
Definition at line 527 of file calc_xscore.f90.
integer calc_xscore::nhq
Definition at line 512 of file calc_xscore.f90.
integer calc_xscore::nlph_l
Definition at line 527 of file calc_xscore.f90.
integer calc_xscore::nlph_r
Definition at line 527 of file calc_xscore.f90.
integer, public calc_xscore::nmasks = 0
Definition at line 542 of file calc_xscore.f90.
integer calc_xscore::nmet_r
Definition at line 528 of file calc_xscore.f90.
integer calc_xscore::nqbonds
Definition at line 528 of file calc_xscore.f90.
integer calc_xscore::nrings
Definition at line 530 of file calc_xscore.f90.
integer calc_xscore::num_atomtype
Definition at line 558 of file calc_xscore.f90.
integer calc_xscore::num_cofactor
Definition at line 554 of file calc_xscore.f90.
integer calc_xscore::num_patomrestype
Definition at line 560 of file calc_xscore.f90.
integer calc_xscore::num_residue
Definition at line 562 of file calc_xscore.f90.
integer calc_xscore::nwaters
Definition at line 528 of file calc_xscore.f90.
integer calc_xscore::nxscores
Definition at line 546 of file calc_xscore.f90.
type(patom_name_conversion), dimension(:), pointer calc_xscore::patomnametable
Definition at line 559 of file calc_xscore.f90.
real calc_xscore::pi = 3.1416
Definition at line 586 of file calc_xscore.f90.
real calc_xscore::pocket_depth = 4.00
Definition at line 582 of file calc_xscore.f90.
integer, dimension(:), allocatable calc_xscore::pol_con
Definition at line 524 of file calc_xscore.f90.
type(txprotein), public calc_xscore::protein
Definition at line 533 of file calc_xscore.f90.
type(q_atom), dimension(:), allocatable, target, private calc_xscore::q_atoms [private]
Definition at line 505 of file calc_xscore.f90.
type(q_bond), dimension(:), allocatable, target, private calc_xscore::q_bonds [private]
Definition at line 506 of file calc_xscore.f90.
type(residue_name_conversion), dimension(:), pointer calc_xscore::residuetable
Definition at line 561 of file calc_xscore.f90.
integer, dimension(:), pointer calc_xscore::top2prot
Definition at line 537 of file calc_xscore.f90.
character*80 calc_xscore::top_file
Definition at line 501 of file calc_xscore.f90.
integer, private calc_xscore::warn [private]
Definition at line 589 of file calc_xscore.f90.
real calc_xscore::water_r = 1.40
Definition at line 581 of file calc_xscore.f90.
type(wat), dimension(:), allocatable calc_xscore::waters
Definition at line 522 of file calc_xscore.f90.
type(txscore), dimension(:), pointer calc_xscore::xscores
Definition at line 545 of file calc_xscore.f90.
The documentation for this module was generated from the following file:
calc_xscore.f90