parse Module Reference
Data Types
type substring
Public Member Functions
subroutine parse_startup ()
logical function parse_open_file (filename)
integer function openit (lun, fil, stat, frm, mode)
subroutine split
subroutine getline ()
subroutine get_string_arg (arg, prompt)
subroutine get_line_arg (arg, prompt)
logical function get_string_single_line (arg, prompt)
subroutine parse_reset
integer function get_int_arg (prompt)
real function get_real_arg (prompt)
Public Attributes
integer, parameter max_args = 10
character(200) inbuf
type(substring), dimension(0:max_args) argv
integer argc = 0
integer argp = 1
Private Attributes
character(*), parameter, private module_version = '5.01'
character(*), parameter, private module_date = '2003-06-02'
logical, private read_from_file = .false.
integer, private infile = 0
Detailed Description
Definition at line 6 of file parse.f90.
Member Function/Subroutine Documentation
integer function parse::get_int_arg (character(*), intent(in), optional prompt)
Definition at line 213 of file parse.f90.
References getline(), parse_reset(), and prompt().
Referenced by prep::listres(), calc_nb::nb_qp_add(), calc_rdf::rdf_add(), and prep::readframe().
subroutine parse::get_line_arg (character(*), intent(out) arg, character(*), intent(in), optional prompt)
Definition at line 168 of file parse.f90.
References getline(), parse_reset(), and prompt().
Referenced by prep::maketop(), maskmanip::maskmanip_make_pretop(), and prep::modify_mask().
real function parse::get_real_arg (character(*), intent(in), optional prompt)
Definition at line 238 of file parse.f90.
References getline(), parse_reset(), and prompt().
Referenced by prep::checkangs(), prep::checkbonds(), prep::checkimps(), prep::checktors(), prep::make_shell2(), calc_rdf::rdf_add(), prep::set_simulation_sphere(), prep::set_solvent_box(), and prep::set_solvent_sphere().
subroutine parse::get_string_arg (character(*), intent(out) arg, character(*), intent(in), optional prompt)
Definition at line 152 of file parse.f90.
References getline(), and prompt().
Referenced by prep::addbond(), avetr::avetr_calc(), openit(), qprep_from_commandline(), qprep_from_inputfile(), prep::readff(), prep::readlib(), prep::readpdb(), prep::readtop(), prep::readx(), prep::set(), prep::set_boundary_condition(), prep::set_simulation_sphere(), prep::set_solvent_box(), prep::set_solvent_sphere(), prep::solvate_box(), prep::solvate_box_file(), prep::solvate_box_grid(), prep::solvate_restart(), prep::solvate_sphere(), prep::solvate_sphere_file(), prep::solvate_sphere_grid(), prep::trajectory(), prep::writemol2(), prep::writepdb(), and prep::writetop().
logical function parse::get_string_single_line (character(*), intent(out) arg, character(*), intent(in), optional prompt)
Definition at line 184 of file parse.f90.
References getline(), and prompt().
subroutine parse::getline ()
Definition at line 136 of file parse.f90.
References split().
Referenced by get_int_arg(), get_line_arg(), get_real_arg(), get_string_arg(), and get_string_single_line().
integer function parse::openit (integer lun, character(*) fil, character(*) stat, character(*) frm, character(*) mode)
Definition at line 62 of file parse.f90.
References get_string_arg().
Referenced by prep::oldreadlib(), qfep(), prep::readff(), prep::readparm(), prep::readpdb(), prep::readtop(), prep::readx(), prep::writemol2(), and prep::writepdb().
logical function parse::parse_open_file (character(*) filename)
Definition at line 37 of file parse.f90.
References misc::freefile().
Referenced by qprep_from_inputfile().
subroutine parse::parse_reset ()
Definition at line 206 of file parse.f90.
Referenced by prep::define_boundary_condition(), get_int_arg(), get_line_arg(), get_real_arg(), qprep_from_commandline(), prep::set_boundary_condition(), prep::solvate_box(), prep::solvate_box_file(), prep::solvate_restart(), prep::solvate_sphere(), prep::solvate_sphere_file(), prep::writemol2(), prep::writepdb(), and prep::writetop().
subroutine parse::parse_startup ()
Definition at line 30 of file parse.f90.
Referenced by prep::prep_startup().
subroutine parse::split ()
Definition at line 92 of file parse.f90.
Referenced by prmfile::get_strings(), getline(), and prmfile::split().
Member Data Documentation
integer parse::argc = 0
Definition at line 22 of file parse.f90.
integer parse::argp = 1
Definition at line 22 of file parse.f90.
type(substring), dimension(0:max_args) parse::argv
Definition at line 21 of file parse.f90.
character(200) parse::inbuf
Definition at line 20 of file parse.f90.
integer, private parse::infile = 0 [private]
Definition at line 25 of file parse.f90.
integer, parameter parse::max_args = 10
Definition at line 14 of file parse.f90.
character(*), parameter, private parse::module_date = '2003-06-02' [private]
Definition at line 12 of file parse.f90.
character(*), parameter, private parse::module_version = '5.01' [private]
Definition at line 11 of file parse.f90.
logical, private parse::read_from_file = .false. [private]
Definition at line 24 of file parse.f90.
The documentation for this module was generated from the following file:
parse.f90