maskmanip Module Reference
Public Member Functions
integer function maskmanip_make (mask)
subroutine maskmanip_help
integer function maskmanip_make_pretop (mask)
subroutine maskmanip_help_pretop
Detailed Description
Definition at line 8 of file maskmanip.f90.
Member Function/Subroutine Documentation
subroutine maskmanip::maskmanip_help ()
Definition at line 49 of file maskmanip.f90.
References misc::centered_heading().
Referenced by maskmanip_make().
subroutine maskmanip::maskmanip_help_pretop ()
Definition at line 105 of file maskmanip.f90.
References misc::centered_heading().
Referenced by maskmanip_make_pretop().
integer function maskmanip::maskmanip_make (type(mask_type) mask)
Definition at line 18 of file maskmanip.f90.
References misc::getlin(), atom_mask::mask_add(), atom_mask::mask_clear(), maskmanip_help(), and misc::upcase().
Referenced by calc_com::com_add(), calc_com_ke::com_ke_add(), calc_entropy::entropy_add(), calc_fit::fit_add(), calc_nb::nb_add(), calc_nb::nb_qp_add(), calc_pmf::pmf_add(), calc_rdf::rdf_add(), calc_rms::rms_add(), calc_rmsf::rmsf_add(), calc_chemscore::score_add(), and calc_xscore::xscore_add().
integer function maskmanip::maskmanip_make_pretop (type(mask_type) mask)
Definition at line 73 of file maskmanip.f90.
References parse::get_line_arg(), atom_mask::mask_add(), atom_mask::mask_clear(), maskmanip_help_pretop(), and misc::upcase().
Referenced by prep::get_centre_by_mass().
The documentation for this module was generated from the following file:
maskmanip.f90