calc_rms Module Reference
Data Types
type rms_coord_type
Public Member Functions
subroutine rms_initialize
subroutine rms_finalize (i)
integer function rms_add (desc)
subroutine rms_calc (i)
subroutine rms_make_ref (i)
subroutine rms_heading (i)
Public Attributes
integer, parameter max_masks = 10
Private Attributes
type(mask_type), dimension(max_masks),
*
target, private masks
integer, private nmasks = 0
type(rms_coord_type),
*
dimension(max_masks), private coords
Detailed Description
Definition at line 6 of file calc_rms.f90.
Member Function/Subroutine Documentation
integer function calc_rms::rms_add (character(*) desc)
Definition at line 31 of file calc_rms.f90.
References atom_mask::mask_finalize(), atom_mask::mask_initialize(), maskmanip::maskmanip_make(), and rms_make_ref().
Referenced by add_a_calc().
subroutine calc_rms::rms_calc (integer, intent(in) i)
Definition at line 61 of file calc_rms.f90.
References atom_mask::mask_get(), and calc_rdf::r().
Referenced by calc_all().
subroutine calc_rms::rms_finalize (integer i)
Definition at line 25 of file calc_rms.f90.
References atom_mask::mask_finalize().
Referenced by finalize().
subroutine calc_rms::rms_heading (integer i)
Definition at line 86 of file calc_rms.f90.
Referenced by print_headings().
subroutine calc_rms::rms_initialize ()
Definition at line 22 of file calc_rms.f90.
Referenced by initialize().
subroutine calc_rms::rms_make_ref (integer i)
Definition at line 78 of file calc_rms.f90.
References atom_mask::mask_get().
Referenced by make_ref_all(), and rms_add().
Member Data Documentation
type(rms_coord_type), dimension(max_masks), private calc_rms::coords [private]
Definition at line 19 of file calc_rms.f90.
type(mask_type), dimension(max_masks), target, private calc_rms::masks [private]
Definition at line 14 of file calc_rms.f90.
integer, parameter calc_rms::max_masks = 10
Definition at line 12 of file calc_rms.f90.
integer, private calc_rms::nmasks = 0 [private]
Definition at line 15 of file calc_rms.f90.
The documentation for this module was generated from the following file:
calc_rms.f90