qatom Module Reference
Data Types
type monitor_atom_group_type
type monitor_group_pair_type
type qangle_type
type qbond_type
type qbondlib_type
type qq_el_scale_type
type specex_type
Public Member Functions
subroutine qatom_startup
subroutine qatom_shutdown
logical function qatom_old_load_atoms (fep_file)
logical function qatom_load_atoms (fep_file)
logical function qatom_old_load_fep ()
logical function qatom_load_fep (fep_file)
logical function bond_harmonic_in_any_state (k)
Public Attributes
integer, parameter max_states = 10
integer, parameter max_qat = 100
integer, parameter max_link = 10
integer nstates
integer nqat
integer qswitch
integer offset
logical qvdw_flag
logical qq_use_library_charges
integer(ai), dimension(:),
*
allocatable iqseq
integer, dimension(:,:),
*
allocatable qiac
character(len=keylength),
*
dimension(:), allocatable qtac
integer nqexpnb
integer(ai), dimension(:),
*
allocatable iqexpnb
integer(ai), dimension(:),
*
allocatable jqexpnb
integer nqlib
real(4), dimension(:,:),
*
allocatable qcrg
real(8), dimension(:), allocatable qmass
real(8), dimension(:,:),
*
allocatable qavdw
real(8), dimension(:,:),
*
allocatable qbvdw
integer nqbond
type(qbond_type), dimension(:),
*
allocatable qbnd
type(qbondlib_type), dimension(:),
*
allocatable qbondlib
integer nqangle
type(qangle_type), dimension(:),
*
allocatable qang
type(anglib_type), dimension(:),
*
allocatable qanglib
integer nqtor
integer(ai), dimension(:),
*
allocatable iqtor
integer(ai), dimension(:),
*
allocatable jqtor
integer(ai), dimension(:),
*
allocatable kqtor
integer(ai), dimension(:),
*
allocatable lqtor
integer(tiny), dimension(:,:),
*
allocatable qtorcod
real(8), dimension(:), allocatable qfktor
real(8), dimension(:), allocatable qrmult
real(8), dimension(:), allocatable qdeltor
integer nqimp
integer(ai), dimension(:),
*
allocatable iqimp
integer(ai), dimension(:),
*
allocatable jqimp
integer(ai), dimension(:),
*
allocatable kqimp
integer(ai), dimension(:),
*
allocatable lqimp
integer(tiny), dimension(:,:),
*
allocatable qimpcod
real(8), dimension(:), allocatable qfkimp
real(8), dimension(:), allocatable qimp0
integer nang_coupl
integer ntor_coupl
integer nimp_coupl
integer(ai), dimension(3, max_qat) iang_coupl
integer(ai), dimension(3, max_qat) itor_coupl
integer(ai), dimension(3, max_qat) iimp_coupl
integer nqshake
integer(ai), dimension(max_qat) iqshake
integer(ai), dimension(max_qat) jqshake
real(8), dimension(max_qat,
*
max_states) qshake_dist
integer noffd
type(offdiag_save), dimension(:),
*
allocatable offd
type(offdiag_aux), dimension(:),
*
allocatable offd2
integer nexspec
type(specex_type), dimension(:),
*
allocatable exspec
type(monitor_group_pair_type),
*
dimension(:), allocatable monitor_group_pair
type(monitor_atom_group_type),
*
dimension(:), allocatable monitor_atom_group
integer, parameter max_atoms_in_special_group =30
integer monitor_group_pairs
integer monitor_groups
type(qq_el_scale_type),
*
dimension(:), allocatable qq_el_scale
integer nel_scale
integer tmpindex
integer numsoftlines
integer i2
real(8), dimension(:,:,:),
*
allocatable sc_lookup
real(8), dimension(:,:),
*
allocatable alpha_max
real(8) sc_aq
real(8) sc_bq
real(8) sc_aj
real(8) sc_bj
real(8) alpha_max_tmp
logical softcore_use_max_potential
type(q_energies), dimension(:),
*
allocatable eq
real(8), dimension(max_states,
*
max_states) hij
real(8), dimension(max_qat) emorsed
real(8), dimension(3, max_qat) dmorse_i
real(8), dimension(3, max_qat) dmorse_j
logical use_new_fep_format
Private Attributes
character(*), parameter, private module_name = 'Q-atom'
character(*), parameter, private module_version = '5.01'
character(*), parameter, private module_date = '2003-06-02'
real(8), private pi
real(8), private deg2rad
Detailed Description
Definition at line 6 of file qatom.f90.
Member Function/Subroutine Documentation
logical function qatom::bond_harmonic_in_any_state (integer, intent(in) k)
Definition at line 1724 of file qatom.f90.
Referenced by qatom_load_fep().
logical function qatom::qatom_load_atoms (character(*), intent(in) fep_file)
Definition at line 232 of file qatom.f90.
References misc::centered_heading(), prmfile::prm_close(), prmfile::prm_count(), prmfile::prm_get_int_int(), prmfile::prm_get_integer_by_key(), prmfile::prm_get_line(), prmfile::prm_get_logical_by_key(), prmfile::prm_get_string_by_key(), prmfile::prm_get_string_int(), prmfile::prm_get_string_string(), prmfile::prm_max_enum(), prmfile::prm_max_enum2(), prmfile::prm_open_section(), qatom_old_load_atoms(), and misc::upcase().
Referenced by md::get_fep(), calc_pmf::pmf_precalc(), calc_chemscore::start(), and calc_xscore::xscore_precalc().
logical function qatom::qatom_load_fep (character(*), intent(in) fep_file)
Definition at line 853 of file qatom.f90.
References bond_harmonic_in_any_state(), misc::centered_heading(), indexer::index_add(), indexer::index_create(), indexer::index_get(), prmfile::prm_close(), prmfile::prm_count(), prmfile::prm_get_field(), prmfile::prm_get_int_int(), prmfile::prm_get_integer_by_key(), prmfile::prm_get_line(), prmfile::prm_max_enum(), prmfile::prm_open(), prmfile::prm_open_section(), and qatom_old_load_fep().
Referenced by md::get_fep().
logical function qatom::qatom_old_load_atoms (character(*), intent(in) fep_file)
Definition at line 200 of file qatom.f90.
References misc::centered_heading().
Referenced by qatom_load_atoms().
logical function qatom::qatom_old_load_fep ()
Definition at line 528 of file qatom.f90.
References misc::centered_heading().
Referenced by qatom_load_fep().
subroutine qatom::qatom_shutdown ()
Definition at line 180 of file qatom.f90.
Referenced by md::md_shutdown().
subroutine qatom::qatom_startup ()
Definition at line 166 of file qatom.f90.
References nrgy::nrgy_startup(), and prmfile::prmfile_startup().
Referenced by md::md_startup().
Member Data Documentation
real(8), dimension(:,:), allocatable qatom::alpha_max
Definition at line 146 of file qatom.f90.
real(8) qatom::alpha_max_tmp
Definition at line 147 of file qatom.f90.
real(8), private qatom::deg2rad [private]
Definition at line 23 of file qatom.f90.
real(8), dimension(3,max_qat) qatom::dmorse_i
Definition at line 156 of file qatom.f90.
real(8), dimension(3,max_qat) qatom::dmorse_j
Definition at line 157 of file qatom.f90.
real(8), dimension(max_qat) qatom::emorsed
Definition at line 155 of file qatom.f90.
type(q_energies), dimension(:), allocatable qatom::eq
Definition at line 153 of file qatom.f90.
type(specex_type), dimension(:), allocatable qatom::exspec
Definition at line 110 of file qatom.f90.
real(8), dimension(max_states,max_states) qatom::hij
Definition at line 154 of file qatom.f90.
integer qatom::i2
Definition at line 145 of file qatom.f90.
integer(ai), dimension(3,max_qat) qatom::iang_coupl
Definition at line 93 of file qatom.f90.
integer(ai), dimension(3,max_qat) qatom::iimp_coupl
Definition at line 95 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::iqexpnb
Definition at line 47 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::iqimp
Definition at line 88 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::iqseq
Definition at line 43 of file qatom.f90.
integer(ai), dimension(max_qat) qatom::iqshake
Definition at line 98 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::iqtor
Definition at line 83 of file qatom.f90.
integer(ai), dimension(3,max_qat) qatom::itor_coupl
Definition at line 94 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::jqexpnb
Definition at line 47 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::jqimp
Definition at line 88 of file qatom.f90.
integer(ai), dimension(max_qat) qatom::jqshake
Definition at line 98 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::jqtor
Definition at line 83 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::kqimp
Definition at line 88 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::kqtor
Definition at line 83 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::lqimp
Definition at line 88 of file qatom.f90.
integer(ai), dimension(:), allocatable qatom::lqtor
Definition at line 83 of file qatom.f90.
integer, parameter qatom::max_atoms_in_special_group =30
Definition at line 131 of file qatom.f90.
integer, parameter qatom::max_link = 10
Definition at line 31 of file qatom.f90.
integer, parameter qatom::max_qat = 100
Definition at line 30 of file qatom.f90.
integer, parameter qatom::max_states = 10
Definition at line 29 of file qatom.f90.
character(*), parameter, private qatom::module_date = '2003-06-02' [private]
Definition at line 20 of file qatom.f90.
character(*), parameter, private qatom::module_name = 'Q-atom' [private]
Definition at line 18 of file qatom.f90.
character(*), parameter, private qatom::module_version = '5.01' [private]
Definition at line 19 of file qatom.f90.
type (monitor_atom_group_type), dimension(:), allocatable qatom::monitor_atom_group
Definition at line 126 of file qatom.f90.
type(monitor_group_pair_type), dimension(:), allocatable qatom::monitor_group_pair
Definition at line 119 of file qatom.f90.
integer qatom::monitor_group_pairs
Definition at line 133 of file qatom.f90.
integer qatom::monitor_groups
Definition at line 133 of file qatom.f90.
integer qatom::nang_coupl
Definition at line 92 of file qatom.f90.
integer qatom::nel_scale
Definition at line 143 of file qatom.f90.
integer qatom::nexspec
Definition at line 105 of file qatom.f90.
integer qatom::nimp_coupl
Definition at line 92 of file qatom.f90.
integer qatom::noffd
Definition at line 101 of file qatom.f90.
integer qatom::nqangle
Definition at line 77 of file qatom.f90.
integer qatom::nqat
Definition at line 33 of file qatom.f90.
integer qatom::nqbond
Definition at line 54 of file qatom.f90.
integer qatom::nqexpnb
Definition at line 46 of file qatom.f90.
integer qatom::nqimp
Definition at line 87 of file qatom.f90.
integer qatom::nqlib
Definition at line 49 of file qatom.f90.
integer qatom::nqshake
Definition at line 97 of file qatom.f90.
integer qatom::nqtor
Definition at line 82 of file qatom.f90.
integer qatom::nstates
Definition at line 33 of file qatom.f90.
integer qatom::ntor_coupl
Definition at line 92 of file qatom.f90.
integer qatom::numsoftlines
Definition at line 145 of file qatom.f90.
type(offdiag_save), dimension(:), allocatable qatom::offd
Definition at line 102 of file qatom.f90.
type(offdiag_aux), dimension(:), allocatable qatom::offd2
Definition at line 103 of file qatom.f90.
integer qatom::offset
Definition at line 40 of file qatom.f90.
real(8), private qatom::pi [private]
Definition at line 23 of file qatom.f90.
type(qangle_type), dimension(:), allocatable qatom::qang
Definition at line 79 of file qatom.f90.
type(anglib_type), dimension(:), allocatable qatom::qanglib
Definition at line 80 of file qatom.f90.
real(8), dimension(:,:), allocatable qatom::qavdw
Definition at line 52 of file qatom.f90.
type(qbond_type), dimension(:), allocatable qatom::qbnd
Definition at line 68 of file qatom.f90.
type(qbondlib_type), dimension(:), allocatable qatom::qbondlib
Definition at line 69 of file qatom.f90.
real(8), dimension(:,:), allocatable qatom::qbvdw
Definition at line 52 of file qatom.f90.
real(4), dimension(:,:), allocatable qatom::qcrg
Definition at line 50 of file qatom.f90.
real(8), dimension(:), allocatable qatom::qdeltor
Definition at line 85 of file qatom.f90.
real(8), dimension(:), allocatable qatom::qfkimp
Definition at line 90 of file qatom.f90.
real(8), dimension(:), allocatable qatom::qfktor
Definition at line 85 of file qatom.f90.
integer, dimension(:,:), allocatable qatom::qiac
Definition at line 44 of file qatom.f90.
real(8), dimension(:), allocatable qatom::qimp0
Definition at line 90 of file qatom.f90.
integer(tiny), dimension(:,:), allocatable qatom::qimpcod
Definition at line 89 of file qatom.f90.
real(8), dimension(:), allocatable qatom::qmass
Definition at line 51 of file qatom.f90.
type(qq_el_scale_type), dimension(:), allocatable qatom::qq_el_scale
Definition at line 141 of file qatom.f90.
logical qatom::qq_use_library_charges
Definition at line 42 of file qatom.f90.
real(8), dimension(:), allocatable qatom::qrmult
Definition at line 85 of file qatom.f90.
real(8), dimension(max_qat,max_states) qatom::qshake_dist
Definition at line 99 of file qatom.f90.
integer qatom::qswitch
Definition at line 38 of file qatom.f90.
character(len=keylength), dimension(:), allocatable qatom::qtac
Definition at line 45 of file qatom.f90.
integer(tiny), dimension(:,:), allocatable qatom::qtorcod
Definition at line 84 of file qatom.f90.
logical qatom::qvdw_flag
Definition at line 41 of file qatom.f90.
real(8) qatom::sc_aj
Definition at line 147 of file qatom.f90.
real(8) qatom::sc_aq
Definition at line 147 of file qatom.f90.
real(8) qatom::sc_bj
Definition at line 147 of file qatom.f90.
real(8) qatom::sc_bq
Definition at line 147 of file qatom.f90.
real(8), dimension(:,:,:), allocatable qatom::sc_lookup
Definition at line 146 of file qatom.f90.
logical qatom::softcore_use_max_potential
Definition at line 148 of file qatom.f90.
integer qatom::tmpindex
Definition at line 145 of file qatom.f90.
logical qatom::use_new_fep_format
Definition at line 160 of file qatom.f90.
The documentation for this module was generated from the following file:
qatom.f90