prefs Module Reference
Data Types
type pref
Public Member Functions
subroutine pref_initialize (max)
logical function pref_add (name, ival, rval, sval)
subroutine pref_list (heading)
logical function pref_set (string, inval)
Public Attributes
integer, parameter pref_len =200
Private Member Functions
integer function, private lookup (name)
Private Attributes
character(*), parameter, private module_version = '5.01'
character(*), parameter, private module_date = '2003-06-02'
integer, private max_prefs
integer, private nprefs
integer, parameter, private default_max = 20
character(len=2), private separator
type(pref), dimension(:),
*
allocatable, private p
Detailed Description
Definition at line 6 of file prefs.f90.
Member Function/Subroutine Documentation
integer function, private prefs::lookup (character(*), intent(in) name) [private]
Definition at line 157 of file prefs.f90.
Referenced by pref_set().
logical function prefs::pref_add (character(*), target name, integer, optional, target ival, real, optional, target rval, character(*), optional, target sval)
Definition at line 54 of file prefs.f90.
Referenced by prep::prep_startup().
subroutine prefs::pref_initialize (integer, optional max)
Definition at line 34 of file prefs.f90.
Referenced by prep::prep_startup().
subroutine prefs::pref_list (character(*), optional heading)
Definition at line 84 of file prefs.f90.
Referenced by prep::listprefs().
logical function prefs::pref_set (character(*), intent(in) string, character(*), intent(in), optional inval)
Definition at line 109 of file prefs.f90.
References lookup().
Referenced by prep::set().
Member Data Documentation
integer, parameter, private prefs::default_max = 20 [private]
Definition at line 15 of file prefs.f90.
integer, private prefs::max_prefs [private]
Definition at line 14 of file prefs.f90.
character(*), parameter, private prefs::module_date = '2003-06-02' [private]
Definition at line 12 of file prefs.f90.
character(*), parameter, private prefs::module_version = '5.01' [private]
Definition at line 11 of file prefs.f90.
integer, private prefs::nprefs [private]
Definition at line 14 of file prefs.f90.
type(pref), dimension(:), allocatable, private prefs::p [private]
Definition at line 27 of file prefs.f90.
integer, parameter prefs::pref_len =200
Definition at line 16 of file prefs.f90.
character(len=2), private prefs::separator [private]
Definition at line 17 of file prefs.f90.
The documentation for this module was generated from the following file:
prefs.f90