avetr Module Reference
Public Member Functions
subroutine avetr_calc
subroutine add_coordinates
subroutine average
subroutine write_average
Public Attributes
integer, parameter ave_pdb = 11
Private Attributes
integer(4), private ncoords
integer(4), private n_sets = 0
real(4), dimension(:),
*
allocatable, private x_in
real(4), dimension(:),
*
allocatable, private x_sum
real(4), dimension(:),
*
allocatable, private x2_sum
real(8), private rmsd
Detailed Description
Definition at line 6 of file avetr.f90.
Member Function/Subroutine Documentation
subroutine avetr::add_coordinates ()
Definition at line 60 of file avetr.f90.
Referenced by avetr_calc().
subroutine avetr::average ()
Definition at line 69 of file avetr.f90.
Referenced by avetr_calc().
subroutine avetr::avetr_calc ()
Definition at line 20 of file avetr.f90.
References add_coordinates(), average(), parse::get_string_arg(), prep::trajectory(), trj::trj_get_ncoords(), trj::trj_read_masked(), and write_average().
Referenced by parse_command().
subroutine avetr::write_average ()
Definition at line 80 of file avetr.f90.
References atom_mask::mask_put(), and prep::writepdb().
Referenced by avetr_calc().
Member Data Documentation
integer, parameter avetr::ave_pdb = 11
Definition at line 10 of file avetr.f90.
integer(4), private avetr::n_sets = 0 [private]
Definition at line 11 of file avetr.f90.
integer(4), private avetr::ncoords [private]
Definition at line 11 of file avetr.f90.
real(8), private avetr::rmsd [private]
Definition at line 13 of file avetr.f90.
real(4), dimension(:), allocatable, private avetr::x2_sum [private]
Definition at line 12 of file avetr.f90.
real(4), dimension(:), allocatable, private avetr::x_in [private]
Definition at line 12 of file avetr.f90.
real(4), dimension(:), allocatable, private avetr::x_sum [private]
Definition at line 12 of file avetr.f90.
The documentation for this module was generated from the following file:
avetr.f90