calc_chemscore Module Reference
Data Types
type atom_data_type
type bond_pointer
type donor
type lipos
type q_atom
type q_bond
type score_coord_type
type score_precalc_type
type score_type
type wat
Public Member Functions
subroutine score_initialize
subroutine chemscore_finalize
subroutine log_frame (iFrame)
subroutine score_heading (i)
subroutine calc_hbonds
subroutine calc_lipo
subroutine calc_metals
subroutine calc_rot
subroutine calc_scores
subroutine count_qlipo
recursive function lip_atom (atom)
subroutine frozen
recursive function find_contact (atom)
subroutine get_atom_data
subroutine make_tac_index
subroutine q_contacts
subroutine q_types
subroutine report_ligand
subroutine report_protein
subroutine report_rings
subroutine reset_waters
subroutine score_waters
subroutine set_ligand
subroutine set_rings
recursive subroutine search_ring (bond, ir)
subroutine mark_ring (bond, ir)
recursive function trace_ring (atom, ir)
subroutine set_rotatable
subroutine set_waters
subroutine sort_atoms
subroutine sort_bonds
subroutine sort_waters
subroutine start
subroutine store_waters
real function angle (a, b, c)
real function dist (a, b)
real function distsq (a, b)
real function fr_lip (a, b)
real function fr_met (a, b)
real function g1_hb (a, b)
real function g2_hb (a, b, c)
subroutine score_precalc
integer function score_add (desc)
subroutine score_mean
subroutine score_calc (iCalc, iFrame)
Public Attributes
real score
integer frame
integer stat
integer i
character(len=4) trj_type
character *80 top_file
character *80 fep_file
integer, parameter max_masks = 10
integer nscores
integer maxscores
integer(ai), dimension(:),
*
allocatable lph_r
integer(ai), dimension(:),
*
allocatable lph_l
type(donor), dimension(:),
*
allocatable hbd_r
type(donor), dimension(:),
*
allocatable hbd_l
integer(ai), dimension(:),
*
allocatable hba_r
integer(ai), dimension(:),
*
allocatable hba_l
integer(ai), dimension(:),
*
allocatable met_r
type(wat), dimension(:),
*
allocatable waters
integer, dimension(:), allocatable pol_con
integer nlph_r
integer nlph_l
integer nhbd_r
integer nhbd_l
integer nhba_r
integer nhba_l
integer nmet_r
integer nwaters
integer nqbonds
integer nhbd_prot
integer nhba_prot
integer nrings
integer, parameter lipo =1
integer, parameter metal =2
integer, parameter sulphur =3
integer, parameter acceptor =4
integer, parameter sp3 =5
integer, parameter sp2 =6
integer, parameter sp3_n =7
integer, parameter pl_n =8
integer, parameter hydrogen =9
integer, parameter oxygen =10
integer, parameter carbon_lipo =11
integer, parameter carbonyl_carbon =12
integer, parameter carbonyl_oxygen =13
integer, parameter nprops =13
character *(*), dimension(nprops),
*
parameter file_heading = [ 'lipophilic '
type(atom_data_type),
*
dimension(:), allocatable atom_data
integer, dimension(:), allocatable iqatom
real, dimension(:), allocatable vdwr
character *80 atom_data_file
character *80 coord_file
real hbond_term
real metal_term
real lipo_term
real rot_term
real, parameter dgconst =-5.48
real, parameter dghbond =-3.34
real, parameter dgmetal =-6.03
real, parameter dglipo =-0.117
real, parameter dgrot =2.56
Private Attributes
type(score_precalc_type),
*
dimension(:), pointer, private aprecalc
integer, private iprecalc
integer, private maxprecalc
type(score_type), dimension(:),
*
pointer, private ascore
type(mask_type), dimension(max_masks),
*
target, private masks
integer, private nmasks = 0
type(score_coord_type),
*
dimension(max_masks), private coords
type(q_atom), dimension(:),
*
allocatable, target, private q_atoms
type(q_bond), dimension(:),
*
allocatable, target, private q_bonds
integer, private bdotopcalc
integer, private irestartcalc =-1
logical, private busexin = .false.
integer, private warn
Detailed Description
Definition at line 8 of file calc_chemscore.f90.
Member Function/Subroutine Documentation
real function calc_chemscore::angle (integer a, integer b, integer c)
Definition at line 1205 of file calc_chemscore.f90.
References distsq().
Referenced by calc_xscore::angle(), md::angle(), prep::angle_ene(), calc_xscore::angle_of_two_vectors(), g2_hb(), prep::genh(), calc_xscore::hbond_value_hbond_2(), md::init_shake(), calc_xscore::ligand_sum_hbonds(), calc_pmf::pmfangle_of_two_vectors(), and md::pot_energy_bonds().
subroutine calc_chemscore::calc_hbonds ()
Definition at line 219 of file calc_chemscore.f90.
References g1_hb(), and g2_hb().
Referenced by calc_scores().
subroutine calc_chemscore::calc_lipo ()
Definition at line 243 of file calc_chemscore.f90.
References fr_lip().
Referenced by calc_scores().
subroutine calc_chemscore::calc_metals ()
Definition at line 258 of file calc_chemscore.f90.
References fr_met().
Referenced by calc_scores().
subroutine calc_chemscore::calc_rot ()
Definition at line 272 of file calc_chemscore.f90.
Referenced by calc_scores().
subroutine calc_chemscore::calc_scores ()
Definition at line 297 of file calc_chemscore.f90.
References calc_hbonds(), calc_lipo(), calc_metals(), calc_rot(), frozen(), q_contacts(), and set_waters().
Referenced by score_calc(), and score_precalc().
subroutine calc_chemscore::chemscore_finalize ()
Definition at line 176 of file calc_chemscore.f90.
Referenced by finalize().
subroutine calc_chemscore::count_qlipo ()
Definition at line 310 of file calc_chemscore.f90.
References lip_atom().
Referenced by set_ligand().
real function calc_chemscore::dist (integer a, integer b)
Definition at line 1225 of file calc_chemscore.f90.
Referenced by fr_lip(), fr_met(), g1_hb(), q_contacts(), and calc_rdf::rdf_calc().
real function calc_chemscore::distsq (integer a, integer b)
Definition at line 1240 of file calc_chemscore.f90.
Referenced by angle().
recursive function calc_chemscore::find_contact (type(q_atom), pointer atom)
Definition at line 403 of file calc_chemscore.f90.
References md::bond().
Referenced by frozen().
real function calc_chemscore::fr_lip (integer a, integer b)
Definition at line 1256 of file calc_chemscore.f90.
References dist().
Referenced by calc_lipo().
real function calc_chemscore::fr_met (integer a, integer b)
Definition at line 1279 of file calc_chemscore.f90.
References dist().
Referenced by calc_metals().
subroutine calc_chemscore::frozen ()
Definition at line 381 of file calc_chemscore.f90.
References md::bond(), and find_contact().
Referenced by calc_scores().
real function calc_chemscore::g1_hb (integer a, integer b)
Definition at line 1297 of file calc_chemscore.f90.
References dist().
Referenced by calc_hbonds(), and score_waters().
real function calc_chemscore::g2_hb (integer a, integer b, integer c)
Definition at line 1318 of file calc_chemscore.f90.
References angle().
Referenced by calc_hbonds(), and score_waters().
subroutine calc_chemscore::get_atom_data ()
Definition at line 440 of file calc_chemscore.f90.
References indexer::index_get(), prmfile::prm_get_line(), prmfile::prm_get_string_real(), and prmfile::prm_open_section().
Referenced by start().
recursive function calc_chemscore::lip_atom (type(q_atom), pointer atom)
Definition at line 337 of file calc_chemscore.f90.
References md::bond().
Referenced by count_qlipo().
subroutine calc_chemscore::log_frame (integer, intent(in) iFrame)
Definition at line 184 of file calc_chemscore.f90.
Referenced by score_calc().
subroutine calc_chemscore::make_tac_index ()
Definition at line 506 of file calc_chemscore.f90.
References indexer::index_add(), and indexer::index_create().
Referenced by start().
subroutine calc_chemscore::mark_ring (type(q_bond), pointer bond, integer ir)
Definition at line 779 of file calc_chemscore.f90.
References md::bond(), and trace_ring().
Referenced by search_ring().
subroutine calc_chemscore::q_contacts ()
Definition at line 518 of file calc_chemscore.f90.
References dist(), and calc_xscore::distance().
Referenced by calc_scores().
subroutine calc_chemscore::q_types ()
Definition at line 541 of file calc_chemscore.f90.
Referenced by set_ligand().
subroutine calc_chemscore::report_ligand ()
Definition at line 595 of file calc_chemscore.f90.
Referenced by score_precalc().
subroutine calc_chemscore::report_protein ()
Definition at line 634 of file calc_chemscore.f90.
Referenced by score_precalc().
subroutine calc_chemscore::report_rings ()
Definition at line 648 of file calc_chemscore.f90.
Referenced by score_precalc().
subroutine calc_chemscore::reset_waters ()
Definition at line 664 of file calc_chemscore.f90.
Referenced by set_waters().
integer function calc_chemscore::score_add (character(*) desc)
Definition at line 1366 of file calc_chemscore.f90.
References misc::getlin(), misc::locase(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), and maskmanip::maskmanip_make().
Referenced by add_a_calc().
subroutine calc_chemscore::score_calc (integer, intent(in) iCalc, integer, intent(in) iFrame)
Definition at line 1455 of file calc_chemscore.f90.
References calc_scores(), and log_frame().
Referenced by calc_all().
subroutine calc_chemscore::score_heading (integer i)
Definition at line 210 of file calc_chemscore.f90.
Referenced by print_headings().
subroutine calc_chemscore::score_initialize ()
Definition at line 170 of file calc_chemscore.f90.
Referenced by initialize().
subroutine calc_chemscore::score_mean ()
Definition at line 1419 of file calc_chemscore.f90.
Referenced by make_mean_all().
subroutine calc_chemscore::score_precalc ()
Definition at line 1337 of file calc_chemscore.f90.
References calc_scores(), misc::centered_heading(), report_ligand(), report_protein(), report_rings(), set_ligand(), and start().
Referenced by do_pre_calcs().
subroutine calc_chemscore::score_waters ()
Definition at line 672 of file calc_chemscore.f90.
References g1_hb(), and g2_hb().
Referenced by set_waters().
recursive subroutine calc_chemscore::search_ring (type(q_bond), pointer bond, integer ir)
Definition at line 745 of file calc_chemscore.f90.
References md::bond(), and mark_ring().
Referenced by set_rings().
subroutine calc_chemscore::set_ligand ()
Definition at line 700 of file calc_chemscore.f90.
References count_qlipo(), q_types(), set_rings(), and set_rotatable().
Referenced by score_precalc().
subroutine calc_chemscore::set_rings ()
Definition at line 707 of file calc_chemscore.f90.
References search_ring().
Referenced by set_ligand().
subroutine calc_chemscore::set_rotatable ()
Definition at line 837 of file calc_chemscore.f90.
Referenced by set_ligand().
subroutine calc_chemscore::set_waters ()
Definition at line 862 of file calc_chemscore.f90.
References reset_waters(), score_waters(), and sort_waters().
Referenced by calc_scores().
subroutine calc_chemscore::sort_atoms ()
Definition at line 869 of file calc_chemscore.f90.
Referenced by start().
subroutine calc_chemscore::sort_bonds ()
Definition at line 928 of file calc_chemscore.f90.
Referenced by start().
subroutine calc_chemscore::sort_waters ()
Definition at line 1119 of file calc_chemscore.f90.
Referenced by set_waters().
subroutine calc_chemscore::start ()
Definition at line 1140 of file calc_chemscore.f90.
References misc::centered_heading(), get_atom_data(), make_tac_index(), qatom::qatom_load_atoms(), sort_atoms(), sort_bonds(), and store_waters().
Referenced by prmfile::load(), calc_pmf::pmfatom_walk(), score_precalc(), and misc::string_part().
subroutine calc_chemscore::store_waters ()
Definition at line 1190 of file calc_chemscore.f90.
Referenced by start().
recursive function calc_chemscore::trace_ring (type(q_atom), pointer atom, integer ir)
Definition at line 795 of file calc_chemscore.f90.
References md::bond().
Referenced by mark_ring().
Member Data Documentation
integer, parameter calc_chemscore::acceptor =4
Definition at line 122 of file calc_chemscore.f90.
type(score_precalc_type), dimension(:), pointer, private calc_chemscore::aprecalc [private]
Definition at line 43 of file calc_chemscore.f90.
type(score_type), dimension(:), pointer, private calc_chemscore::ascore [private]
Definition at line 47 of file calc_chemscore.f90.
type(atom_data_type), dimension(:), allocatable calc_chemscore::atom_data
Definition at line 146 of file calc_chemscore.f90.
character*80 calc_chemscore::atom_data_file
Definition at line 154 of file calc_chemscore.f90.
integer, private calc_chemscore::bdotopcalc [private]
Definition at line 161 of file calc_chemscore.f90.
logical, private calc_chemscore::busexin = .false. [private]
Definition at line 164 of file calc_chemscore.f90.
integer, parameter calc_chemscore::carbon_lipo =11
Definition at line 124 of file calc_chemscore.f90.
integer, parameter calc_chemscore::carbonyl_carbon =12
Definition at line 125 of file calc_chemscore.f90.
integer, parameter calc_chemscore::carbonyl_oxygen =13
Definition at line 125 of file calc_chemscore.f90.
character*80 calc_chemscore::coord_file
Definition at line 155 of file calc_chemscore.f90.
type(score_coord_type), dimension(max_masks), private calc_chemscore::coords [private]
Definition at line 57 of file calc_chemscore.f90.
real, parameter calc_chemscore::dgconst =-5.48
Definition at line 158 of file calc_chemscore.f90.
real, parameter calc_chemscore::dghbond =-3.34
Definition at line 158 of file calc_chemscore.f90.
real, parameter calc_chemscore::dglipo =-0.117
Definition at line 159 of file calc_chemscore.f90.
real, parameter calc_chemscore::dgmetal =-6.03
Definition at line 158 of file calc_chemscore.f90.
real, parameter calc_chemscore::dgrot =2.56
Definition at line 159 of file calc_chemscore.f90.
character*80 calc_chemscore::fep_file
Definition at line 23 of file calc_chemscore.f90.
character*(*), dimension(nprops), parameter calc_chemscore::file_heading = [ 'lipophilic '
Definition at line 127 of file calc_chemscore.f90.
integer calc_chemscore::frame
Definition at line 19 of file calc_chemscore.f90.
integer(ai), dimension(:), allocatable calc_chemscore::hba_l
Definition at line 105 of file calc_chemscore.f90.
integer(ai), dimension(:), allocatable calc_chemscore::hba_r
Definition at line 104 of file calc_chemscore.f90.
type(donor), dimension(:), allocatable calc_chemscore::hbd_l
Definition at line 103 of file calc_chemscore.f90.
type(donor), dimension(:), allocatable calc_chemscore::hbd_r
Definition at line 102 of file calc_chemscore.f90.
real calc_chemscore::hbond_term
Definition at line 157 of file calc_chemscore.f90.
integer, parameter calc_chemscore::hydrogen =9
Definition at line 124 of file calc_chemscore.f90.
integer calc_chemscore::i
Definition at line 21 of file calc_chemscore.f90.
integer, private calc_chemscore::iprecalc [private]
Definition at line 44 of file calc_chemscore.f90.
integer, dimension(:), allocatable calc_chemscore::iqatom
Definition at line 150 of file calc_chemscore.f90.
integer, private calc_chemscore::irestartcalc =-1 [private]
Definition at line 162 of file calc_chemscore.f90.
integer, parameter calc_chemscore::lipo =1
Definition at line 122 of file calc_chemscore.f90.
real calc_chemscore::lipo_term
Definition at line 157 of file calc_chemscore.f90.
integer(ai), dimension(:), allocatable calc_chemscore::lph_l
Definition at line 101 of file calc_chemscore.f90.
integer(ai), dimension(:), allocatable calc_chemscore::lph_r
Definition at line 100 of file calc_chemscore.f90.
type(mask_type), dimension(max_masks), target, private calc_chemscore::masks [private]
Definition at line 50 of file calc_chemscore.f90.
integer, parameter calc_chemscore::max_masks = 10
Definition at line 41 of file calc_chemscore.f90.
integer, private calc_chemscore::maxprecalc [private]
Definition at line 45 of file calc_chemscore.f90.
integer calc_chemscore::maxscores
Definition at line 48 of file calc_chemscore.f90.
integer(ai), dimension(:), allocatable calc_chemscore::met_r
Definition at line 106 of file calc_chemscore.f90.
integer, parameter calc_chemscore::metal =2
Definition at line 122 of file calc_chemscore.f90.
real calc_chemscore::metal_term
Definition at line 157 of file calc_chemscore.f90.
integer calc_chemscore::nhba_l
Definition at line 117 of file calc_chemscore.f90.
integer calc_chemscore::nhba_prot
Definition at line 118 of file calc_chemscore.f90.
integer calc_chemscore::nhba_r
Definition at line 117 of file calc_chemscore.f90.
integer calc_chemscore::nhbd_l
Definition at line 116 of file calc_chemscore.f90.
integer calc_chemscore::nhbd_prot
Definition at line 118 of file calc_chemscore.f90.
integer calc_chemscore::nhbd_r
Definition at line 116 of file calc_chemscore.f90.
integer calc_chemscore::nlph_l
Definition at line 116 of file calc_chemscore.f90.
integer calc_chemscore::nlph_r
Definition at line 116 of file calc_chemscore.f90.
integer, private calc_chemscore::nmasks = 0 [private]
Definition at line 51 of file calc_chemscore.f90.
integer calc_chemscore::nmet_r
Definition at line 117 of file calc_chemscore.f90.
integer, parameter calc_chemscore::nprops =13
Definition at line 126 of file calc_chemscore.f90.
integer calc_chemscore::nqbonds
Definition at line 117 of file calc_chemscore.f90.
integer calc_chemscore::nrings
Definition at line 119 of file calc_chemscore.f90.
integer calc_chemscore::nscores
Definition at line 48 of file calc_chemscore.f90.
integer calc_chemscore::nwaters
Definition at line 117 of file calc_chemscore.f90.
integer, parameter calc_chemscore::oxygen =10
Definition at line 124 of file calc_chemscore.f90.
integer, parameter calc_chemscore::pl_n =8
Definition at line 123 of file calc_chemscore.f90.
integer, dimension(:), allocatable calc_chemscore::pol_con
Definition at line 109 of file calc_chemscore.f90.
type(q_atom), dimension(:), allocatable, target, private calc_chemscore::q_atoms [private]
Definition at line 112 of file calc_chemscore.f90.
type(q_bond), dimension(:), allocatable, target, private calc_chemscore::q_bonds [private]
Definition at line 113 of file calc_chemscore.f90.
real calc_chemscore::rot_term
Definition at line 157 of file calc_chemscore.f90.
real calc_chemscore::score
Definition at line 18 of file calc_chemscore.f90.
integer, parameter calc_chemscore::sp2 =6
Definition at line 123 of file calc_chemscore.f90.
integer, parameter calc_chemscore::sp3 =5
Definition at line 123 of file calc_chemscore.f90.
integer, parameter calc_chemscore::sp3_n =7
Definition at line 123 of file calc_chemscore.f90.
integer calc_chemscore::stat
Definition at line 20 of file calc_chemscore.f90.
integer, parameter calc_chemscore::sulphur =3
Definition at line 122 of file calc_chemscore.f90.
character*80 calc_chemscore::top_file
Definition at line 23 of file calc_chemscore.f90.
character(len=4) calc_chemscore::trj_type
Definition at line 22 of file calc_chemscore.f90.
real, dimension(:), allocatable calc_chemscore::vdwr
Definition at line 152 of file calc_chemscore.f90.
integer, private calc_chemscore::warn [private]
Definition at line 166 of file calc_chemscore.f90.
type(wat), dimension(:), allocatable calc_chemscore::waters
Definition at line 107 of file calc_chemscore.f90.
The documentation for this module was generated from the following file:
calc_chemscore.f90