calc_rmsf Module Reference
Data Types
type rmsf_coord_type
Public Member Functions
subroutine rmsf_initialize
subroutine rmsf_finalize (i)
integer function rmsf_add (desc)
subroutine rmsf_calc (i)
subroutine rmsf_make_ref (i)
subroutine rmsf_heading (i)
Public Attributes
integer, parameter max_masks = 10
real(8), dimension(:), allocatable rmsf
Private Attributes
integer, dimension(max_masks),
*
private frames
integer, private apa
type(mask_type), dimension(max_masks),
*
target, private masks
integer, private nmasks = 0
type(rmsf_coord_type),
*
dimension(max_masks), private coords
Detailed Description
Definition at line 6 of file calc_rmsf.f90.
Member Function/Subroutine Documentation
integer function calc_rmsf::rmsf_add (character(*) desc)
Definition at line 33 of file calc_rmsf.f90.
References atom_mask::mask_finalize(), atom_mask::mask_initialize(), maskmanip::maskmanip_make(), and rmsf_make_ref().
Referenced by add_a_calc().
subroutine calc_rmsf::rmsf_calc (integer, intent(in) i)
Definition at line 65 of file calc_rmsf.f90.
References atom_mask::mask_get(), and calc_rdf::r().
Referenced by calc_all().
subroutine calc_rmsf::rmsf_finalize (integer i)
Definition at line 27 of file calc_rmsf.f90.
References atom_mask::mask_finalize().
Referenced by finalize().
subroutine calc_rmsf::rmsf_heading (integer i)
Definition at line 106 of file calc_rmsf.f90.
Referenced by print_headings().
subroutine calc_rmsf::rmsf_initialize ()
Definition at line 24 of file calc_rmsf.f90.
Referenced by initialize().
subroutine calc_rmsf::rmsf_make_ref (integer i)
Definition at line 98 of file calc_rmsf.f90.
References atom_mask::mask_get().
Referenced by make_ref_all(), and rmsf_add().
Member Data Documentation
integer, private calc_rmsf::apa [private]
Definition at line 14 of file calc_rmsf.f90.
type(rmsf_coord_type), dimension(max_masks), private calc_rmsf::coords [private]
Definition at line 21 of file calc_rmsf.f90.
integer, dimension(max_masks), private calc_rmsf::frames [private]
Definition at line 14 of file calc_rmsf.f90.
type(mask_type), dimension(max_masks), target, private calc_rmsf::masks [private]
Definition at line 16 of file calc_rmsf.f90.
integer, parameter calc_rmsf::max_masks = 10
Definition at line 12 of file calc_rmsf.f90.
integer, private calc_rmsf::nmasks = 0 [private]
Definition at line 17 of file calc_rmsf.f90.
real(8), dimension(:), allocatable calc_rmsf::rmsf
Definition at line 15 of file calc_rmsf.f90.
The documentation for this module was generated from the following file:
calc_rmsf.f90