calc_com_ke Module Reference
Data Types
type com_ke_coord_type
type com_ke_velocity_type
type coord_type
type dp_type
type eigen_stuff_type
type mass_ave_type
Public Member Functions
subroutine com_ke_initialize
subroutine com_ke_finalize (i)
integer function com_ke_add (desc)
subroutine com_ke_calc (i)
subroutine com_ke_put_mass (i)
subroutine com_ke_heading (i)
subroutine eigen (A, R, N, MV)
Public Attributes
integer, parameter max_masks = 10
real(8), dimension(:), allocatable kineticenergy
Private Attributes
integer, parameter, private conversion_factor = 2390.0574
integer, dimension(max_masks),
*
private frames
integer, private apa
type(mask_type), dimension(max_masks),
*
target, private masks
integer, private nmasks = 0
type(com_ke_coord_type),
*
dimension(max_masks), private coords_mass
type(com_ke_coord_type),
*
dimension(max_masks), private prev_coords_mass
type(com_ke_velocity_type),
*
dimension(max_masks), private velocity
type(com_ke_velocity_type),
*
dimension(max_masks), private rel_coords
type(com_ke_velocity_type),
*
dimension(max_masks), private prev_rel_coords
type(com_ke_velocity_type),
*
dimension(max_masks,
*
3), private rad_vec
type(coord_type), dimension(max_masks),
*
private coords
type(coord_type), dimension(max_masks),
*
private prev_coords
type(dp_type), dimension(max_masks),
*
private dp_vect
type(mass_ave_type), dimension(max_masks),
*
private mass_ave
type(mass_ave_type), dimension(max_masks),
*
private prev_mass_ave
type(mass_ave_type), dimension(max_masks,
*
3), private ang_momentum
type(eigen_stuff_type),
*
dimension(max_masks), private eigen_stuff
real, dimension(max_masks), private tot_mass
real, dimension(max_masks,
*
3), private ke_rot
logical, dimension(max_masks),
*
private first_frame = .true.
real, private frame_length = 0
Detailed Description
Definition at line 6 of file calc_com_ke.f90.
Member Function/Subroutine Documentation
integer function calc_com_ke::com_ke_add (character(*) desc)
Definition at line 71 of file calc_com_ke.f90.
References com_ke_put_mass(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), and maskmanip::maskmanip_make().
Referenced by add_a_calc().
subroutine calc_com_ke::com_ke_calc (integer, intent(in) i)
Definition at line 138 of file calc_com_ke.f90.
References eigen(), and atom_mask::mask_get().
Referenced by calc_all().
subroutine calc_com_ke::com_ke_finalize (integer i)
Definition at line 65 of file calc_com_ke.f90.
References atom_mask::mask_finalize().
Referenced by finalize().
subroutine calc_com_ke::com_ke_heading (integer i)
Definition at line 306 of file calc_com_ke.f90.
Referenced by print_headings().
subroutine calc_com_ke::com_ke_initialize ()
Definition at line 62 of file calc_com_ke.f90.
Referenced by initialize().
subroutine calc_com_ke::com_ke_put_mass (integer i)
Definition at line 283 of file calc_com_ke.f90.
Referenced by com_ke_add().
subroutine calc_com_ke::eigen (double precision, dimension(1) A, double precision, dimension(1) R, integer N, integer MV)
Definition at line 313 of file calc_com_ke.f90.
References calc_rdf::r().
Member Data Documentation
type(mass_ave_type), dimension(max_masks,3), private calc_com_ke::ang_momentum [private]
Definition at line 45 of file calc_com_ke.f90.
integer, private calc_com_ke::apa [private]
Definition at line 16 of file calc_com_ke.f90.
integer, parameter, private calc_com_ke::conversion_factor = 2390.0574 [private]
Definition at line 15 of file calc_com_ke.f90.
type(coord_type), dimension(max_masks), private calc_com_ke::coords [private]
Definition at line 33 of file calc_com_ke.f90.
type(com_ke_coord_type), dimension(max_masks), private calc_com_ke::coords_mass [private]
Definition at line 23 of file calc_com_ke.f90.
type(dp_type), dimension(max_masks), private calc_com_ke::dp_vect [private]
Definition at line 38 of file calc_com_ke.f90.
type(eigen_stuff_type), dimension(max_masks), private calc_com_ke::eigen_stuff [private]
Definition at line 50 of file calc_com_ke.f90.
logical, dimension(max_masks), private calc_com_ke::first_frame = .true. [private]
Definition at line 56 of file calc_com_ke.f90.
real, private calc_com_ke::frame_length = 0 [private]
Definition at line 58 of file calc_com_ke.f90.
integer, dimension(max_masks), private calc_com_ke::frames [private]
Definition at line 16 of file calc_com_ke.f90.
real, dimension(max_masks,3), private calc_com_ke::ke_rot [private]
Definition at line 55 of file calc_com_ke.f90.
real(8), dimension(:), allocatable calc_com_ke::kineticenergy
Definition at line 17 of file calc_com_ke.f90.
type(mask_type), dimension(max_masks), target, private calc_com_ke::masks [private]
Definition at line 18 of file calc_com_ke.f90.
type(mass_ave_type), dimension(max_masks), private calc_com_ke::mass_ave [private]
Definition at line 45 of file calc_com_ke.f90.
integer, parameter calc_com_ke::max_masks = 10
Definition at line 13 of file calc_com_ke.f90.
integer, private calc_com_ke::nmasks = 0 [private]
Definition at line 19 of file calc_com_ke.f90.
type(coord_type), dimension(max_masks), private calc_com_ke::prev_coords [private]
Definition at line 33 of file calc_com_ke.f90.
type(com_ke_coord_type), dimension(max_masks), private calc_com_ke::prev_coords_mass [private]
Definition at line 23 of file calc_com_ke.f90.
type(mass_ave_type), dimension(max_masks), private calc_com_ke::prev_mass_ave [private]
Definition at line 45 of file calc_com_ke.f90.
type(com_ke_velocity_type), dimension(max_masks), private calc_com_ke::prev_rel_coords [private]
Definition at line 28 of file calc_com_ke.f90.
type(com_ke_velocity_type), dimension(max_masks,3), private calc_com_ke::rad_vec [private]
Definition at line 28 of file calc_com_ke.f90.
type(com_ke_velocity_type), dimension(max_masks), private calc_com_ke::rel_coords [private]
Definition at line 28 of file calc_com_ke.f90.
real, dimension(max_masks), private calc_com_ke::tot_mass [private]
Definition at line 55 of file calc_com_ke.f90.
type(com_ke_velocity_type), dimension(max_masks), private calc_com_ke::velocity [private]
Definition at line 28 of file calc_com_ke.f90.
The documentation for this module was generated from the following file:
calc_com_ke.f90