calc_fit Module Reference
Data Types
type fit_coord_type
Public Member Functions
subroutine fit_initialize
subroutine fit_finalize (i)
integer function fit_add (desc)
subroutine fit_calc (i)
subroutine fit_make_ref (i)
integer function lsqstr (NR, W, XP, X, E, U)
Public Attributes
integer, parameter max_masks = 10
Private Attributes
type(mask_type), dimension(max_masks),
*
target, private masks
integer, private nmasks = 0
type(fit_coord_type),
*
dimension(max_masks), private coords
Detailed Description
Definition at line 7 of file calc_fit.f90.
Member Function/Subroutine Documentation
integer function calc_fit::fit_add (character(*) desc)
Definition at line 35 of file calc_fit.f90.
References fit_make_ref(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), and maskmanip::maskmanip_make().
Referenced by add_a_calc().
subroutine calc_fit::fit_calc (integer, intent(in) i)
Definition at line 68 of file calc_fit.f90.
References lsqstr().
Referenced by calc_all().
subroutine calc_fit::fit_finalize (integer i)
Definition at line 29 of file calc_fit.f90.
References atom_mask::mask_finalize().
Referenced by finalize().
subroutine calc_fit::fit_initialize ()
Definition at line 26 of file calc_fit.f90.
Referenced by initialize().
subroutine calc_fit::fit_make_ref (integer i)
Definition at line 118 of file calc_fit.f90.
Referenced by fit_add(), and make_ref_all().
integer function calc_fit::lsqstr (integer, intent(in) NR, logical(1), dimension(:), intent(in) W, real(8), dimension(:), intent(in) XP, real(8), dimension(:), intent(inout) X, real(8), intent(out), optional E, real(8), dimension(3,3), optional U)
Definition at line 148 of file calc_fit.f90.
References eigen().
Referenced by fit_calc(), and calc_entropy::rotationandtranslation().
Member Data Documentation
type(fit_coord_type), dimension(max_masks), private calc_fit::coords [private]
Definition at line 22 of file calc_fit.f90.
type(mask_type), dimension(max_masks), target, private calc_fit::masks [private]
Definition at line 15 of file calc_fit.f90.
integer, parameter calc_fit::max_masks = 10
Definition at line 13 of file calc_fit.f90.
integer, private calc_fit::nmasks = 0 [private]
Definition at line 16 of file calc_fit.f90.
The documentation for this module was generated from the following file:
calc_fit.f90