calc_entropy Module Reference
Data Types
type covariance_matrix
type entropy_coord_type
type trajectory
Public Member Functions
integer function entropy_add (desc)
subroutine construct_trajectory (t, Temp, startframe, endframe, no_atoms, Calc_type)
subroutine entropy_initialize
subroutine entropy_finalize (i)
subroutine entropy_heading (i)
subroutine entropy_calc (i)
subroutine covariancematrix (t)
subroutine schlittersformula (t, det)
subroutine multiplymatrices (t)
subroutine choleskyfactorization (t)
subroutine rotationandtranslation (t, i)
subroutine fit_make_reference (i)
subroutine quasiharmonic_analysis (i, t, det)
subroutine massweight (t)
subroutine viz (t)
subroutine entropy_ho (m, t, det)
subroutine pca (t, det)
subroutine euler_angles (t)
subroutine updatecovariancematrix (t, i)
Public Attributes
real(8) pi_val
real(8) hs
real(8) r
real(8) ref_vol
real(8) e
real(8) u
real(8) kb
real(8) cm
integer entropy_frame
integer start
Private Attributes
type(mask_type), dimension(max_masks),
*
target, private masks
integer, private nmasks = 0
type(entropy_coord_type),
*
dimension(max_masks), private coords
Detailed Description
Definition at line 5 of file calc_entropy.f90.
Member Function/Subroutine Documentation
subroutine calc_entropy::choleskyfactorization (type(trajectory) t)
Definition at line 445 of file calc_entropy.f90.
Referenced by schlittersformula().
subroutine calc_entropy::construct_trajectory (type(trajectory) t, real(8) Temp, integer startframe, integer endframe, integer no_atoms, integer Calc_type)
Definition at line 142 of file calc_entropy.f90.
Referenced by entropy_calc().
subroutine calc_entropy::covariancematrix (type(trajectory) t)
Definition at line 359 of file calc_entropy.f90.
Referenced by entropy_calc(), and pca().
integer function calc_entropy::entropy_add (character(*) desc)
Definition at line 58 of file calc_entropy.f90.
References misc::getlin(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), and maskmanip::maskmanip_make().
Referenced by add_a_calc().
subroutine calc_entropy::entropy_calc (integer, intent(in) i)
Definition at line 201 of file calc_entropy.f90.
References construct_trajectory(), covariancematrix(), fit_make_reference(), md::gauss(), atom_mask::mask_get(), pca(), quasiharmonic_analysis(), rotationandtranslation(), and schlittersformula().
Referenced by calc_all().
subroutine calc_entropy::entropy_finalize (integer i)
Definition at line 182 of file calc_entropy.f90.
References atom_mask::mask_finalize().
Referenced by finalize().
subroutine calc_entropy::entropy_heading (integer i)
Definition at line 192 of file calc_entropy.f90.
subroutine calc_entropy::entropy_ho (integer m, type(trajectory) t, real(8) det)
Definition at line 661 of file calc_entropy.f90.
Referenced by quasiharmonic_analysis().
subroutine calc_entropy::entropy_initialize ()
Definition at line 162 of file calc_entropy.f90.
Referenced by initialize().
subroutine calc_entropy::euler_angles (type(trajectory) t)
Definition at line 767 of file calc_entropy.f90.
Referenced by rotationandtranslation().
subroutine calc_entropy::fit_make_reference (integer i)
Definition at line 560 of file calc_entropy.f90.
Referenced by entropy_calc().
subroutine calc_entropy::massweight (type(trajectory) t)
Definition at line 616 of file calc_entropy.f90.
Referenced by quasiharmonic_analysis().
subroutine calc_entropy::multiplymatrices (type(trajectory) t)
Definition at line 405 of file calc_entropy.f90.
Referenced by schlittersformula().
subroutine calc_entropy::pca (type(trajectory) t, real(8) det)
Definition at line 720 of file calc_entropy.f90.
References covariancematrix(), eigen(), and viz().
Referenced by entropy_calc().
subroutine calc_entropy::quasiharmonic_analysis (integer i, type(trajectory) t, real(8) det)
Definition at line 598 of file calc_entropy.f90.
References eigen(), entropy_ho(), massweight(), and viz().
Referenced by entropy_calc().
subroutine calc_entropy::rotationandtranslation (type(trajectory) t, integer, intent(in) i)
Definition at line 471 of file calc_entropy.f90.
References euler_angles(), and calc_fit::lsqstr().
Referenced by entropy_calc().
subroutine calc_entropy::schlittersformula (type(trajectory) t, real(8) det)
Definition at line 382 of file calc_entropy.f90.
References choleskyfactorization(), and multiplymatrices().
Referenced by entropy_calc().
subroutine calc_entropy::updatecovariancematrix (type(trajectory) t, integer i)
Definition at line 801 of file calc_entropy.f90.
subroutine calc_entropy::viz (type(trajectory) t)
Definition at line 639 of file calc_entropy.f90.
Referenced by pca(), and quasiharmonic_analysis().
Member Data Documentation
real(8) calc_entropy::cm
Definition at line 16 of file calc_entropy.f90.
type(entropy_coord_type), dimension(max_masks), private calc_entropy::coords [private]
Definition at line 40 of file calc_entropy.f90.
real(8) calc_entropy::e
Definition at line 16 of file calc_entropy.f90.
integer calc_entropy::entropy_frame
Definition at line 41 of file calc_entropy.f90.
real(8) calc_entropy::hs
Definition at line 16 of file calc_entropy.f90.
real(8) calc_entropy::kb
Definition at line 16 of file calc_entropy.f90.
type(mask_type), dimension(max_masks), target, private calc_entropy::masks [private]
Definition at line 21 of file calc_entropy.f90.
integer, private calc_entropy::nmasks = 0 [private]
Definition at line 22 of file calc_entropy.f90.
real(8) calc_entropy::pi_val
Definition at line 16 of file calc_entropy.f90.
real(8) calc_entropy::r
Definition at line 16 of file calc_entropy.f90.
real(8) calc_entropy::ref_vol
Definition at line 16 of file calc_entropy.f90.
integer calc_entropy::start
Definition at line 41 of file calc_entropy.f90.
real(8) calc_entropy::u
Definition at line 16 of file calc_entropy.f90.
The documentation for this module was generated from the following file:
calc_entropy.f90