prmfile Module Reference
Data Types
type line_type
type section_type
Public Member Functions
subroutine prmfile_startup
logical function prm_get_integer_by_key (key, value, default)
logical function prm_get_real_by_key (key, value, default)
logical function prm_get_real8_by_key (key, value, default)
logical function prm_get_string_by_key (key, value, default)
logical function prm_get_line_by_key (key, value, default)
logical function prm_get_logical_by_key (key, value, default)
logical function prm_get_line (line)
logical function prm_get_field (field, skip)
integer function prm_count (section)
integer function prm_max_enum (section, count_out)
integer function prm_max_enum2 (section, count_out)
logical function prm_get_string_string (key, value)
logical function prm_get_string_line (key, value)
logical function prm_get_string_int (key, value)
logical function prm_get_string_real (key, value)
logical function prm_get_string_real8 (key, value)
logical function prm_get_int_real (key, value)
logical function prm_get_int_real8 (key, value)
logical function prm_get_int_int (key, value)
logical function prm_get_int (value)
logical function prm_open_section (section, filename)
subroutine rewind_section
logical function prm_get_next_title (title)
subroutine rewind_title
logical function prm_open (filename)
subroutine clear
subroutine prm_dump
subroutine prm_close
Public Attributes
type(section_type), pointer first_sec
type(section_type), pointer current_sec
type(line_type), pointer current_lp
integer section_count
character(len=80) current_title
character(len=80) next_title
Private Member Functions
logical function, private get_strings (key, value)
logical function, private find_section (section)
logical function, private load ()
logical function, private split (line, key, value)
logical function, private splitone (line, key, value)
Private Attributes
character(*), parameter, private module_version = '5.01'
character(*), parameter, private module_date = '2003-06-02'
integer, private prm_u = 0
character(200), private prm_fn
integer, private stat
Detailed Description
Definition at line 6 of file prmfile.f90.
Member Function/Subroutine Documentation
subroutine prmfile::clear ()
Definition at line 802 of file prmfile.f90.
Referenced by load(), and prm_close().
logical function, private prmfile::find_section (character(*), intent(in) section) [private]
Definition at line 708 of file prmfile.f90.
References misc::upcase().
Referenced by prm_count(), prm_max_enum(), prm_max_enum2(), and prm_open_section().
logical function, private prmfile::get_strings (character(*), intent(out) key, character(*), intent(out) value) [private]
Definition at line 645 of file prmfile.f90.
References prm_get_line(), and parse::split().
Referenced by prm_get_string_int(), prm_get_string_real(), prm_get_string_real8(), and prm_get_string_string().
logical function, private prmfile::load () [private]
Definition at line 853 of file prmfile.f90.
References clear(), rewind_title(), calc_chemscore::start(), and misc::upcase().
Referenced by prm_get_next_title(), and prm_open().
subroutine prmfile::prm_close ()
Definition at line 983 of file prmfile.f90.
References clear().
Referenced by md::initialize(), prm_open(), prm_open_section(), qatom::qatom_load_atoms(), qatom::qatom_load_fep(), prep::readff(), prep::readlib(), and prep::readparm().
integer function prmfile::prm_count (character(*), intent(in) section)
Definition at line 412 of file prmfile.f90.
References find_section().
Referenced by md::initialize(), qatom::qatom_load_atoms(), qatom::qatom_load_fep(), prep::readlib(), and prep::readparm().
subroutine prmfile::prm_dump ()
Definition at line 827 of file prmfile.f90.
References rewind_title().
logical function prmfile::prm_get_field (character(*), intent(out) field, logical, intent(in), optional skip)
Definition at line 350 of file prmfile.f90.
References prm_get_line().
Referenced by md::initialize(), qatom::qatom_load_fep(), and prep::readlib().
logical function prmfile::prm_get_int (integer, intent(out) value)
Definition at line 627 of file prmfile.f90.
References prm_get_line().
Referenced by prm_max_enum().
logical function prmfile::prm_get_int_int (integer, intent(out) key, integer, intent(out) value)
Definition at line 608 of file prmfile.f90.
References prm_get_line().
Referenced by qatom::qatom_load_atoms(), and qatom::qatom_load_fep().
logical function prmfile::prm_get_int_real (integer, intent(out) key, real, intent(out) value)
Definition at line 571 of file prmfile.f90.
References prm_get_line().
logical function prmfile::prm_get_int_real8 (integer, intent(out) key, real(8), intent(out) value)
Definition at line 589 of file prmfile.f90.
References prm_get_line().
Referenced by md::old_initialize().
logical function prmfile::prm_get_integer_by_key (character(*) key, integer, intent(out) value, integer, intent(in), optional default)
Definition at line 100 of file prmfile.f90.
References prm_get_string_int(), and rewind_section().
Referenced by md::initialize(), qatom::qatom_load_atoms(), and qatom::qatom_load_fep().
logical function prmfile::prm_get_line (character(*), intent(out) line)
Definition at line 330 of file prmfile.f90.
Referenced by calc_chemscore::get_atom_data(), get_strings(), md::initialize(), prm_get_field(), prm_get_int(), prm_get_int_int(), prm_get_int_real(), prm_get_int_real8(), prm_get_string_line(), qatom::qatom_load_atoms(), qatom::qatom_load_fep(), prep::readlib(), and prep::readparm().
logical function prmfile::prm_get_line_by_key (character(*) key, character(*), intent(out) value, character(*), intent(in), optional default)
Definition at line 247 of file prmfile.f90.
References prm_get_string_line(), and rewind_section().
Referenced by md::initialize().
logical function prmfile::prm_get_logical_by_key (character(*) key, logical, intent(out) value, logical, intent(in), optional default)
Definition at line 285 of file prmfile.f90.
References prm_get_string_string(), and rewind_section().
Referenced by md::initialize(), qatom::qatom_load_atoms(), prep::readlib(), and prep::readparm().
logical function prmfile::prm_get_next_title (character(*), intent(out) title)
Definition at line 748 of file prmfile.f90.
References load().
Referenced by prep::readlib().
logical function prmfile::prm_get_real8_by_key (character(*) key, real(8), intent(out) value, real(8), intent(in), optional default)
Definition at line 170 of file prmfile.f90.
References prm_get_string_real8(), and rewind_section().
Referenced by md::initialize().
logical function prmfile::prm_get_real_by_key (character(*) key, real, intent(out) value, real, intent(in), optional default)
Definition at line 135 of file prmfile.f90.
References prm_get_string_real(), and rewind_section().
Referenced by prep::readlib(), and prep::readparm().
logical function prmfile::prm_get_string_by_key (character(*) key, character(*), intent(out) value, character(*), intent(in), optional default)
Definition at line 205 of file prmfile.f90.
References prm_get_string_string(), rewind_section(), and misc::upcase().
Referenced by md::initialize(), qatom::qatom_load_atoms(), prep::readlib(), and prep::readparm().
logical function prmfile::prm_get_string_int (character(*), intent(out) key, integer, intent(out) value)
Definition at line 511 of file prmfile.f90.
References get_strings().
Referenced by prm_get_integer_by_key(), prm_max_enum2(), and qatom::qatom_load_atoms().
logical function prmfile::prm_get_string_line (character(*), intent(out) key, character(*), intent(out) value)
Definition at line 490 of file prmfile.f90.
References prm_get_line(), and splitone().
Referenced by prm_get_line_by_key().
logical function prmfile::prm_get_string_real (character(*), intent(out) key, real, intent(out) value)
Definition at line 532 of file prmfile.f90.
References get_strings().
Referenced by calc_chemscore::get_atom_data(), and prm_get_real_by_key().
logical function prmfile::prm_get_string_real8 (character(*), intent(out) key, real(8), intent(out) value)
Definition at line 551 of file prmfile.f90.
References get_strings().
Referenced by prm_get_real8_by_key().
logical function prmfile::prm_get_string_string (character(*), intent(out) key, character(*), intent(out) value)
Definition at line 480 of file prmfile.f90.
References get_strings().
Referenced by prm_get_logical_by_key(), prm_get_string_by_key(), qatom::qatom_load_atoms(), and prep::readparm().
integer function prmfile::prm_max_enum (character(*), intent(in) section, integer, intent(out), optional count_out)
Definition at line 428 of file prmfile.f90.
References find_section(), prm_get_int(), and rewind_section().
Referenced by qatom::qatom_load_atoms(), and qatom::qatom_load_fep().
integer function prmfile::prm_max_enum2 (character(*), intent(in) section, integer, intent(out), optional count_out)
Definition at line 455 of file prmfile.f90.
References find_section(), prm_get_string_int(), and rewind_section().
Referenced by qatom::qatom_load_atoms().
logical function prmfile::prm_open (character(*), intent(in) filename)
Definition at line 778 of file prmfile.f90.
References misc::freefile(), load(), and prm_close().
Referenced by prm_open_section(), qatom::qatom_load_fep(), prep::readff(), and prep::readlib().
logical function prmfile::prm_open_section (character(*), intent(in) section, character(*), intent(in), optional filename)
Definition at line 666 of file prmfile.f90.
References find_section(), prm_close(), and prm_open().
Referenced by calc_chemscore::get_atom_data(), md::initialize(), qatom::qatom_load_atoms(), qatom::qatom_load_fep(), prep::readlib(), and prep::readparm().
subroutine prmfile::prmfile_startup ()
Definition at line 94 of file prmfile.f90.
Referenced by prep::prep_startup(), and qatom::qatom_startup().
subroutine prmfile::rewind_section ()
Definition at line 696 of file prmfile.f90.
References rewind_title().
Referenced by prm_get_integer_by_key(), prm_get_line_by_key(), prm_get_logical_by_key(), prm_get_real8_by_key(), prm_get_real_by_key(), prm_get_string_by_key(), prm_max_enum(), and prm_max_enum2().
subroutine prmfile::rewind_title ()
Definition at line 767 of file prmfile.f90.
Referenced by load(), prm_dump(), and rewind_section().
logical function, private prmfile::split (character(*), intent(in) line, character(*), intent(out) key, character(*), intent(out) value) [private]
Definition at line 993 of file prmfile.f90.
References parse::split().
logical function, private prmfile::splitone (character(*), intent(in) line, character(*), intent(out) key, character(*), intent(out) value) [private]
Definition at line 1040 of file prmfile.f90.
Referenced by prm_get_string_line().
Member Data Documentation
type(line_type), pointer prmfile::current_lp
Definition at line 79 of file prmfile.f90.
type(section_type), pointer prmfile::current_sec
Definition at line 78 of file prmfile.f90.
character(len=80) prmfile::current_title
Definition at line 82 of file prmfile.f90.
type(section_type), pointer prmfile::first_sec
Definition at line 78 of file prmfile.f90.
character(*), parameter, private prmfile::module_date = '2003-06-02' [private]
Definition at line 62 of file prmfile.f90.
character(*), parameter, private prmfile::module_version = '5.01' [private]
Definition at line 61 of file prmfile.f90.
character(len=80) prmfile::next_title
Definition at line 82 of file prmfile.f90.
character(200), private prmfile::prm_fn [private]
Definition at line 84 of file prmfile.f90.
integer, private prmfile::prm_u = 0 [private]
Definition at line 83 of file prmfile.f90.
integer prmfile::section_count
Definition at line 80 of file prmfile.f90.
integer, private prmfile::stat [private]
Definition at line 85 of file prmfile.f90.
The documentation for this module was generated from the following file:
prmfile.f90