topo Module Reference
Data Types
type ang_type
type anglib_type
type bond_type
type bondlib_type
type cgp_type
type iac_type
type implib_type
type lj2_type
type residue_type
type tor_type
type torlib_type
Public Member Functions
subroutine topo_startup
subroutine topo_set_max (max, max_lib, max_nbr)
subroutine topo_allocate_potential (stat_out)
subroutine topo_allocate_atom (stat_out)
subroutine topo_deallocate (keep_ff)
subroutine topo_reallocate_xtop (atoms)
subroutine topo_reallocate (oldatoms, atoms, waters)
logical function topo_load (filename, require_version)
integer function topo_open (filename)
logical function topo_read (u, require_version, extrabonds)
subroutine topo_save (name)
Public Attributes
integer, parameter nljtyp = 3
integer, parameter max_nbr_range = 25
real version
character(len=80) title = ''
character(len=80) forcefield = ''
character(len=8) creation_date
character(len=256) pdb_file = ''
character(len=256) lib_files = ''
character(len=256) prm_file
integer nat_pro
integer nat_solute
integer max_atom
real(8), dimension(:), allocatable xtop
integer(tiny), dimension(:),
*
allocatable iac
logical, dimension(:), allocatable heavy
real, dimension(:), allocatable crg
integer(ai), dimension(:),
*
allocatable cgpatom
integer, parameter solvent_spc =0
integer, parameter solvent_3atom =1
integer, parameter solvent_general =2
integer solvent_type
integer, dimension(:), allocatable glb_cofactor
integer, public ligand_offset
real(8), dimension(3) xpcent
real(8), dimension(3) xwcent
real(8) rwat
real(8) rexcl_o
real(8) rexcl_i
integer nexats
integer nshellats
integer nexwat
logical, dimension(:), allocatable shell
logical, dimension(:), allocatable excl
real(8), dimension(3) boxlength
real(8), dimension(3) boxcentre
real(8), dimension(3) inv_boxl
logical use_pbc = .false.
integer nbonds
integer nbonds_solute
integer max_bonds
type(bond_type), dimension(:),
*
allocatable bnd
integer nbndcod
integer max_bondlib
type(bondlib_type), dimension(:),
*
allocatable bondlib
character(len=3), dimension(:),
*
allocatable sybyl_bond_type
integer nangles
integer nangles_solute
integer max_angles
type(ang_type), dimension(:),
*
allocatable ang
integer nangcod
integer max_anglib
type(anglib_type), dimension(:),
*
allocatable anglib
integer ntors
integer ntors_solute
integer ntorcod
integer max_tors
integer max_torlib
integer nimps
integer nimps_solute
integer nimpcod
integer max_imps
integer max_implib
integer imp_type
type(tor_type), dimension(:),
*
allocatable, target tor
type(tor_type), dimension(:),
*
allocatable, target imp
type(torlib_type), dimension(:),
*
allocatable, target torlib
type(implib_type), dimension(:),
*
allocatable, target implib
integer ncgp
integer ncgp_solute
integer max_cgp
type(cgp_type), dimension(:),
*
allocatable cgp
integer natyps
integer max_atyps
integer nlj2
integer max_lj2
type(iac_type), dimension(:),
*
allocatable iaclib
character(len=5), dimension(:),
*
allocatable sybyl_atom_type
character(len=8), dimension(:),
*
allocatable tac
type(lj2_type), dimension(:),
*
allocatable lj2
integer ivdw_rule
integer, parameter vdw_geometric =1
integer, parameter vdw_arithmetic =2
real(8) el14_scale
integer iuse_switch_atom
real(8) coulomb_constant
integer ff_type
integer, parameter ff_gromos =1
integer, parameter ff_amber =2
integer, parameter ff_charmm =3
integer n14nbrs
integer nexnbrs
integer max_exbnrs
integer n14long
integer max_14long
integer nexlong
integer max_exlong
logical, dimension(:,:),
*
allocatable list14
logical, dimension(:,:),
*
allocatable listex
integer(ai), dimension(:,:),
*
allocatable list14long
integer(ai), dimension(:,:),
*
pointer listexlong
integer nres
integer nres_solute
integer max_res
type(residue_type), dimension(:),
*
allocatable res
integer nmol
integer max_mol
integer, dimension(:), allocatable istart_mol
Private Member Functions
subroutine, private topo_check_alloc (message)
Private Attributes
real, parameter, private module_version = 5.03
character(*), parameter, private module_date = '2003-11-12'
integer, private alloc_status
Detailed Description
Definition at line 6 of file topo.f90.
Member Function/Subroutine Documentation
subroutine topo::topo_allocate_atom (integer, intent(out), optional stat_out)
Definition at line 262 of file topo.f90.
Referenced by md::init_nodes(), and topo_read().
subroutine topo::topo_allocate_potential (integer, intent(out), optional stat_out)
Definition at line 227 of file topo.f90.
Referenced by md::init_nodes().
subroutine, private topo::topo_check_alloc (character(*) message) [private]
Definition at line 422 of file topo.f90.
Referenced by topo_read(), topo_reallocate(), topo_reallocate_xtop(), and topo_save().
subroutine topo::topo_deallocate (logical, intent(in), optional keep_ff)
Definition at line 291 of file topo.f90.
Referenced by finalize_topology(), md::md_shutdown(), prep::prep_shutdown(), prep::readpdb(), and topo_read().
logical function topo::topo_load (character(*) filename, real, intent(in) require_version)
Definition at line 436 of file topo.f90.
References topo_open(), and topo_read().
Referenced by get_topology(), and md::topology().
integer function topo::topo_open (character(*) filename)
Definition at line 463 of file topo.f90.
References misc::freefile().
Referenced by topo_load().
logical function topo::topo_read (integer u, real, intent(in) require_version, integer, intent(in), optional extrabonds)
Definition at line 487 of file topo.f90.
References misc::centered_heading(), topo_allocate_atom(), topo_check_alloc(), topo_deallocate(), and misc::upcase().
Referenced by prep::readtop(), and topo_load().
subroutine topo::topo_reallocate (integer oldatoms, integer atoms, integer waters)
Definition at line 357 of file topo.f90.
References topo_check_alloc().
subroutine topo::topo_reallocate_xtop (integer atoms)
Definition at line 335 of file topo.f90.
References topo_check_alloc().
subroutine topo::topo_save (character(*) name)
Definition at line 1036 of file topo.f90.
References misc::centered_heading(), misc::freefile(), and topo_check_alloc().
Referenced by prep::writetop().
subroutine topo::topo_set_max (integer max, integer max_lib, integer max_nbr)
Definition at line 194 of file topo.f90.
Referenced by prep::make_solute_bonds(), prep::maketop(), and qprep().
subroutine topo::topo_startup ()
Definition at line 189 of file topo.f90.
Referenced by atom_mask::mask_startup(), and prep::prep_startup().
Member Data Documentation
integer, private topo::alloc_status [private]
Definition at line 75 of file topo.f90.
type(ang_type), dimension(:), allocatable topo::ang
Definition at line 129 of file topo.f90.
type(anglib_type), dimension(:), allocatable topo::anglib
Definition at line 132 of file topo.f90.
type(bond_type), dimension(:), allocatable topo::bnd
Definition at line 121 of file topo.f90.
type(bondlib_type), dimension(:), allocatable topo::bondlib
Definition at line 124 of file topo.f90.
real(8), dimension(3) topo::boxcentre
Definition at line 113 of file topo.f90.
real(8), dimension(3) topo::boxlength
Definition at line 112 of file topo.f90.
type(cgp_type), dimension(:), allocatable topo::cgp
Definition at line 146 of file topo.f90.
integer(ai), dimension(:), allocatable topo::cgpatom
Definition at line 95 of file topo.f90.
real(8) topo::coulomb_constant
Definition at line 161 of file topo.f90.
character(len=8) topo::creation_date
Definition at line 83 of file topo.f90.
real, dimension(:), allocatable topo::crg
Definition at line 94 of file topo.f90.
real(8) topo::el14_scale
Definition at line 159 of file topo.f90.
logical, dimension(:), allocatable topo::excl
Definition at line 109 of file topo.f90.
integer, parameter topo::ff_amber =2
Definition at line 165 of file topo.f90.
integer, parameter topo::ff_charmm =3
Definition at line 165 of file topo.f90.
integer, parameter topo::ff_gromos =1
Definition at line 165 of file topo.f90.
integer topo::ff_type
Definition at line 164 of file topo.f90.
character(len=80) topo::forcefield = ''
Definition at line 82 of file topo.f90.
integer, dimension(:), allocatable topo::glb_cofactor
Definition at line 98 of file topo.f90.
logical, dimension(:), allocatable topo::heavy
Definition at line 93 of file topo.f90.
integer(tiny), dimension(:), allocatable topo::iac
Definition at line 92 of file topo.f90.
type(iac_type), dimension(:), allocatable topo::iaclib
Definition at line 151 of file topo.f90.
type(tor_type), dimension(:), allocatable, target topo::imp
Definition at line 140 of file topo.f90.
integer topo::imp_type
Definition at line 138 of file topo.f90.
type(implib_type), dimension(:), allocatable, target topo::implib
Definition at line 142 of file topo.f90.
real(8), dimension(3) topo::inv_boxl
Definition at line 114 of file topo.f90.
integer, dimension(:), allocatable topo::istart_mol
Definition at line 183 of file topo.f90.
integer topo::iuse_switch_atom
Definition at line 160 of file topo.f90.
integer topo::ivdw_rule
Definition at line 157 of file topo.f90.
character(len=256) topo::lib_files = ''
Definition at line 85 of file topo.f90.
integer, public topo::ligand_offset
Definition at line 100 of file topo.f90.
logical, dimension(:,:), allocatable topo::list14
Definition at line 172 of file topo.f90.
integer(ai), dimension(:,:), allocatable topo::list14long
Definition at line 174 of file topo.f90.
logical, dimension(:,:), allocatable topo::listex
Definition at line 173 of file topo.f90.
integer(ai), dimension(:,:), pointer topo::listexlong
Definition at line 176 of file topo.f90.
type(lj2_type), dimension(:), allocatable topo::lj2
Definition at line 154 of file topo.f90.
integer topo::max_14long
Definition at line 170 of file topo.f90.
integer topo::max_angles
Definition at line 128 of file topo.f90.
integer topo::max_anglib
Definition at line 131 of file topo.f90.
integer topo::max_atom
Definition at line 90 of file topo.f90.
integer topo::max_atyps
Definition at line 149 of file topo.f90.
integer topo::max_bondlib
Definition at line 123 of file topo.f90.
integer topo::max_bonds
Definition at line 120 of file topo.f90.
integer topo::max_cgp
Definition at line 145 of file topo.f90.
integer topo::max_exbnrs
Definition at line 169 of file topo.f90.
integer topo::max_exlong
Definition at line 171 of file topo.f90.
integer topo::max_implib
Definition at line 138 of file topo.f90.
integer topo::max_imps
Definition at line 138 of file topo.f90.
integer topo::max_lj2
Definition at line 150 of file topo.f90.
integer topo::max_mol
Definition at line 182 of file topo.f90.
integer, parameter topo::max_nbr_range = 25
Definition at line 17 of file topo.f90.
integer topo::max_res
Definition at line 179 of file topo.f90.
integer topo::max_torlib
Definition at line 136 of file topo.f90.
integer topo::max_tors
Definition at line 136 of file topo.f90.
character(*), parameter, private topo::module_date = '2003-11-12' [private]
Definition at line 14 of file topo.f90.
real, parameter, private topo::module_version = 5.03 [private]
Definition at line 13 of file topo.f90.
integer topo::n14long
Definition at line 170 of file topo.f90.
integer topo::n14nbrs
Definition at line 168 of file topo.f90.
integer topo::nangcod
Definition at line 131 of file topo.f90.
integer topo::nangles
Definition at line 128 of file topo.f90.
integer topo::nangles_solute
Definition at line 128 of file topo.f90.
integer topo::nat_pro
Definition at line 90 of file topo.f90.
integer topo::nat_solute
Definition at line 90 of file topo.f90.
integer topo::natyps
Definition at line 149 of file topo.f90.
integer topo::nbndcod
Definition at line 123 of file topo.f90.
integer topo::nbonds
Definition at line 120 of file topo.f90.
integer topo::nbonds_solute
Definition at line 120 of file topo.f90.
integer topo::ncgp
Definition at line 145 of file topo.f90.
integer topo::ncgp_solute
Definition at line 145 of file topo.f90.
integer topo::nexats
Definition at line 107 of file topo.f90.
integer topo::nexlong
Definition at line 171 of file topo.f90.
integer topo::nexnbrs
Definition at line 169 of file topo.f90.
integer topo::nexwat
Definition at line 107 of file topo.f90.
integer topo::nimpcod
Definition at line 137 of file topo.f90.
integer topo::nimps
Definition at line 137 of file topo.f90.
integer topo::nimps_solute
Definition at line 137 of file topo.f90.
integer topo::nlj2
Definition at line 150 of file topo.f90.
integer, parameter topo::nljtyp = 3
Definition at line 16 of file topo.f90.
integer topo::nmol
Definition at line 182 of file topo.f90.
integer topo::nres
Definition at line 179 of file topo.f90.
integer topo::nres_solute
Definition at line 179 of file topo.f90.
integer topo::nshellats
Definition at line 107 of file topo.f90.
integer topo::ntorcod
Definition at line 135 of file topo.f90.
integer topo::ntors
Definition at line 135 of file topo.f90.
integer topo::ntors_solute
Definition at line 135 of file topo.f90.
character(len=256) topo::pdb_file = ''
Definition at line 84 of file topo.f90.
character(len=256) topo::prm_file
Definition at line 86 of file topo.f90.
type(residue_type), dimension(:), allocatable topo::res
Definition at line 180 of file topo.f90.
real(8) topo::rexcl_i
Definition at line 106 of file topo.f90.
real(8) topo::rexcl_o
Definition at line 106 of file topo.f90.
real(8) topo::rwat
Definition at line 105 of file topo.f90.
logical, dimension(:), allocatable topo::shell
Definition at line 108 of file topo.f90.
integer, parameter topo::solvent_3atom =1
Definition at line 96 of file topo.f90.
integer, parameter topo::solvent_general =2
Definition at line 96 of file topo.f90.
integer, parameter topo::solvent_spc =0
Definition at line 96 of file topo.f90.
integer topo::solvent_type
Definition at line 97 of file topo.f90.
character(len=5), dimension(:), allocatable topo::sybyl_atom_type
Definition at line 152 of file topo.f90.
character(len=3), dimension(:), allocatable topo::sybyl_bond_type
Definition at line 125 of file topo.f90.
character(len=8), dimension(:), allocatable topo::tac
Definition at line 153 of file topo.f90.
character(len=80) topo::title = ''
Definition at line 81 of file topo.f90.
type(tor_type), dimension(:), allocatable, target topo::tor
Definition at line 139 of file topo.f90.
type(torlib_type), dimension(:), allocatable, target topo::torlib
Definition at line 141 of file topo.f90.
logical topo::use_pbc = .false.
Definition at line 117 of file topo.f90.
integer, parameter topo::vdw_arithmetic =2
Definition at line 158 of file topo.f90.
integer, parameter topo::vdw_geometric =1
Definition at line 158 of file topo.f90.
real topo::version
Definition at line 80 of file topo.f90.
real(8), dimension(3) topo::xpcent
Definition at line 104 of file topo.f90.
real(8), dimension(:), allocatable topo::xtop
Definition at line 91 of file topo.f90.
real(8), dimension(3) topo::xwcent
Definition at line 104 of file topo.f90.
The documentation for this module was generated from the following file:
topo.f90