md Module Reference
Data Types
type cgp_pair_type
type lrf_type
type nb_type
type nbq_type
type nbqp_type
type profiling_var_type
type rstrdis_type
type rstrpos_type
type rstrseq_type
type rstrwal_type
type shake_bond_type
type shake_mol_type
type shell_type
Public Member Functions
subroutine md_startup
subroutine md_shutdown
subroutine die (cause)
subroutine allocate_natom_arrays
subroutine allocate_nbxx_per_cgp
subroutine allocate_lrf_arrays
subroutine allocate_mpi
subroutine allocate_watpol_arrays
subroutine check_alloc (message)
subroutine md_deallocate
subroutine reallocate_nonbondlist_pp
subroutine reallocate_nbpp_cgp
subroutine reallocate_nbpw_cgp
subroutine reallocate_nbqp_cgp
subroutine reallocate_nonbondlist_pw
subroutine reallocate_nonbondlist_qp
subroutine reallocate_nonbondlist_ww
real(8) function angle (istart, iend)
real(8) function urey_bradley (istart, iend)
real(8) function bond (istart, iend)
subroutine cgp_centers
subroutine make_nbqqlist
subroutine distribute_nonbonds
subroutine close_input_files
subroutine close_output_files
subroutine open_files
subroutine fix_shell
subroutine gauss (am, sd, v, ig)
subroutine get_fep
subroutine get_fname (text, length, filnam)
real(8) function improper (istart, iend)
real(8) function improper2 (istart, iend)
subroutine init_nodes
subroutine init_shake
subroutine initial_shaking
logical function initialize ()
logical function old_initialize (fu)
subroutine lrf_taylor
subroutine make_pair_lists
subroutine maxwell
subroutine temperature (Temp, Tscale_solute, Tscale_solvent, Ekinmax)
subroutine md_run
subroutine nbpp_count (npp, nppcgp)
subroutine nbpplis2
subroutine nbpplis2_box
subroutine nbpplis2_box_lrf
subroutine nbpplis2_lrf
subroutine nbpplist
subroutine nbpplist_box
subroutine nbpplist_lrf
subroutine nbpplist_box_lrf
subroutine nbpw_count (npw, npwcgp)
subroutine nbpwlis2
subroutine nbpwlis2_box
subroutine nbpwlis2_box_lrf
subroutine nbpwlis2_lrf
subroutine nbpwlist
subroutine nbpwlist_box
subroutine nbpwlist_lrf
subroutine nbpwlist_box_lrf
subroutine make_qconn
recursive subroutine find_bonded (origin, current, level, state)
integer function nbqq_count ()
subroutine nbqqlist
subroutine nbqp_count (nqp, nqpcgp)
subroutine nbqw_count (nqw, nqwmol)
subroutine nbqplis2
subroutine nbqplis2_box
subroutine nbqplist
subroutine nbqplist_box
subroutine nbqwlist
subroutine nbqwlist_box
subroutine nbww_count (nww, nwwmol)
subroutine nbwwlist
subroutine nbwwlist_box
subroutine nbwwlist_lrf
subroutine nbwwlist_box_lrf
subroutine nbmonitorlist
subroutine nonbond_monitor
subroutine nonbon2_pp
subroutine nonbon2_pp_box
subroutine nonbon2_pw
subroutine nonbon2_pw_box
subroutine nonbon2_qq
subroutine nonbon2_qq_lib_charges
subroutine nonbon2_qp
subroutine nonbon2_qp_box
subroutine nonbon2_qw
subroutine nonbon2_qw_box
subroutine nonbon2_ww
subroutine nonbon2_ww_box
subroutine nonbond_pp
subroutine nonbond_pp_box
subroutine nonbond_pw
subroutine nonbond_pw_box
subroutine nonbond_qq
subroutine nonbond_qq_lib_charges
subroutine nonbond_qp
subroutine nonbond_qp_box
subroutine nonbond_qp_qvdw
subroutine nonbond_qp_qvdw_box
subroutine nonbond_qw_spc
subroutine nonbond_qw_spc_box
subroutine nonbond_qw_3atom
subroutine nonbond_qw_3atom_box
subroutine nonbond_ww_spc
subroutine nonbond_ww_spc_box
subroutine nonbond_3atomsolvent
subroutine nonbond_3atomsolvent_box
subroutine offdiag
subroutine p_restrain
subroutine pot_energy
subroutine pot_energy_bonds
subroutine pot_energy_nonbonds
subroutine prep_coord
subroutine make_shell
subroutine make_shell2
subroutine init_trj
subroutine prep_sim
subroutine qangle (istate)
subroutine qurey_bradley (istate)
subroutine qbond (istate)
subroutine qimproper (istate)
subroutine qtorsion (istate)
real(8) function randm (ig)
integer function shake (xx, x)
subroutine shrink_topology
subroutine stop_cm_translation
subroutine topology
real(8) function torsion (istart, iend)
subroutine restrain_solvent
subroutine wat_sphere
subroutine wat_shells
subroutine watpol
subroutine write_out
subroutine write_trj
subroutine write_xfin
subroutine put_back_in_box
subroutine mc_volume ()
subroutine new_potential (old)
subroutine gather_nonbond ()
integer function get_atom_from_resnum_atnum (aid)
Public Attributes
character *(*), parameter md_version = '5.7'
character *(*), parameter md_date = '2015-02-22'
real, parameter rho_wat = 0.0335
real, parameter boltz = 0.001986
real(8) pi
real(8) deg2rad
integer stat
real, parameter temp_print_threshold =0.02
integer alloc_status
integer natom
integer nat3
integer(tiny), dimension(:),
*
allocatable iqatom
integer nwat
real(4) crg_ow
real(4) crg_hw
real(4) mu_w
logical box
logical rigid_box_centre
logical put_solute_back_in_box
logical put_solvent_back_in_box
logical constant_pressure = .false.
integer volume_try
integer volume_acc
real(8) pressure
real(8) max_vol_displ
integer pressure_seed
real(8), dimension(:), allocatable mol_mass
real(8), dimension(:), allocatable mass
logical control_box
real(8), dimension(3) new_boxl
integer nsteps
integer istep
integer iseed
logical restart
real(8) dt
real(8) temp0
real(8) tmaxw
real(8) tau_t
logical shake_solvent
logical shake_solute
logical shake_hydrogens
logical separate_scaling
logical use_lrf
integer nbcycle
real(8) rcpp
real(8) rcww
real(8) rcpw
real(8) rcq
real(8) rclrf
integer, parameter max_atyp = 255
integer, dimension(max_atyp,
*
max_atyp) ljcod
integer itrj_cycle
integer iene_cycle
integer itemp_cycle
integer iout_cycle
logical force_rms
integer ivolume_cycle
logical exclude_bonded
real(8) fk_pshell
real(8), parameter fk_fix = 200.0
real(8) dwmz
real(8) awmz
real(8) rwat_in
real(8) fkwpol
logical wpol_restr
logical wpol_born
real(8) fk_wsphere
real(8) crgtot
real(8) crgqtot
integer(ai), dimension(:,:),
*
allocatable list_sh
integer(ai), dimension(:,:),
*
allocatable nsort
real(8), dimension(:), allocatable theta
real(8), dimension(:), allocatable theta0
real(8), dimension(:), allocatable tdum
integer nwpolr_shell
integer n_max_insh
type(shell_type), dimension(:),
*
allocatable wshell
integer, parameter itdis_update = 100
real, parameter wpolr_layer = 3.0001
real, parameter drout = 0.5
real(8), parameter tau_t_default = 10.
real(8), parameter rcpp_default = 10.
real(8), parameter rcww_default = 10.
real(8), parameter rcpw_default = 10.
real(8), parameter rcq_default = 99.
real(8), parameter rclrf_default = 99.
real(8), parameter shell_default = 0.85
real(8), parameter fk_pshell_default = 10.
integer, parameter itrj_cycle_default = 100
integer, parameter iene_cycle_default = 10
integer, parameter iout_cycle_default = 10
integer, parameter nb_cycle_default = 10
real(8), parameter fkwpol_default = 20.
real(8), parameter fk_wsphere_default = 60.
logical, parameter wpol_restr_default = .true.
integer, parameter ivolume_cycle_default = 10
integer, parameter ipressure_cycle_default = 100
character(len=200) top_file
character(len=200) restart_file
character(len=200) xfin_file
character(len=200) trj_file
character(len=200) fep_file
character(len=200) ene_file
character(len=200) exrstr_file
character(len=200) xwat_file
integer implicit_rstr_from_file
integer nrstr_seq
integer nrstr_pos
integer nrstr_dist
integer nrstr_wall
type(rstrseq_type), dimension(:),
*
allocatable rstseq
type(rstrpos_type), dimension(:),
*
allocatable rstpos
type(rstrdis_type), dimension(:),
*
allocatable rstdis
type(rstrwal_type), dimension(:),
*
allocatable rstwal
real(8), dimension(:), allocatable d
real(8), dimension(:), allocatable x
real(8), dimension(:), allocatable xx
real(8), dimension(:), allocatable v
real, dimension(:), allocatable winv
real(8) grms
type(energies) e
real(8) tfree
real(8) tfree_solvent
real(8) tfree_solute
real(8) temp_solvent
real(8) temp_solute
real(8) texcl_solute
real(8) texcl_solvent
integer nbpp_pair
type(nb_type), dimension(:),
*
allocatable, target nbpp
integer nbww_pair
integer nbww_true_pair
integer(ai), dimension(:),
*
allocatable, target nbww
integer nbpw_pair
type(nb_type), dimension(:),
*
allocatable, target nbpw
integer nbqq_max
integer(tiny), dimension(:,:,:),
*
allocatable qconn
integer, dimension(max_states) nbqq_pair
type(nbq_type), dimension(:,:),
*
allocatable nbqq
integer nbqp_pair
type(nbqp_type), dimension(:),
*
allocatable, target nbqp
integer nbqw_pair
integer(ai), dimension(:),
*
allocatable nbqw
integer nbpp_cgp_pair
type(cgp_pair_type), dimension(:),
*
allocatable nbpp_cgp
integer nbpw_cgp_pair
type(cgp_pair_type), dimension(:),
*
allocatable nbpw_cgp
integer nbqp_cgp_pair
type(cgp_pair_type), dimension(:),
*
allocatable nbqp_cgp
integer(tiny), dimension(:,:,:,:),
*
allocatable special_ljcod
integer(ai), dimension(:),
*
allocatable iwhich_cgp
type(lrf_type), dimension(:),
*
allocatable lrf
type(lrf_type), dimension(:),
*
allocatable old_lrf
type(node_assignment_type) calculation_assignment
real(8), parameter shake_tol = 0.0001
integer, parameter shake_max_iter = 1000
integer shake_constraints
integer shake_molecules
type(shake_mol_type),
*
dimension(:), allocatable shake_mol
integer, parameter num_profiling_times = 11
type(profiling_var_type),
*
dimension(num_profiling_times) profile
real(8), dimension(:), allocatable all_node_times
real(8), dimension(:), allocatable node_times
integer ndegf
integer ndegfree
integer ndegf_solute
integer ndegfree_solute
integer ndegf_solvent
integer ndegfree_solvent
logical detail_temps
Detailed Description
Definition at line 19 of file md.f90.
Member Function/Subroutine Documentation
subroutine md::allocate_lrf_arrays ()
Definition at line 495 of file md.f90.
References check_alloc().
Referenced by init_nodes(), and prep_sim().
subroutine md::allocate_mpi ()
Definition at line 508 of file md.f90.
References check_alloc().
Referenced by init_nodes().
subroutine md::allocate_natom_arrays ()
Definition at line 467 of file md.f90.
References check_alloc().
Referenced by init_nodes(), and prep_coord().
subroutine md::allocate_nbxx_per_cgp ()
Definition at line 481 of file md.f90.
References check_alloc().
Referenced by distribute_nonbonds().
subroutine md::allocate_watpol_arrays ()
Definition at line 528 of file md.f90.
References check_alloc().
Referenced by wat_shells().
real(8) function md::angle (integer istart, integer iend)
Definition at line 817 of file md.f90.
References calc_chemscore::angle().
real(8) function md::bond (integer istart, integer iend)
Definition at line 958 of file md.f90.
Referenced by calc_chemscore::find_contact(), calc_chemscore::frozen(), calc_chemscore::lip_atom(), calc_chemscore::mark_ring(), calc_pmf::pmfprotein_translate(), pot_energy_bonds(), calc_chemscore::search_ring(), calc_chemscore::trace_ring(), and calc_xscore::xprotein_translate().
subroutine md::cgp_centers ()
Definition at line 1003 of file md.f90.
Referenced by make_pair_lists(), and mc_volume().
subroutine md::check_alloc (character(*) message)
Definition at line 542 of file md.f90.
References die().
Referenced by allocate_lrf_arrays(), allocate_mpi(), allocate_natom_arrays(), allocate_nbxx_per_cgp(), allocate_watpol_arrays(), distribute_nonbonds(), get_fep(), prep::grow_arrays_for_solvent(), init_nodes(), init_shake(), initialize(), make_nbqqlist(), md_run(), old_initialize(), prep::oldreadparm(), prep::readparm(), reallocate_nbpp_cgp(), reallocate_nbpw_cgp(), reallocate_nbqp_cgp(), reallocate_nonbondlist_pp(), reallocate_nonbondlist_pw(), reallocate_nonbondlist_qp(), reallocate_nonbondlist_ww(), prep::rwat_eff(), prep::solvate_box_file(), prep::solvate_box_grid(), prep::solvate_sphere_file(), prep::solvate_sphere_grid(), and wat_shells().
subroutine md::close_input_files ()
Definition at line 1368 of file md.f90.
Referenced by qdyn().
subroutine md::close_output_files ()
Definition at line 1378 of file md.f90.
Referenced by die(), and qdyn().
subroutine md::die (character(*), optional cause)
Definition at line 401 of file md.f90.
References misc::centered_heading(), close_output_files(), md_deallocate(), write_out(), and write_xfin().
Referenced by check_alloc(), distribute_nonbonds(), gather_nonbond(), get_atom_from_resnum_atnum(), get_fep(), init_nodes(), init_trj(), initialize(), mc_volume(), md_run(), nbmonitorlist(), old_initialize(), open_files(), prep_coord(), prep_sim(), put_back_in_box(), qdyn(), shake(), sigabrt_handler(), sigint_handler(), sigkill_handler(), topology(), and write_trj().
subroutine md::distribute_nonbonds ()
Definition at line 1046 of file md.f90.
References allocate_nbxx_per_cgp(), misc::centered_heading(), check_alloc(), die(), nbpp_count(), nbpw_count(), nbqp_count(), nbqw_count(), and nbww_count().
Referenced by qdyn().
recursive subroutine md::find_bonded (integer, intent(in) origin, integer, intent(in) current, integer, intent(in) level, integer, intent(in) state)
Definition at line 7302 of file md.f90.
Referenced by make_qconn().
subroutine md::fix_shell ()
Definition at line 1420 of file md.f90.
Referenced by pot_energy().
subroutine md::gather_nonbond ()
Definition at line 15819 of file md.f90.
References die().
Referenced by new_potential(), and pot_energy().
subroutine md::gauss (real(8) am, real(8) sd, real(8) v, integer ig)
Definition at line 1460 of file md.f90.
References randm().
Referenced by calc_entropy::entropy_calc(), and maxwell().
integer function md::get_atom_from_resnum_atnum (character(*), intent(in) aid)
Definition at line 15885 of file md.f90.
References die().
Referenced by prep_coord().
subroutine md::get_fep ()
Definition at line 1478 of file md.f90.
References misc::centered_heading(), check_alloc(), die(), qatom::qatom_load_atoms(), and qatom::qatom_load_fep().
Referenced by qdyn().
subroutine md::get_fname (character text, integer length, character filnam)
Definition at line 1662 of file md.f90.
Referenced by old_initialize().
real(8) function md::improper (integer istart, integer iend)
Definition at line 1684 of file md.f90.
Referenced by pot_energy_bonds().
real(8) function md::improper2 (integer istart, integer iend)
Definition at line 1799 of file md.f90.
Referenced by pot_energy_bonds().
subroutine md::init_nodes ()
Definition at line 1918 of file md.f90.
References allocate_lrf_arrays(), allocate_mpi(), allocate_natom_arrays(), misc::centered_heading(), check_alloc(), die(), topo::topo_allocate_atom(), and topo::topo_allocate_potential().
Referenced by qdyn().
subroutine md::init_shake ()
Definition at line 2335 of file md.f90.
References calc_chemscore::angle(), and check_alloc().
Referenced by qdyn().
subroutine md::init_trj ()
Definition at line 13614 of file md.f90.
References die(), trj::trj_commit_mask(), trj::trj_create(), and trj::trj_initialize().
Referenced by qdyn().
subroutine md::initial_shaking ()
Definition at line 2513 of file md.f90.
References shake().
Referenced by qdyn().
logical function md::initialize ()
Definition at line 2536 of file md.f90.
References misc::centered_heading(), check_alloc(), die(), misc::freefile(), initialize(), old_initialize(), misc::onoff(), prmfile::prm_close(), prmfile::prm_count(), prmfile::prm_get_field(), prmfile::prm_get_integer_by_key(), prmfile::prm_get_line(), prmfile::prm_get_line_by_key(), prmfile::prm_get_logical_by_key(), prmfile::prm_get_real8_by_key(), prmfile::prm_get_string_by_key(), prmfile::prm_open_section(), and trj::trj_store_mask().
subroutine md::lrf_taylor ()
Definition at line 3597 of file md.f90.
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::make_nbqqlist ()
Definition at line 1024 of file md.f90.
References check_alloc(), make_qconn(), nbqq_count(), and nbqqlist().
Referenced by qdyn().
subroutine md::make_pair_lists ()
Definition at line 3668 of file md.f90.
References cgp_centers(), nbpplis2(), nbpplis2_box(), nbpplis2_box_lrf(), nbpplis2_lrf(), nbpplist(), nbpplist_box(), nbpplist_box_lrf(), nbpplist_lrf(), nbpwlis2(), nbpwlis2_box(), nbpwlis2_box_lrf(), nbpwlis2_lrf(), nbpwlist(), nbpwlist_box(), nbpwlist_box_lrf(), nbpwlist_lrf(), nbqplis2(), nbqplis2_box(), nbqplist(), nbqplist_box(), nbqwlist(), nbqwlist_box(), nbwwlist(), nbwwlist_box(), nbwwlist_box_lrf(), nbwwlist_lrf(), and misc::rtime().
Referenced by md_run().
subroutine md::make_qconn ()
Definition at line 7258 of file md.f90.
References find_bonded().
Referenced by make_nbqqlist().
subroutine md::make_shell ()
Definition at line 13542 of file md.f90.
Referenced by prep_coord().
subroutine md::make_shell2 ()
Definition at line 13575 of file md.f90.
Referenced by parse_command(), and prep_coord().
subroutine md::maxwell ()
Definition at line 3740 of file md.f90.
References gauss().
Referenced by qdyn().
subroutine md::mc_volume ()
Definition at line 15441 of file md.f90.
References cgp_centers(), die(), nbpplis2_box_lrf(), nbpplist_box_lrf(), nbpwlis2_box_lrf(), nbpwlist_box_lrf(), nbwwlist_box_lrf(), new_potential(), and randm().
Referenced by md_run().
subroutine md::md_deallocate ()
Definition at line 558 of file md.f90.
Referenced by die(), and md_shutdown().
subroutine md::md_run ()
Definition at line 3859 of file md.f90.
References misc::centered_heading(), check_alloc(), die(), make_pair_lists(), mc_volume(), nonbond_monitor(), offdiag(), pot_energy(), put_back_in_box(), nrgy::put_ene(), misc::rtime(), shake(), temperature(), write_out(), write_trj(), and write_xfin().
Referenced by qdyn().
subroutine md::md_shutdown ()
Definition at line 391 of file md.f90.
References md_deallocate(), qatom::qatom_shutdown(), and topo::topo_deallocate().
Referenced by shutdown().
subroutine md::md_startup ()
Definition at line 379 of file md.f90.
References qatom::qatom_startup(), and trj::trj_startup().
Referenced by startup().
subroutine md::nbmonitorlist ()
Definition at line 8719 of file md.f90.
References die().
Referenced by qdyn().
subroutine md::nbpp_count (integer npp, integer, dimension(:) nppcgp)
Definition at line 4212 of file md.f90.
Referenced by distribute_nonbonds().
subroutine md::nbpplis2 ()
Definition at line 4330 of file md.f90.
References reallocate_nonbondlist_pp(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpplis2_box ()
Definition at line 4463 of file md.f90.
References reallocate_nbpp_cgp(), reallocate_nonbondlist_pp(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpplis2_box_lrf ()
Definition at line 4596 of file md.f90.
References reallocate_nbpp_cgp(), reallocate_nonbondlist_pp(), and misc::rtime().
Referenced by make_pair_lists(), and mc_volume().
subroutine md::nbpplis2_lrf ()
Definition at line 4872 of file md.f90.
References reallocate_nonbondlist_pp(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpplist ()
Definition at line 5121 of file md.f90.
References reallocate_nonbondlist_pp(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpplist_box ()
Definition at line 5253 of file md.f90.
References reallocate_nbpp_cgp(), reallocate_nonbondlist_pp(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpplist_box_lrf ()
Definition at line 5648 of file md.f90.
References reallocate_nbpp_cgp(), reallocate_nonbondlist_pp(), and misc::rtime().
Referenced by make_pair_lists(), and mc_volume().
subroutine md::nbpplist_lrf ()
Definition at line 5394 of file md.f90.
References reallocate_nonbondlist_pp(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpw_count (integer npw, integer, dimension(:) npwcgp)
Definition at line 5933 of file md.f90.
Referenced by distribute_nonbonds().
subroutine md::nbpwlis2 ()
Definition at line 6024 of file md.f90.
References reallocate_nonbondlist_pw(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpwlis2_box ()
Definition at line 6104 of file md.f90.
References reallocate_nbpw_cgp(), reallocate_nonbondlist_pw(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpwlis2_box_lrf ()
Definition at line 6189 of file md.f90.
References reallocate_nbpw_cgp(), reallocate_nonbondlist_pw(), and misc::rtime().
Referenced by make_pair_lists(), and mc_volume().
subroutine md::nbpwlis2_lrf ()
Definition at line 6423 of file md.f90.
References reallocate_nonbondlist_pw(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpwlist ()
Definition at line 6630 of file md.f90.
References reallocate_nonbondlist_pw(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpwlist_box ()
Definition at line 6716 of file md.f90.
References reallocate_nbpw_cgp(), reallocate_nonbondlist_pw(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbpwlist_box_lrf ()
Definition at line 7016 of file md.f90.
References reallocate_nbpw_cgp(), reallocate_nonbondlist_pw(), and misc::rtime().
Referenced by make_pair_lists(), and mc_volume().
subroutine md::nbpwlist_lrf ()
Definition at line 6810 of file md.f90.
References reallocate_nonbondlist_pw(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbqp_count (integer nqp, integer, dimension(:) nqpcgp)
Definition at line 7484 of file md.f90.
Referenced by distribute_nonbonds().
subroutine md::nbqplis2 ()
Definition at line 7614 of file md.f90.
References reallocate_nonbondlist_qp(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbqplis2_box ()
Definition at line 7724 of file md.f90.
References reallocate_nbqp_cgp(), reallocate_nonbondlist_qp(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbqplist ()
Definition at line 7825 of file md.f90.
References reallocate_nonbondlist_qp(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbqplist_box ()
Definition at line 7919 of file md.f90.
References reallocate_nbqp_cgp(), reallocate_nonbondlist_qp(), and misc::rtime().
Referenced by make_pair_lists().
integer function md::nbqq_count ()
Definition at line 7363 of file md.f90.
Referenced by make_nbqqlist().
subroutine md::nbqqlist ()
Definition at line 7399 of file md.f90.
References prep::set().
Referenced by make_nbqqlist().
subroutine md::nbqw_count (integer nqw, integer, dimension(:) nqwmol)
Definition at line 7560 of file md.f90.
Referenced by distribute_nonbonds().
subroutine md::nbqwlist ()
Definition at line 8016 of file md.f90.
References misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbqwlist_box ()
Definition at line 8073 of file md.f90.
References misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbww_count (integer nww, integer, dimension(:) nwwmol)
Definition at line 8120 of file md.f90.
Referenced by distribute_nonbonds().
subroutine md::nbwwlist ()
Definition at line 8183 of file md.f90.
References reallocate_nonbondlist_ww(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbwwlist_box ()
Definition at line 8248 of file md.f90.
References reallocate_nonbondlist_ww(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::nbwwlist_box_lrf ()
Definition at line 8508 of file md.f90.
References reallocate_nonbondlist_ww(), and misc::rtime().
Referenced by make_pair_lists(), and mc_volume().
subroutine md::nbwwlist_lrf ()
Definition at line 8320 of file md.f90.
References reallocate_nonbondlist_ww(), and misc::rtime().
Referenced by make_pair_lists().
subroutine md::new_potential (type(energies), intent(in) old)
Definition at line 15670 of file md.f90.
References gather_nonbond(), lrf_taylor(), nonbon2_pp_box(), nonbon2_pw_box(), nonbon2_qp_box(), nonbon2_qq(), nonbon2_qq_lib_charges(), nonbon2_qw_box(), nonbon2_ww_box(), nonbond_3atomsolvent_box(), nonbond_pp_box(), nonbond_pw_box(), nonbond_qp_box(), nonbond_qp_qvdw_box(), nonbond_qq(), nonbond_qq_lib_charges(), nonbond_qw_3atom_box(), nonbond_qw_spc_box(), nonbond_ww_spc_box(), and p_restrain().
Referenced by mc_volume().
subroutine md::nonbon2_pp ()
Definition at line 8922 of file md.f90.
Referenced by pot_energy_nonbonds().
subroutine md::nonbon2_pp_box ()
Definition at line 9042 of file md.f90.
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbon2_pw ()
Definition at line 9192 of file md.f90.
References calc_rdf::r().
Referenced by pot_energy_nonbonds().
subroutine md::nonbon2_pw_box ()
Definition at line 9251 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbon2_qp ()
Definition at line 9553 of file md.f90.
References calc_rdf::r().
Referenced by pot_energy_nonbonds().
subroutine md::nonbon2_qp_box ()
Definition at line 9643 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbon2_qq ()
Definition at line 9335 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy().
subroutine md::nonbon2_qq_lib_charges ()
Definition at line 9444 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy().
subroutine md::nonbon2_qw ()
Definition at line 9748 of file md.f90.
Referenced by pot_energy_nonbonds().
subroutine md::nonbon2_qw_box ()
Definition at line 9890 of file md.f90.
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbon2_ww ()
Definition at line 10049 of file md.f90.
References calc_rdf::r().
Referenced by pot_energy_nonbonds().
subroutine md::nonbon2_ww_box ()
Definition at line 10180 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbond_3atomsolvent ()
Definition at line 12263 of file md.f90.
Referenced by pot_energy_nonbonds().
subroutine md::nonbond_3atomsolvent_box ()
Definition at line 12541 of file md.f90.
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbond_monitor ()
Definition at line 8796 of file md.f90.
References calc_rdf::r().
Referenced by md_run().
subroutine md::nonbond_pp ()
Definition at line 10336 of file md.f90.
Referenced by pot_energy_nonbonds().
subroutine md::nonbond_pp_box ()
Definition at line 10444 of file md.f90.
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbond_pw ()
Definition at line 10580 of file md.f90.
References calc_rdf::r().
Referenced by pot_energy_nonbonds().
subroutine md::nonbond_pw_box ()
Definition at line 10635 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbond_qp ()
Definition at line 10929 of file md.f90.
References calc_rdf::r().
Referenced by pot_energy_nonbonds().
subroutine md::nonbond_qp_box ()
Definition at line 10998 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbond_qp_qvdw ()
Definition at line 11087 of file md.f90.
References calc_rdf::r().
Referenced by pot_energy_nonbonds().
subroutine md::nonbond_qp_qvdw_box ()
Definition at line 11156 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbond_qq ()
Definition at line 10712 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy().
subroutine md::nonbond_qq_lib_charges ()
Definition at line 10821 of file md.f90.
References calc_rdf::r().
Referenced by new_potential(), and pot_energy().
subroutine md::nonbond_qw_3atom ()
Definition at line 11494 of file md.f90.
Referenced by pot_energy_nonbonds().
subroutine md::nonbond_qw_3atom_box ()
Definition at line 11623 of file md.f90.
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbond_qw_spc ()
Definition at line 11251 of file md.f90.
Referenced by pot_energy_nonbonds().
subroutine md::nonbond_qw_spc_box ()
Definition at line 11364 of file md.f90.
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::nonbond_ww_spc ()
Definition at line 11772 of file md.f90.
Referenced by pot_energy_nonbonds().
subroutine md::nonbond_ww_spc_box ()
Definition at line 12000 of file md.f90.
Referenced by new_potential(), and pot_energy_nonbonds().
subroutine md::offdiag ()
Definition at line 12856 of file md.f90.
References calc_rdf::r().
Referenced by md_run().
logical function md::old_initialize (integer fu)
Definition at line 3235 of file md.f90.
References check_alloc(), die(), get_fname(), and prmfile::prm_get_int_real8().
Referenced by initialize().
subroutine md::open_files ()
Definition at line 1387 of file md.f90.
References die().
Referenced by qdyn().
subroutine md::p_restrain ()
Definition at line 12885 of file md.f90.
Referenced by new_potential(), and pot_energy().
subroutine md::pot_energy ()
Definition at line 13122 of file md.f90.
References fix_shell(), gather_nonbond(), nonbon2_qq(), nonbon2_qq_lib_charges(), nonbond_qq(), nonbond_qq_lib_charges(), p_restrain(), pot_energy_bonds(), pot_energy_nonbonds(), qangle(), qbond(), qimproper(), qtorsion(), qurey_bradley(), restrain_solvent(), misc::rtime(), and watpol().
Referenced by md_run().
subroutine md::pot_energy_bonds ()
Definition at line 13324 of file md.f90.
References calc_chemscore::angle(), bond(), improper(), improper2(), torsion(), and urey_bradley().
Referenced by pot_energy().
subroutine md::pot_energy_nonbonds ()
Definition at line 13362 of file md.f90.
References lrf_taylor(), nonbon2_pp(), nonbon2_pp_box(), nonbon2_pw(), nonbon2_pw_box(), nonbon2_qp(), nonbon2_qp_box(), nonbon2_qw(), nonbon2_qw_box(), nonbon2_ww(), nonbon2_ww_box(), nonbond_3atomsolvent(), nonbond_3atomsolvent_box(), nonbond_pp(), nonbond_pp_box(), nonbond_pw(), nonbond_pw_box(), nonbond_qp(), nonbond_qp_box(), nonbond_qp_qvdw(), nonbond_qp_qvdw_box(), nonbond_qw_3atom(), nonbond_qw_3atom_box(), nonbond_qw_spc(), nonbond_qw_spc_box(), nonbond_ww_spc(), and nonbond_ww_spc_box().
Referenced by pot_energy().
subroutine md::prep_coord ()
Definition at line 13444 of file md.f90.
References allocate_natom_arrays(), misc::centered_heading(), die(), get_atom_from_resnum_atnum(), make_shell(), and make_shell2().
Referenced by qdyn().
subroutine md::prep_sim ()
Definition at line 13635 of file md.f90.
References allocate_lrf_arrays(), misc::centered_heading(), die(), put_back_in_box(), wat_shells(), and wat_sphere().
Referenced by qdyn().
subroutine md::put_back_in_box ()
Definition at line 15305 of file md.f90.
References die().
Referenced by md_run(), and prep_sim().
subroutine md::qangle (integer istate)
Definition at line 13744 of file md.f90.
Referenced by pot_energy().
subroutine md::qbond (integer istate)
Definition at line 13908 of file md.f90.
Referenced by pot_energy().
subroutine md::qimproper (integer istate)
Definition at line 13965 of file md.f90.
Referenced by pot_energy().
subroutine md::qtorsion (integer istate)
Definition at line 14111 of file md.f90.
Referenced by pot_energy().
subroutine md::qurey_bradley (integer istate)
Definition at line 13840 of file md.f90.
Referenced by pot_energy().
real(8) function md::randm (integer ig)
Definition at line 14259 of file md.f90.
References calc_rdf::r().
Referenced by gauss(), prep::genh(), prep::makehyds(), mc_volume(), and prep::randm().
subroutine md::reallocate_nbpp_cgp ()
Definition at line 642 of file md.f90.
References check_alloc().
Referenced by nbpplis2_box(), nbpplis2_box_lrf(), nbpplist_box(), and nbpplist_box_lrf().
subroutine md::reallocate_nbpw_cgp ()
Definition at line 670 of file md.f90.
References check_alloc().
Referenced by nbpwlis2_box(), nbpwlis2_box_lrf(), nbpwlist_box(), and nbpwlist_box_lrf().
subroutine md::reallocate_nbqp_cgp ()
Definition at line 698 of file md.f90.
References check_alloc().
Referenced by nbqplis2_box(), and nbqplist_box().
subroutine md::reallocate_nonbondlist_pp ()
Definition at line 614 of file md.f90.
References check_alloc().
Referenced by nbpplis2(), nbpplis2_box(), nbpplis2_box_lrf(), nbpplis2_lrf(), nbpplist(), nbpplist_box(), nbpplist_box_lrf(), and nbpplist_lrf().
subroutine md::reallocate_nonbondlist_pw ()
Definition at line 728 of file md.f90.
References check_alloc().
Referenced by nbpwlis2(), nbpwlis2_box(), nbpwlis2_box_lrf(), nbpwlis2_lrf(), nbpwlist(), nbpwlist_box(), nbpwlist_box_lrf(), and nbpwlist_lrf().
subroutine md::reallocate_nonbondlist_qp ()
Definition at line 757 of file md.f90.
References check_alloc().
Referenced by nbqplis2(), nbqplis2_box(), nbqplist(), and nbqplist_box().
subroutine md::reallocate_nonbondlist_ww ()
Definition at line 786 of file md.f90.
References check_alloc().
Referenced by nbwwlist(), nbwwlist_box(), nbwwlist_box_lrf(), and nbwwlist_lrf().
subroutine md::restrain_solvent ()
Definition at line 14738 of file md.f90.
Referenced by pot_energy().
integer function md::shake (real(8), dimension(:) xx, real(8), dimension(:) x)
Definition at line 14297 of file md.f90.
References die(), and misc::rtime().
Referenced by initial_shaking(), and md_run().
subroutine md::shrink_topology ()
Definition at line 14396 of file md.f90.
References misc::centered_heading().
Referenced by qdyn().
subroutine md::stop_cm_translation ()
Definition at line 14497 of file md.f90.
Referenced by qdyn().
subroutine md::temperature (real(8) Temp, real(8) Tscale_solute, real(8) Tscale_solvent, real(8) Ekinmax)
Definition at line 3764 of file md.f90.
Referenced by md_run().
subroutine md::topology ()
Definition at line 14532 of file md.f90.
References die(), and topo::topo_load().
Referenced by qdyn().
real(8) function md::torsion (integer istart, integer iend)
Definition at line 14620 of file md.f90.
Referenced by pot_energy_bonds().
real(8) function md::urey_bradley (integer istart, integer iend)
Definition at line 907 of file md.f90.
Referenced by pot_energy_bonds().
subroutine md::wat_shells ()
Definition at line 14872 of file md.f90.
References allocate_watpol_arrays(), and check_alloc().
Referenced by prep_sim().
subroutine md::wat_sphere ()
Definition at line 14789 of file md.f90.
Referenced by prep_sim().
subroutine md::watpol ()
Definition at line 14950 of file md.f90.
References misc::centered_heading().
Referenced by pot_energy().
subroutine md::write_out ()
Definition at line 15120 of file md.f90.
References misc::centered_heading().
Referenced by die(), and md_run().
subroutine md::write_trj ()
Definition at line 15270 of file md.f90.
References die(), and trj::trj_write().
Referenced by md_run().
subroutine md::write_xfin ()
Definition at line 15280 of file md.f90.
Referenced by die(), and md_run().
Member Data Documentation
real(8), dimension(:), allocatable md::all_node_times
Definition at line 352 of file md.f90.
integer md::alloc_status
Definition at line 58 of file md.f90.
real(8) md::awmz
Definition at line 124 of file md.f90.
real, parameter md::boltz = 0.001986
Definition at line 48 of file md.f90.
logical md::box
Definition at line 76 of file md.f90.
type(node_assignment_type) md::calculation_assignment
Definition at line 312 of file md.f90.
logical md::constant_pressure = .false.
Definition at line 80 of file md.f90.
logical md::control_box
Definition at line 88 of file md.f90.
real(4) md::crg_hw
Definition at line 69 of file md.f90.
real(4) md::crg_ow
Definition at line 69 of file md.f90.
real(8) md::crgqtot
Definition at line 127 of file md.f90.
real(8) md::crgtot
Definition at line 127 of file md.f90.
real(8), dimension(:), allocatable md::d
Definition at line 220 of file md.f90.
real(8) md::deg2rad
Definition at line 49 of file md.f90.
logical md::detail_temps
Definition at line 364 of file md.f90.
real, parameter md::drout = 0.5
Definition at line 145 of file md.f90.
real(8) md::dt
Definition at line 98 of file md.f90.
real(8) md::dwmz
Definition at line 124 of file md.f90.
type(energies) md::e
Definition at line 231 of file md.f90.
character(len=200) md::ene_file
Definition at line 174 of file md.f90.
logical md::exclude_bonded
Definition at line 119 of file md.f90.
character(len=200) md::exrstr_file
Definition at line 175 of file md.f90.
character(len=200) md::fep_file
Definition at line 173 of file md.f90.
real(8), parameter md::fk_fix = 200.0
Definition at line 121 of file md.f90.
real(8) md::fk_pshell
Definition at line 120 of file md.f90.
real(8), parameter md::fk_pshell_default = 10.
Definition at line 154 of file md.f90.
real(8) md::fk_wsphere
Definition at line 127 of file md.f90.
real(8), parameter md::fk_wsphere_default = 60.
Definition at line 160 of file md.f90.
real(8) md::fkwpol
Definition at line 125 of file md.f90.
real(8), parameter md::fkwpol_default = 20.
Definition at line 159 of file md.f90.
logical md::force_rms
Definition at line 114 of file md.f90.
real(8) md::grms
Definition at line 225 of file md.f90.
integer md::iene_cycle
Definition at line 112 of file md.f90.
integer, parameter md::iene_cycle_default = 10
Definition at line 156 of file md.f90.
integer md::implicit_rstr_from_file
Definition at line 180 of file md.f90.
integer md::iout_cycle
Definition at line 113 of file md.f90.
integer, parameter md::iout_cycle_default = 10
Definition at line 157 of file md.f90.
integer, parameter md::ipressure_cycle_default = 100
Definition at line 163 of file md.f90.
integer(tiny), dimension(:), allocatable md::iqatom
Definition at line 65 of file md.f90.
integer md::iseed
Definition at line 96 of file md.f90.
integer md::istep
Definition at line 95 of file md.f90.
integer, parameter md::itdis_update = 100
Definition at line 143 of file md.f90.
integer md::itemp_cycle
Definition at line 113 of file md.f90.
integer md::itrj_cycle
Definition at line 112 of file md.f90.
integer, parameter md::itrj_cycle_default = 100
Definition at line 155 of file md.f90.
integer md::ivolume_cycle
Definition at line 116 of file md.f90.
integer, parameter md::ivolume_cycle_default = 10
Definition at line 162 of file md.f90.
integer(ai), dimension(:), allocatable md::iwhich_cgp
Definition at line 297 of file md.f90.
integer(ai), dimension(:,:), allocatable md::list_sh
Definition at line 128 of file md.f90.
integer, dimension(max_atyp,max_atyp) md::ljcod
Definition at line 108 of file md.f90.
type(lrf_type), dimension(:), allocatable md::lrf
Definition at line 308 of file md.f90.
real(8), dimension(:), allocatable md::mass
Definition at line 85 of file md.f90.
integer, parameter md::max_atyp = 255
Definition at line 107 of file md.f90.
real(8) md::max_vol_displ
Definition at line 82 of file md.f90.
character*(*), parameter md::md_date = '2015-02-22'
Definition at line 46 of file md.f90.
character*(*), parameter md::md_version = '5.7'
Definition at line 45 of file md.f90.
real(8), dimension(:), allocatable md::mol_mass
Definition at line 84 of file md.f90.
real(4) md::mu_w
Definition at line 69 of file md.f90.
integer md::n_max_insh
Definition at line 130 of file md.f90.
integer md::nat3
Definition at line 63 of file md.f90.
integer md::natom
Definition at line 62 of file md.f90.
integer, parameter md::nb_cycle_default = 10
Definition at line 158 of file md.f90.
integer md::nbcycle
Definition at line 105 of file md.f90.
type(nb_type), dimension(:), allocatable, target md::nbpp
Definition at line 264 of file md.f90.
type(cgp_pair_type), dimension(:), allocatable md::nbpp_cgp
Definition at line 287 of file md.f90.
integer md::nbpp_cgp_pair
Definition at line 286 of file md.f90.
integer md::nbpp_pair
Definition at line 263 of file md.f90.
type(nb_type), dimension(:), allocatable, target md::nbpw
Definition at line 270 of file md.f90.
type(cgp_pair_type), dimension(:), allocatable md::nbpw_cgp
Definition at line 289 of file md.f90.
integer md::nbpw_cgp_pair
Definition at line 288 of file md.f90.
integer md::nbpw_pair
Definition at line 269 of file md.f90.
type(nbqp_type), dimension(:), allocatable, target md::nbqp
Definition at line 279 of file md.f90.
type(cgp_pair_type), dimension(:), allocatable md::nbqp_cgp
Definition at line 291 of file md.f90.
integer md::nbqp_cgp_pair
Definition at line 290 of file md.f90.
integer md::nbqp_pair
Definition at line 278 of file md.f90.
type(nbq_type), dimension(:,:), allocatable md::nbqq
Definition at line 276 of file md.f90.
integer md::nbqq_max
Definition at line 272 of file md.f90.
integer, dimension(max_states) md::nbqq_pair
Definition at line 275 of file md.f90.
integer(ai), dimension(:), allocatable md::nbqw
Definition at line 282 of file md.f90.
integer md::nbqw_pair
Definition at line 281 of file md.f90.
integer(ai), dimension(:), allocatable, target md::nbww
Definition at line 267 of file md.f90.
integer md::nbww_pair
Definition at line 266 of file md.f90.
integer md::nbww_true_pair
Definition at line 266 of file md.f90.
integer md::ndegf
Definition at line 361 of file md.f90.
integer md::ndegf_solute
Definition at line 362 of file md.f90.
integer md::ndegf_solvent
Definition at line 363 of file md.f90.
integer md::ndegfree
Definition at line 361 of file md.f90.
integer md::ndegfree_solute
Definition at line 362 of file md.f90.
integer md::ndegfree_solvent
Definition at line 363 of file md.f90.
real(8), dimension(3) md::new_boxl
Definition at line 89 of file md.f90.
real(8), dimension(:), allocatable md::node_times
Definition at line 353 of file md.f90.
integer md::nrstr_dist
Definition at line 181 of file md.f90.
integer md::nrstr_pos
Definition at line 181 of file md.f90.
integer md::nrstr_seq
Definition at line 181 of file md.f90.
integer md::nrstr_wall
Definition at line 181 of file md.f90.
integer(ai), dimension(:,:), allocatable md::nsort
Definition at line 128 of file md.f90.
integer md::nsteps
Definition at line 95 of file md.f90.
integer, parameter md::num_profiling_times = 11
Definition at line 341 of file md.f90.
integer md::nwat
Definition at line 68 of file md.f90.
integer md::nwpolr_shell
Definition at line 130 of file md.f90.
type(lrf_type), dimension(:), allocatable md::old_lrf
Definition at line 309 of file md.f90.
real(8) md::pi
Definition at line 49 of file md.f90.
real(8) md::pressure
Definition at line 82 of file md.f90.
integer md::pressure_seed
Definition at line 83 of file md.f90.
type(profiling_var_type), dimension(num_profiling_times) md::profile
Definition at line 348 of file md.f90.
logical md::put_solute_back_in_box
Definition at line 77 of file md.f90.
logical md::put_solvent_back_in_box
Definition at line 77 of file md.f90.
integer(tiny), dimension(:,:,:), allocatable md::qconn
Definition at line 273 of file md.f90.
real(8) md::rclrf
Definition at line 106 of file md.f90.
real(8), parameter md::rclrf_default = 99.
Definition at line 151 of file md.f90.
real(8) md::rcpp
Definition at line 106 of file md.f90.
real(8), parameter md::rcpp_default = 10.
Definition at line 147 of file md.f90.
real(8) md::rcpw
Definition at line 106 of file md.f90.
real(8), parameter md::rcpw_default = 10.
Definition at line 149 of file md.f90.
real(8) md::rcq
Definition at line 106 of file md.f90.
real(8), parameter md::rcq_default = 99.
Definition at line 150 of file md.f90.
real(8) md::rcww
Definition at line 106 of file md.f90.
real(8), parameter md::rcww_default = 10.
Definition at line 148 of file md.f90.
logical md::restart
Definition at line 97 of file md.f90.
character(len=200) md::restart_file
Definition at line 170 of file md.f90.
real, parameter md::rho_wat = 0.0335
Definition at line 47 of file md.f90.
logical md::rigid_box_centre
Definition at line 76 of file md.f90.
type(rstrdis_type), dimension(:), allocatable md::rstdis
Definition at line 213 of file md.f90.
type(rstrpos_type), dimension(:), allocatable md::rstpos
Definition at line 212 of file md.f90.
type(rstrseq_type), dimension(:), allocatable md::rstseq
Definition at line 211 of file md.f90.
type(rstrwal_type), dimension(:), allocatable md::rstwal
Definition at line 214 of file md.f90.
real(8) md::rwat_in
Definition at line 124 of file md.f90.
logical md::separate_scaling
Definition at line 101 of file md.f90.
integer md::shake_constraints
Definition at line 334 of file md.f90.
logical md::shake_hydrogens
Definition at line 100 of file md.f90.
integer, parameter md::shake_max_iter = 1000
Definition at line 318 of file md.f90.
type(shake_mol_type), dimension(:), allocatable md::shake_mol
Definition at line 335 of file md.f90.
integer md::shake_molecules
Definition at line 334 of file md.f90.
logical md::shake_solute
Definition at line 99 of file md.f90.
logical md::shake_solvent
Definition at line 99 of file md.f90.
real(8), parameter md::shake_tol = 0.0001
Definition at line 317 of file md.f90.
real(8), parameter md::shell_default = 0.85
Definition at line 153 of file md.f90.
integer (tiny), dimension(:,:,:,:), allocatable md::special_ljcod
Definition at line 294 of file md.f90.
integer md::stat
Definition at line 52 of file md.f90.
real(8) md::tau_t
Definition at line 98 of file md.f90.
real(8), parameter md::tau_t_default = 10.
Definition at line 146 of file md.f90.
real(8), dimension(:), allocatable md::tdum
Definition at line 129 of file md.f90.
real(8) md::temp0
Definition at line 98 of file md.f90.
real, parameter md::temp_print_threshold =0.02
Definition at line 55 of file md.f90.
real(8) md::temp_solute
Definition at line 233 of file md.f90.
real(8) md::temp_solvent
Definition at line 233 of file md.f90.
real(8) md::texcl_solute
Definition at line 233 of file md.f90.
real(8) md::texcl_solvent
Definition at line 233 of file md.f90.
real(8) md::tfree
Definition at line 232 of file md.f90.
real(8) md::tfree_solute
Definition at line 232 of file md.f90.
real(8) md::tfree_solvent
Definition at line 232 of file md.f90.
real(8), dimension(:), allocatable md::theta
Definition at line 129 of file md.f90.
real(8), dimension(:), allocatable md::theta0
Definition at line 129 of file md.f90.
real(8) md::tmaxw
Definition at line 98 of file md.f90.
character(len=200) md::top_file
Definition at line 169 of file md.f90.
character(len=200) md::trj_file
Definition at line 172 of file md.f90.
logical md::use_lrf
Definition at line 104 of file md.f90.
real(8), dimension(:), allocatable md::v
Definition at line 223 of file md.f90.
integer md::volume_acc
Definition at line 81 of file md.f90.
integer md::volume_try
Definition at line 81 of file md.f90.
real, dimension(:), allocatable md::winv
Definition at line 224 of file md.f90.
logical md::wpol_born
Definition at line 126 of file md.f90.
logical md::wpol_restr
Definition at line 126 of file md.f90.
logical, parameter md::wpol_restr_default = .true.
Definition at line 161 of file md.f90.
real, parameter md::wpolr_layer = 3.0001
Definition at line 144 of file md.f90.
type(shell_type), dimension(:), allocatable md::wshell
Definition at line 139 of file md.f90.
real(8), dimension(:), allocatable md::x
Definition at line 221 of file md.f90.
character(len=200) md::xfin_file
Definition at line 171 of file md.f90.
character(len=200) md::xwat_file
Definition at line 176 of file md.f90.
real(8), dimension(:), allocatable md::xx
Definition at line 222 of file md.f90.
The documentation for this module was generated from the following file:
md.f90