misc Module Reference
Public Member Functions
subroutine centered_heading (msg, fill)
integer function freefile ()
subroutine skip_comments (unit)
subroutine getlin (intxt, outtxt)
subroutine upcase (string)
subroutine locase (string)
character(len=3) function onoff (l)
integer function string_part (string, separator, start)
real(8) function rtime ()
Private Attributes
character(*), parameter, private module_version = '5.01'
character(*), parameter, private modeule_date = '2003-06-02'
Detailed Description
Definition at line 6 of file misc.f90.
Member Function/Subroutine Documentation
subroutine misc::centered_heading (character(*) msg, character fill)
Definition at line 18 of file misc.f90.
Referenced by calc_menu(), check_inputfile(), md::die(), md::distribute_nonbonds(), md::get_fep(), md::init_nodes(), md::initialize(), list_calcs(), maskmanip::maskmanip_help(), maskmanip::maskmanip_help_pretop(), md::md_run(), md::prep_coord(), md::prep_sim(), print_headings(), process_help(), qatom::qatom_load_atoms(), qatom::qatom_load_fep(), qatom::qatom_old_load_atoms(), qatom::qatom_old_load_fep(), calc_chemscore::score_precalc(), md::shrink_topology(), calc_chemscore::start(), topo::topo_read(), topo::topo_save(), md::watpol(), and md::write_out().
integer function misc::freefile ()
Definition at line 28 of file misc.f90.
Referenced by calc_xscore::forcefield_read_atom_def(), calc_xscore::forcefield_read_residue_def(), calc_xscore::forcefield_read_surface_def(), calc_xscore::forcefield_read_xatom_def(), get_coordfile(), md::initialize(), parse::parse_open_file(), calc_pmf::pmf_extract_rules(), calc_pmf::pmfread_data(), calc_pmf::pmfread_input(), calc_pmf::pmfread_names(), calc_pmf::pmfreadatomtypeconversions(), prmfile::prm_open(), qfep(), prep::readx(), prep::solvate_restart(), topo::topo_open(), topo::topo_save(), trj::trj_create(), trj::trj_open(), prep::writemol2(), calc_xscore::xpatomnameconversions(), calc_xscore::xreadatomtypeconversions(), calc_xscore::xreadinput(), calc_xscore::xreadlib(), and calc_xscore::xreadresidueconversions().
subroutine misc::getlin (character(*), intent(out) intxt, character(*), intent(in), optional outtxt)
Definition at line 67 of file misc.f90.
Referenced by calc_entropy::entropy_add(), get_topology(), maskmanip::maskmanip_make(), calc_pmf::pmf_add(), calc_chemscore::score_add(), and calc_xscore::xscore_add().
subroutine misc::locase (character(*), intent(inout) string)
Definition at line 94 of file misc.f90.
Referenced by add_calcs(), calc_pmf::pmf_add(), calc_pmf::pmfreadatomtypeconversions(), qprep_from_commandline(), prep::readlib(), calc_chemscore::score_add(), calc_xscore::xpatomnameconversions(), calc_xscore::xreadatomtypeconversions(), calc_xscore::xreadresidueconversions(), and calc_xscore::xscore_add().
character(len=3) function misc::onoff (logical l)
Definition at line 106 of file misc.f90.
Referenced by md::initialize().
real(8) function misc::rtime ()
Definition at line 134 of file misc.f90.
Referenced by md::make_pair_lists(), md::md_run(), md::nbpplis2(), md::nbpplis2_box(), md::nbpplis2_box_lrf(), md::nbpplis2_lrf(), md::nbpplist(), md::nbpplist_box(), md::nbpplist_box_lrf(), md::nbpplist_lrf(), md::nbpwlis2(), md::nbpwlis2_box(), md::nbpwlis2_box_lrf(), md::nbpwlis2_lrf(), md::nbpwlist(), md::nbpwlist_box(), md::nbpwlist_box_lrf(), md::nbpwlist_lrf(), md::nbqplis2(), md::nbqplis2_box(), md::nbqplist(), md::nbqplist_box(), md::nbqwlist(), md::nbqwlist_box(), md::nbwwlist(), md::nbwwlist_box(), md::nbwwlist_box_lrf(), md::nbwwlist_lrf(), md::pot_energy(), and md::shake().
subroutine misc::skip_comments (integer unit)
Definition at line 50 of file misc.f90.
Referenced by prep::oldreadlib(), and prep::oldreadparm().
integer function misc::string_part (character(*) string, character(*) separator, integer start)
Definition at line 116 of file misc.f90.
References calc_chemscore::start().
Referenced by prep::readtop().
subroutine misc::upcase (character(*), intent(inout) string)
Definition at line 81 of file misc.f90.
Referenced by prep::addbond(), prmfile::find_section(), atom_mask::get_sybylcode(), prmfile::load(), atom_mask::mask_add(), maskmanip::maskmanip_make(), maskmanip::maskmanip_make_pretop(), prep::modify_mask(), calc_pmf::pmfread_input(), prmfile::prm_get_string_by_key(), qatom::qatom_load_atoms(), prep::readlib(), prep::readparm(), prep::set_boundary_condition(), prep::set_solvent_box(), prep::set_solvent_sphere(), prep::solvate_box(), prep::solvate_box_file(), prep::solvate_sphere(), prep::solvate_sphere_file(), topo::topo_read(), atom_mask::update(), calc_xscore::xpatomnameconversions(), and calc_xscore::xreadinput().
Member Data Documentation
character(*), parameter, private misc::modeule_date = '2003-06-02' [private]
Definition at line 14 of file misc.f90.
character(*), parameter, private misc::module_version = '5.01' [private]
Definition at line 13 of file misc.f90.
The documentation for this module was generated from the following file:
misc.f90