atom_mask Module Reference
Data Types
type mask_type
type set
Public Member Functions
subroutine mask_startup
subroutine mask_shutdown
subroutine mask_initialize (m)
subroutine mask_finalize (m)
subroutine mask_clear (m)
subroutine mask_all (m)
integer function mask_count (m)
integer function mask_add (m, line, pretop)
subroutine get_sybylcode (sybylname)
subroutine mask_get (m, x, xmasked)
subroutine mask_put (m, x, xmasked)
Private Member Functions
subroutine, private set_solute
logical function, private get_word (line, word, pos)
integer function, private update (s, m)
integer function, private update_pretop (s, m)
subroutine, private finalize_storage
Private Attributes
character(*), parameter, private module_version = '5.01'
character(*), parameter, private modeule_date = '2003-06-02'
logical(1), dimension(:),
*
allocatable, private solute
Detailed Description
Definition at line 6 of file mask.f90.
Member Function/Subroutine Documentation
subroutine, private atom_mask::finalize_storage () [private]
Definition at line 415 of file mask.f90.
Referenced by mask_shutdown().
subroutine atom_mask::get_sybylcode (character(*) sybylname)
Definition at line 389 of file mask.f90.
References misc::upcase().
Referenced by mask_add().
logical function, private atom_mask::get_word (character(*) line, character(*), intent(out) word, integer, intent(inout) pos) [private]
Definition at line 242 of file mask.f90.
Referenced by mask_add().
integer function atom_mask::mask_add (type(mask_type) m, character(*) line, logical, intent(in), optional pretop)
Definition at line 106 of file mask.f90.
References get_sybylcode(), get_word(), misc::upcase(), update(), and update_pretop().
Referenced by maskmanip::maskmanip_make(), maskmanip::maskmanip_make_pretop(), prep::modify_mask(), calc_nb::nb_qp_add(), trj::trj_add(), trj::trj_commit_mask(), and trj::trj_open().
subroutine atom_mask::mask_all (type(mask_type) m)
Definition at line 82 of file mask.f90.
Referenced by prep::set_default_mask().
subroutine atom_mask::mask_clear (type(mask_type) m)
Definition at line 72 of file mask.f90.
Referenced by mask_initialize(), maskmanip::maskmanip_make(), maskmanip::maskmanip_make_pretop(), prep::modify_mask(), and calc_nb::nb_qp_add().
integer function atom_mask::mask_count (type(mask_type) m)
Definition at line 92 of file mask.f90.
subroutine atom_mask::mask_finalize (type(mask_type) m)
Definition at line 63 of file mask.f90.
Referenced by calc_com::com_add(), calc_com::com_finalize(), calc_com_ke::com_ke_add(), calc_com_ke::com_ke_finalize(), calc_entropy::entropy_add(), calc_entropy::entropy_finalize(), calc_fit::fit_add(), calc_fit::fit_finalize(), calc_nb::nb_add(), calc_nb::nb_qp_add(), calc_pmf::pmf_add(), prep::prep_shutdown(), calc_rdf::rdf_add(), calc_rms::rms_add(), calc_rms::rms_finalize(), calc_rmsf::rmsf_add(), calc_rmsf::rmsf_finalize(), calc_chemscore::score_add(), prep::set_default_mask(), trj::trj_close(), and calc_xscore::xscore_add().
subroutine atom_mask::mask_get (type(mask_type) m, real(8), dimension(:) x, real, dimension(:) xmasked)
Definition at line 420 of file mask.f90.
Referenced by calc_com::com_calc(), calc_com_ke::com_ke_calc(), calc_entropy::entropy_calc(), calc_rms::rms_calc(), calc_rms::rms_make_ref(), calc_rmsf::rmsf_calc(), calc_rmsf::rmsf_make_ref(), and trj::trj_write().
subroutine atom_mask::mask_initialize (type(mask_type) m)
Definition at line 51 of file mask.f90.
References mask_clear(), and set_solute().
Referenced by calc_com::com_add(), calc_com_ke::com_ke_add(), calc_entropy::entropy_add(), calc_fit::fit_add(), prep::get_centre_by_mass(), calc_nb::nb_add(), calc_nb::nb_qp_add(), calc_pmf::pmf_add(), calc_rdf::rdf_add(), calc_rms::rms_add(), calc_rmsf::rmsf_add(), calc_chemscore::score_add(), prep::set_default_mask(), trj::trj_initialize(), trj::trj_open(), and calc_xscore::xscore_add().
subroutine atom_mask::mask_put (type(mask_type) m, real(8), dimension(:) x, real, dimension(:) xmasked)
Definition at line 446 of file mask.f90.
Referenced by trj::trj_read(), and avetr::write_average().
subroutine atom_mask::mask_shutdown ()
Definition at line 46 of file mask.f90.
References finalize_storage().
Referenced by finalize(), and trj::trj_shutdown().
subroutine atom_mask::mask_startup ()
Definition at line 41 of file mask.f90.
References topo::topo_startup().
Referenced by startup(), and trj::trj_startup().
subroutine, private atom_mask::set_solute () [private]
Definition at line 98 of file mask.f90.
Referenced by mask_initialize().
integer function, private atom_mask::update (type(set) s, type(mask_type) m) [private]
Definition at line 290 of file mask.f90.
References misc::upcase().
Referenced by mask_add().
integer function, private atom_mask::update_pretop (type(set) s, type(mask_type) m) [private]
Definition at line 351 of file mask.f90.
Referenced by mask_add().
Member Data Documentation
character(*), parameter, private atom_mask::modeule_date = '2003-06-02' [private]
Definition at line 13 of file mask.f90.
character(*), parameter, private atom_mask::module_version = '5.01' [private]
Definition at line 12 of file mask.f90.
logical(1), dimension(:), allocatable, private atom_mask::solute [private]
Definition at line 19 of file mask.f90.
The documentation for this module was generated from the following file:
mask.f90