calc_nb Module Reference
Data Types
type averages
type nb_list_type
type nb_qp_type
Public Member Functions
subroutine nb_initialize
subroutine nb_finalize (i)
integer function nb_add (desc)
subroutine nb_calc (i)
subroutine nb_calc_lists (NB_Vlj, NB_Vel, nb_list)
subroutine nb_make_list (mask1, mask2, nb_list)
subroutine nb_heading (i)
integer function nb_qp_add (desc)
subroutine nb_qp_calc ()
subroutine nb_qp_finalize ()
subroutine nb_initialize
subroutine nb_finalize (i)
integer function nb_add (desc)
subroutine calc_center ()
integer function dist_group1 (atom2)
subroutine nb_calc (i)
subroutine nb_calc_lists (NB_Vlj, NB_Vel, nb_list)
subroutine nb_make_list (mask1, mask2, nb_list)
subroutine nb_heading (i)
integer function nb_qp_add (desc)
subroutine nb_qp_calc ()
subroutine nb_qp_finalize ()
Public Attributes
integer, parameter max_lists = 20
integer, parameter max_nb_qp = 1
type(averages), dimension(:),
*
allocatable aves
type(averages), dimension(:),
*
allocatable qp_aves
integer, dimension(:), allocatable total_frames
integer total_qp_frames = 0
real, dimension(3) center_mask1
real, dimension(10, 100) ave_elj_r
real, dimension(100) elj_r
Private Attributes
type(mask_type), dimension(2),
*
target, private masks
integer, private nlists = 0
integer, private n_nb_qp = 0
type(nb_list_type), dimension(:),
*
allocatable, private nb_listan
type(nb_list_type), dimension(:),
*
allocatable, private nb_list_res
type(nb_qp_type), private qp_calc
Detailed Description
Definition at line 9 of file calc_nb.f90.
Member Function/Subroutine Documentation
subroutine calc_nb::calc_center ()
Definition at line 152 of file calc_nb_radius.f90.
Referenced by nb_calc_lists().
integer function calc_nb::dist_group1 (integer atom2)
Definition at line 194 of file calc_nb_radius.f90.
Referenced by nb_calc_lists().
integer function calc_nb::nb_add (character(*) desc)
Definition at line 70 of file calc_nb.f90.
References atom_mask::mask_finalize(), atom_mask::mask_initialize(), maskmanip::maskmanip_make(), and nb_make_list().
Referenced by add_a_calc(), and nb_add().
integer function calc_nb::nb_add (character(*) desc)
Definition at line 77 of file calc_nb_radius.f90.
References atom_mask::mask_finalize(), atom_mask::mask_initialize(), maskmanip::maskmanip_make(), nb_add(), and nb_make_list().
subroutine calc_nb::nb_calc (integer i)
Definition at line 142 of file calc_nb.f90.
References nb_calc_lists().
Referenced by calc_all().
subroutine calc_nb::nb_calc (integer i)
Definition at line 217 of file calc_nb_radius.f90.
References nb_calc_lists().
subroutine calc_nb::nb_calc_lists (real(8), intent(out) NB_Vlj, real(8), intent(out) NB_Vel, type(nb_list_type), intent(in) nb_list)
Definition at line 239 of file calc_nb_radius.f90.
References calc_center(), dist_group1(), and calc_rdf::r().
subroutine calc_nb::nb_calc_lists (real(8), intent(out) NB_Vlj, real(8), intent(out) NB_Vel, type(nb_list_type), intent(in) nb_list)
Definition at line 162 of file calc_nb.f90.
References calc_rdf::r().
Referenced by nb_calc(), and nb_qp_calc().
subroutine calc_nb::nb_finalize (integer i)
Definition at line 56 of file calc_nb.f90.
Referenced by finalize().
subroutine calc_nb::nb_finalize (integer i)
Definition at line 58 of file calc_nb_radius.f90.
subroutine calc_nb::nb_heading (integer i)
Definition at line 449 of file calc_nb_radius.f90.
subroutine calc_nb::nb_heading (integer i)
Definition at line 360 of file calc_nb.f90.
Referenced by print_headings().
subroutine calc_nb::nb_initialize ()
Definition at line 47 of file calc_nb.f90.
Referenced by initialize().
subroutine calc_nb::nb_initialize ()
Definition at line 49 of file calc_nb_radius.f90.
subroutine calc_nb::nb_make_list (type(mask_type), intent(in) mask1, type(mask_type), intent(in) mask2, type(nb_list_type) nb_list)
Definition at line 295 of file calc_nb_radius.f90.
subroutine calc_nb::nb_make_list (type(mask_type), intent(in) mask1, type(mask_type), intent(in) mask2, type(nb_list_type) nb_list)
Definition at line 206 of file calc_nb.f90.
Referenced by nb_add(), and nb_qp_add().
integer function calc_nb::nb_qp_add (character(*) desc)
Definition at line 375 of file calc_nb.f90.
References parse::get_int_arg(), atom_mask::mask_add(), atom_mask::mask_clear(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), maskmanip::maskmanip_make(), and nb_make_list().
Referenced by add_a_calc(), and nb_qp_add().
integer function calc_nb::nb_qp_add (character(*) desc)
Definition at line 464 of file calc_nb_radius.f90.
References parse::get_int_arg(), atom_mask::mask_add(), atom_mask::mask_clear(), atom_mask::mask_finalize(), atom_mask::mask_initialize(), maskmanip::maskmanip_make(), nb_make_list(), and nb_qp_add().
subroutine calc_nb::nb_qp_calc ()
Definition at line 436 of file calc_nb.f90.
References nb_calc_lists().
Referenced by calc_all().
subroutine calc_nb::nb_qp_calc ()
Definition at line 523 of file calc_nb_radius.f90.
References nb_calc_lists().
subroutine calc_nb::nb_qp_finalize ()
Definition at line 542 of file calc_nb_radius.f90.
subroutine calc_nb::nb_qp_finalize ()
Definition at line 455 of file calc_nb.f90.
Referenced by finalize().
Member Data Documentation
real, dimension(10,100) calc_nb::ave_elj_r
Definition at line 43 of file calc_nb_radius.f90.
type(averages), dimension(:), allocatable calc_nb::aves
Definition at line 33 of file calc_nb.f90.
real, dimension(3) calc_nb::center_mask1
Definition at line 43 of file calc_nb_radius.f90.
real, dimension(100) calc_nb::elj_r
Definition at line 43 of file calc_nb_radius.f90.
type(mask_type), dimension(2), target, private calc_nb::masks [private]
Definition at line 20 of file calc_nb.f90.
integer parameter calc_nb::max_lists = 20
Definition at line 17 of file calc_nb.f90.
integer parameter calc_nb::max_nb_qp = 1
Definition at line 18 of file calc_nb.f90.
integer private calc_nb::n_nb_qp = 0 [private]
Definition at line 22 of file calc_nb.f90.
type(nb_list_type), dimension(:), allocatable, private calc_nb::nb_list_res [private]
Definition at line 29 of file calc_nb.f90.
type(nb_list_type), dimension(:), allocatable, private calc_nb::nb_listan [private]
Definition at line 28 of file calc_nb.f90.
integer private calc_nb::nlists = 0 [private]
Definition at line 21 of file calc_nb.f90.
type(averages), dimension(:), allocatable calc_nb::qp_aves
Definition at line 34 of file calc_nb.f90.
type(nb_qp_type), private calc_nb::qp_calc [private]
Definition at line 41 of file calc_nb.f90.
integer, dimension(:), allocatable calc_nb::total_frames
Definition at line 35 of file calc_nb.f90.
integer calc_nb::total_qp_frames = 0
Definition at line 36 of file calc_nb.f90.
The documentation for this module was generated from the following files:
calc_nb.f90
calc_nb_radius.f90