indexer Module Reference
Data Types
type indexentry
Public Member Functions
subroutine index_create (size)
subroutine index_clear
subroutine index_shutdown
subroutine index_startup
subroutine index_resize (size)
logical function index_add (key, index)
logical function index_alias (alias, key)
logical function index_get (key, i, allow_wildcard)
Public Attributes
integer, parameter keylength = 8
Private Member Functions
subroutine, private grow
Private Attributes
character(*), parameter, private module_version = '5.01'
character(*), parameter, private module_date = '2003-06-02'
integer, private count = 0
integer, private top = 0
integer, parameter, private resize_increment = 10
type(indexentry), dimension(:),
*
pointer, private ndx
integer, private memstat
Detailed Description
Definition at line 6 of file index.f90.
Member Function/Subroutine Documentation
subroutine, private indexer::grow () [private]
Definition at line 85 of file index.f90.
References index_resize().
Referenced by index_add().
logical function indexer::index_add (character(*) key, integer index)
Definition at line 89 of file index.f90.
References grow().
Referenced by index_alias(), calc_chemscore::make_tac_index(), prep::oldreadparm(), qatom::qatom_load_fep(), prep::readlib(), and prep::readparm().
logical function indexer::index_alias (character(*) alias, character(*) key)
Definition at line 118 of file index.f90.
References index_add(), and index_get().
Referenced by prep::readparm().
subroutine indexer::index_clear ()
Definition at line 46 of file index.f90.
Referenced by index_create(), index_resize(), and index_shutdown().
subroutine indexer::index_create (integer, optional size)
Definition at line 30 of file index.f90.
References index_clear().
Referenced by calc_chemscore::make_tac_index(), prep::oldreadparm(), qatom::qatom_load_fep(), prep::readlib(), and prep::readparm().
logical function indexer::index_get (character(*), intent(in) key, integer, intent(out) i, logical, optional allow_wildcard)
Definition at line 132 of file index.f90.
Referenced by calc_chemscore::get_atom_data(), index_alias(), qatom::qatom_load_fep(), prep::readlib(), prep::readparm(), prep::set_iac(), and prep::set_solvent_type().
subroutine indexer::index_resize (integer size)
Definition at line 61 of file index.f90.
References index_clear().
Referenced by grow(), and prep::readparm().
subroutine indexer::index_shutdown ()
Definition at line 54 of file index.f90.
References index_clear().
Referenced by prep::prep_shutdown().
subroutine indexer::index_startup ()
Definition at line 58 of file index.f90.
Referenced by prep::prep_startup().
Member Data Documentation
integer, private indexer::count = 0 [private]
Definition at line 14 of file index.f90.
integer, parameter indexer::keylength = 8
Definition at line 15 of file index.f90.
integer, private indexer::memstat [private]
Definition at line 24 of file index.f90.
character(*), parameter, private indexer::module_date = '2003-06-02' [private]
Definition at line 12 of file index.f90.
character(*), parameter, private indexer::module_version = '5.01' [private]
Definition at line 11 of file index.f90.
type(indexentry), dimension(:), pointer, private indexer::ndx [private]
Definition at line 22 of file index.f90.
integer, parameter, private indexer::resize_increment = 10 [private]
Definition at line 16 of file index.f90.
integer, private indexer::top = 0 [private]
Definition at line 14 of file index.f90.
The documentation for this module was generated from the following file:
index.f90