eigen.f90 File Reference
Functions/Subroutines
subroutine eigen (A, R, N, MV)
Function/Subroutine Documentation
subroutine eigen (dimension(1) A, dimension(1) R, N, MV)
Definition at line 1 of file eigen.f90.
References calc_rdf::r().
Referenced by calc_com_ke::com_ke_calc(), calc_fit::lsqstr(), calc_entropy::pca(), and calc_entropy::quasiharmonic_analysis().