qcalc.f90 File Reference
Data Types
type calc_type
type calc_kind_type
Functions/Subroutines
program qcalc
subroutine startup
subroutine shutdown
logical function get_topology ()
subroutine initialize
subroutine do_pre_calcs
subroutine finalize
subroutine calc_help
subroutine process_help
subroutine finishtrj_all
subroutine process_data
subroutine process_frame (cf, frame)
subroutine make_mean_all
logical function get_coordfile (cf, fn, frames)
logical function load_restart (fn)
subroutine finalize_topology
subroutine add_kind (desc, key, output)
subroutine calc_menu
subroutine add_calcs
subroutine make_ref_all (x)
subroutine list_calcs
subroutine add_a_calc (kind)
subroutine print_headings
subroutine calc_all (frame)
Function/Subroutine Documentation
subroutine qcalc::add_a_calc (integer kind)
Definition at line 528 of file qcalc.f90.
References calc_geom::angle_add(), calc_com::com_add(), calc_com_ke::com_ke_add(), calc_geom::dist_add(), calc_entropy::entropy_add(), calc_fit::fit_add(), calc_nb::nb_add(), calc_nb::nb_qp_add(), calc_pmf::pmf_add(), calc_rdf::rdf_add(), calc_rms::rms_add(), calc_rmsf::rmsf_add(), calc_chemscore::score_add(), calc_geom::torsion_add(), and calc_xscore::xscore_add().
Referenced by add_calcs().
subroutine qcalc::add_calcs ()
Definition at line 455 of file qcalc.f90.
References add_a_calc(), calc_menu(), list_calcs(), and misc::locase().
subroutine qcalc::add_kind (character(*) desc, character(*) key, logical output)
Definition at line 426 of file qcalc.f90.
subroutine qcalc::calc_all (integer frame)
Definition at line 632 of file qcalc.f90.
References calc_geom::angle_calc(), calc_com::com_calc(), calc_com_ke::com_ke_calc(), calc_geom::dist_calc(), calc_entropy::entropy_calc(), calc_fit::fit_calc(), calc_nb::nb_calc(), calc_nb::nb_qp_calc(), calc_pmf::pmf_calc(), calc_rdf::rdf_calc(), calc_rms::rms_calc(), calc_rmsf::rmsf_calc(), calc_chemscore::score_calc(), calc_geom::torsion_calc(), and calc_xscore::xscore_calc().
Referenced by process_frame().
subroutine qcalc::calc_help ()
Definition at line 204 of file qcalc.f90.
Referenced by startup().
subroutine qcalc::calc_menu ()
Definition at line 440 of file qcalc.f90.
References misc::centered_heading().
Referenced by add_calcs().
subroutine qcalc::do_pre_calcs ()
Definition at line 141 of file qcalc.f90.
References calc_pmf::pmf_precalc(), calc_chemscore::score_precalc(), and calc_xscore::xscore_precalc().
subroutine qcalc::finalize ()
Definition at line 159 of file qcalc.f90.
References calc_chemscore::chemscore_finalize(), calc_com::com_finalize(), calc_com_ke::com_ke_finalize(), calc_entropy::entropy_finalize(), calc_fit::fit_finalize(), atom_mask::mask_shutdown(), calc_nb::nb_finalize(), calc_nb::nb_qp_finalize(), calc_pmf::pmf_finalize(), calc_rdf::rdf_finalize(), calc_rms::rms_finalize(), calc_rmsf::rmsf_finalize(), and calc_xscore::xscore_finalize().
subroutine qcalc::finalize_topology ()
Definition at line 422 of file qcalc.f90.
References topo::topo_deallocate().
subroutine qcalc::finishtrj_all ()
Definition at line 221 of file qcalc.f90.
logical function qcalc::get_coordfile (character(len=256), intent(out) cf, integer, intent(out) fn, character(len=80), optional frames)
Definition at line 322 of file qcalc.f90.
References misc::freefile(), make_mean_all(), make_ref_all(), and trj::trj_open().
Referenced by process_data().
logical function qcalc::get_topology ()
Definition at line 113 of file qcalc.f90.
References misc::getlin(), and topo::topo_load().
subroutine qcalc::initialize ()
Definition at line 124 of file qcalc.f90.
References calc_com::com_initialize(), calc_com_ke::com_ke_initialize(), calc_entropy::entropy_initialize(), calc_fit::fit_initialize(), calc_geom::geom_initialize(), calc_nb::nb_initialize(), calc_pmf::pmf_initialize(), calc_rdf::rdf_initialize(), calc_rms::rms_initialize(), calc_rmsf::rmsf_initialize(), calc_chemscore::score_initialize(), and calc_xscore::xscore_initialize().
Referenced by md::initialize(), and qdyn().
subroutine qcalc::list_calcs ()
Definition at line 517 of file qcalc.f90.
References misc::centered_heading().
Referenced by add_calcs(), and print_headings().
logical function qcalc::load_restart (integer, intent(in) fn)
Definition at line 391 of file qcalc.f90.
Referenced by process_data().
subroutine qcalc::make_mean_all ()
Definition at line 305 of file qcalc.f90.
References calc_pmf::pmfscore_mean(), calc_chemscore::score_mean(), and calc_xscore::xscore_mean().
Referenced by get_coordfile().
subroutine qcalc::make_ref_all (real(8), dimension(:) x)
Definition at line 495 of file qcalc.f90.
References calc_fit::fit_make_ref(), calc_rms::rms_make_ref(), and calc_rmsf::rmsf_make_ref().
Referenced by get_coordfile().
subroutine qcalc::print_headings ()
Definition at line 581 of file qcalc.f90.
References calc_geom::angle_heading(), misc::centered_heading(), calc_com::com_heading(), calc_com_ke::com_ke_heading(), calc_geom::dist_heading(), list_calcs(), calc_nb::nb_heading(), calc_pmf::pmf_heading(), calc_rdf::rdf_heading(), calc_rms::rms_heading(), calc_rmsf::rmsf_heading(), calc_chemscore::score_heading(), calc_geom::torsion_heading(), and calc_xscore::xscore_heading().
subroutine qcalc::process_data ()
Definition at line 230 of file qcalc.f90.
References get_coordfile(), load_restart(), process_frame(), trj::trj_close(), and trj::trj_read().
subroutine qcalc::process_frame (character(*) cf, integer frame)
Definition at line 282 of file qcalc.f90.
References calc_all().
Referenced by process_data().
subroutine qcalc::process_help ()
Definition at line 213 of file qcalc.f90.
References misc::centered_heading().
program qcalc ()
Definition at line 6 of file qcalc.f90.
subroutine qcalc::shutdown ()
Definition at line 110 of file qcalc.f90.
Referenced by qdyn(), and qprep().
subroutine qcalc::startup ()
Definition at line 97 of file qcalc.f90.
References calc_help(), and atom_mask::mask_startup().
Referenced by qdyn(), and qprep().