qdyn.f90 File Reference
Functions/Subroutines
program qdyn
subroutine startup
subroutine shutdown
integer(4) function signal (signum, proc, flag)
INTEGER(4) function sigint_handler (sig_num)
INTEGER(4) function sigkill_handler (sig_num)
INTEGER(4) function sigabrt_handler (sig_num)
Function/Subroutine Documentation
program qdyn ()
Definition at line 19 of file qdyn.f90.
References md::close_input_files(), md::close_output_files(), md::die(), md::distribute_nonbonds(), md::get_fep(), md::init_nodes(), md::init_shake(), md::init_trj(), md::initial_shaking(), initialize(), md::make_nbqqlist(), md::maxwell(), md::md_run(), md::nbmonitorlist(), md::open_files(), md::prep_coord(), md::prep_sim(), md::shrink_topology(), shutdown(), sigabrt_handler(), sigint_handler(), sigkill_handler(), signal(), startup(), md::stop_cm_translation(), and md::topology().
subroutine qdyn::shutdown ()
Definition at line 164 of file qdyn.f90.
References md::md_shutdown().
INTEGER(4) function sigabrt_handler (integer(4) sig_num)
Definition at line 217 of file qdyn.f90.
References md::die().
Referenced by qdyn().
INTEGER(4) function sigint_handler (integer(4) sig_num)
Definition at line 199 of file qdyn.f90.
References md::die().
Referenced by qdyn().
INTEGER(4) function sigkill_handler (integer(4) sig_num)
Definition at line 208 of file qdyn.f90.
References md::die().
Referenced by qdyn().
integer(4) function qdyn::signal (integer(4) signum, external proc, integer(4) flag)
Definition at line 182 of file qdyn.f90.
Referenced by qdyn().
subroutine qdyn::startup ()
Definition at line 132 of file qdyn.f90.
References md::md_startup().