qfep.f90 File Reference
Data Types
type fep_data_type
Functions/Subroutines
program qfep
subroutine prompt (outtxt)
subroutine tred2 (A, N, NP, D, E)
subroutine tqli (D, E, N, NP, Z)
Function/Subroutine Documentation
subroutine qfep::prompt (character(*) outtxt)
Definition at line 521 of file qfep.f90.
Referenced by prep::changeimp(), parse::get_int_arg(), parse::get_line_arg(), parse::get_real_arg(), parse::get_string_arg(), parse::get_string_single_line(), and qfep().
program qfep ()
Definition at line 6 of file qfep.f90.
subroutine qfep::tqli (real(8), dimension(:) D, real(8), dimension(:) E, integer N, integer NP, real(8), dimension(:,:) Z)
Definition at line 639 of file qfep.f90.
References calc_rdf::r().
Referenced by qfep().
subroutine qfep::tred2 (real(8), dimension(:,:) A, integer N, integer NP, real(8), dimension(:) D, real(8), dimension(:) E)
Definition at line 545 of file qfep.f90.
Referenced by qfep().