qfep_bar.f90 File Reference
Data Types
type fep_data_type
Functions/Subroutines
program qfep
subroutine prompt (outtxt)
subroutine tred2 (A, N, NP, D, E)
subroutine tqli (D, E, N, NP, Z)
Function/Subroutine Documentation
subroutine qfep::prompt (character*(*) outtxt)
Definition at line 770 of file qfep_bar.f90.
program qfep ()
Definition at line 6 of file qfep_bar.f90.
References misc::freefile(), nrgy::get_ene(), parse::openit(), prompt(), tqli(), and tred2().
subroutine qfep::tqli (real(8), dimension(:) D, real(8), dimension(:) E, integer N, integer NP, real(8), dimension(:,:) Z)
Definition at line 890 of file qfep_bar.f90.
References calc_rdf::r().
subroutine qfep::tred2 (real(8), dimension(:,:) A, integer N, integer NP, real(8), dimension(:) D, real(8), dimension(:) E)
Definition at line 796 of file qfep_bar.f90.