qprep.f90 File Reference
Functions/Subroutines
program qprep
subroutine qprep_from_inputfile (filename)
subroutine qprep_from_commandline
subroutine parse_command (command)
subroutine help
subroutine startup
subroutine shutdown
logical function check_inputfile (infilename)
Function/Subroutine Documentation
logical function qprep::check_inputfile (character(200), intent(out) infilename)
Definition at line 302 of file qprep.f90.
References misc::centered_heading().
Referenced by qprep().
subroutine qprep::help ()
Definition at line 183 of file qprep.f90.
Referenced by parse_command().
subroutine qprep::parse_command (character(*), intent(in) command)
Definition at line 104 of file qprep.f90.
References prep::addbond(), avetr::avetr_calc(), prep::changeimp(), prep::checkangs(), prep::checkbonds(), prep::checkimps(), prep::checktors(), prep::clearbond(), prep::clearlib(), prep::cleartop(), prep::define_boundary_condition(), help(), prep::listprefs(), prep::listres(), prep::listseq(), md::make_shell2(), prep::maketop(), prep::modify_mask(), prep::readff(), prep::readframe(), prep::readlib(), prep::readnext(), prep::readpdb(), prep::readtop(), prep::readx(), prep::set(), prep::solvate(), prep::trajectory(), prep::writemol2(), prep::writepdb(), prep::writetop(), and prep::xlink().
Referenced by qprep_from_commandline(), and qprep_from_inputfile().
program qprep ()
Definition at line 18 of file qprep.f90.
References check_inputfile(), prep::clearlib(), qprep_from_commandline(), qprep_from_inputfile(), shutdown(), startup(), and topo::topo_set_max().
subroutine qprep::qprep_from_commandline ()
Definition at line 83 of file qprep.f90.
References parse::get_string_arg(), misc::locase(), parse_command(), and parse::parse_reset().
Referenced by qprep().
subroutine qprep::qprep_from_inputfile (character(200) filename)
Definition at line 51 of file qprep.f90.
References parse::get_string_arg(), parse_command(), and parse::parse_open_file().
Referenced by qprep().
subroutine qprep::shutdown ()
Definition at line 293 of file qprep.f90.
References prep::prep_shutdown().
subroutine qprep::startup ()
Definition at line 278 of file qprep.f90.
References prep::prep_startup().